### ISSUE TITLE
Memory leak - allocates > 37GB of RAM

### ISSUE THREAD

**Issue by h0wXD** [docker/for-win#10179]
* [x]  I have tried with the latest version of Docker Desktop
* [ ]  I have tried disabling enabled experimental features
* [ ]  I have uploaded Diagnostics
* Diagnostics ID:
* [x]  I am using the Docker WSL2 Backend
* [ ]  I am using the Docker Hyper-V Backend

### Actual behavior
Docker desktop 3.1.0, which I just updated to yesterday, crashed my entire workstation, eating up all available memory and causing applications to crash. 
I have 'Send usage statistics' enabled but had to manually terminate the process by task manager.

### Expected behavior
No memory leak

### Information
* Windows Version: Windows 10, Version 20H2 (OS Build 19042.685)
* Docker Desktop Version: 3.1.0 (51484)
* WSL2 or Hyper-V backend? WSL2 
* Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
I don't know how to reproduce, but I only did few things:
right click the tray, open settings
right click the tray, dashboard, scrolled down to a docker-compose of redis-master/redis-slave, saw the console, and closed the window again. 

![image](https://user-images.githubusercontent.com/10574115/105436135-9a18cb80-5c99-11eb-9a2f-86945cb1b3d7.png)

**Comment by stephen-turner** [comment]
Thanks for the report. I've never seen that before. Is it repeatable or was it a one-off?

**Comment by h0wXD** [comment]
It was a one-off, and I have been unable to repro

**Comment by stephen-turner** [comment]
OK, thanks. I'm not sure how much we're going to be able to do about it in that case. Please do let us know if happens again, and if it does please try and capture diagnostics.

**Comment by MichalLytek** [comment]
@stephen-turner It happened also for me a few times, I only had small postgres db running.
It started to happening after the last update I believe.

How can I help and how can I provide the diagnostics info? 😉

**Comment by stephen-turner** [comment]
Thank you. From the whale menu, Troubleshoot-Support.

**Comment by juanvoxelcare** [comment]
Hello , i have the same behaviour, i have the same Windows version Docker version and also using integration with WSL2

**Comment by stephen-turner** [comment]
@juanvoxelcare Do you have a diagnostics id you can send us?

**Comment by ilbunilcho** [comment]
same here..

win 10 20H2 (19042.804)
docker 3.1.0 (51484)

use wsl2 backends in docker settings (but hyper-v enabled in windows)
no anti-virus software running

docker running postgresql 13.2

checked docker stats in wsl2
looks normal.. only consume 300Mb memory with low cpu usage (configured wsl2.conf for memory limit)

I think wsl2 and windows system looks fine..

but Docker Desktop.exe memory usage going crazy..
now using 24Gb of 32Gb

when I clicked troubleshoot->clean/purge data->hyper-v
memory usage going down to 12Gb then keep growing up to 24Gb..

just watching memory usage in few minutes..
hit 24Gb
going down 15Gb
growing to 24Gb

cycling this..

after turning on debug mode

[kmsg.log]
2021-02-17T20:54:38Z kmsg (1582974) - 2021-02-17T15:14:29.9353696Z: FS-Cache: O-key=[8] '9319010000000d00'
2021-02-17T20:54:38Z kmsg (1582975) - 2021-02-17T15:14:29.9353716Z: FS-Cache: N-cookie c=000000002e4d8396 [p=00000000e7327a8b fl=2 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582976) - 2021-02-17T15:14:29.9353716Z: FS-Cache: N-cookie d=00000000ae03ae1d n=000000006b624e26
2021-02-17T20:54:38Z kmsg (1582977) - 2021-02-17T15:14:29.9353726Z: FS-Cache: N-key=[8] '9319010000000d00'
2021-02-17T20:54:38Z kmsg (1582978) - 2021-02-17T15:14:29.9428956Z: FS-Cache: Duplicate cookie detected
2021-02-17T20:54:38Z kmsg (1582979) - 2021-02-17T15:14:29.9428976Z: FS-Cache: O-cookie c=0000000094409fa6 [p=00000000e7327a8b fl=226 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582980) - 2021-02-17T15:14:29.9428986Z: FS-Cache: O-cookie d=00000000ae03ae1d n=00000000bf4575d3
2021-02-17T20:54:38Z kmsg (1582981) - 2021-02-17T15:14:29.9428986Z: FS-Cache: O-key=[8] '9419010000001300'
2021-02-17T20:54:38Z kmsg (1582982) - 2021-02-17T15:14:29.9429006Z: FS-Cache: N-cookie c=00000000453d96a4 [p=00000000e7327a8b fl=2 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582983) - 2021-02-17T15:14:29.9429006Z: FS-Cache: N-cookie d=00000000ae03ae1d n=0000000063a4fbbd
2021-02-17T20:54:38Z kmsg (1582984) - 2021-02-17T15:14:29.9429016Z: FS-Cache: N-key=[8] '9419010000001300'
2021-02-17T20:54:38Z kmsg (1582985) - 2021-02-17T15:14:29.9477856Z: FS-Cache: Duplicate cookie detected
2021-02-17T20:54:38Z kmsg (1582986) - 2021-02-17T15:14:29.9477876Z: FS-Cache: O-cookie c=00000000d66c49f5 [p=00000000e7327a8b fl=226 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582987) - 2021-02-17T15:14:29.9477876Z: FS-Cache: O-cookie d=00000000ae03ae1d n=0000000038f3affc
2021-02-17T20:54:38Z kmsg (1582988) - 2021-02-17T15:14:29.9477886Z: FS-Cache: O-key=[8] '9519010000000f00'
2021-02-17T20:54:38Z kmsg (1582989) - 2021-02-17T15:14:29.9477896Z: FS-Cache: N-cookie c=00000000453d96a4 [p=00000000e7327a8b fl=2 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582990) - 2021-02-17T15:14:29.9477906Z: FS-Cache: N-cookie d=00000000ae03ae1d n=00000000a037e171
2021-02-17T20:54:38Z kmsg (1582991) - 2021-02-17T15:14:29.9477906Z: FS-Cache: N-key=[8] '9519010000000f00'
2021-02-17T20:54:38Z kmsg (1582992) - 2021-02-17T15:14:29.9865616Z: FS-Cache: Duplicate cookie detected
2021-02-17T20:54:38Z kmsg (1582993) - 2021-02-17T15:14:29.9865636Z: FS-Cache: O-cookie c=00000000d6f7c932 [p=00000000e7327a8b fl=226 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582994) - 2021-02-17T15:14:29.9865646Z: FS-Cache: O-cookie d=00000000ae03ae1d n=00000000cb7e2e47
2021-02-17T20:54:38Z kmsg (1582995) - 2021-02-17T15:14:29.9865646Z: FS-Cache: O-key=[8] '9619010000000b00'
2021-02-17T20:54:38Z kmsg (1582996) - 2021-02-17T15:14:29.9865666Z: FS-Cache: N-cookie c=00000000fa5dc111 [p=00000000e7327a8b fl=2 nc=0 na=1]
2021-02-17T20:54:38Z kmsg (1582997) - 2021-02-17T15:14:29.9865666Z: FS-Cache: N-cookie d=00000000ae03ae1d n=0000000019166301



**dup cookie detected log cycling..**


2021-02-17T20:54:38Z kmsg (1584644) - 2021-02-17T20:54:34.7001486Z: init: (2) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
2021-02-17T20:54:38Z kmsg (1584645) - 2021-02-17T20:54:34.7002036Z: init: (1) ERROR: UtilCreateProcessAndWait:489: /bin/mount failed with status 0x
2021-02-17T20:54:38Z kmsg (1584646) - 2021-02-17T20:54:34.7002046Z: ff00
2021-02-17T20:54:38Z kmsg (1584647) - 2021-02-17T20:54:34.7002066Z: init: (1) ERROR: ConfigMountFsTab:2077: Processing fstab with mount -a failed.
2021-02-17T20:54:38Z kmsg (1584648) - 2021-02-17T20:54:34.7008926Z: init: (3) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
2021-02-17T20:54:38Z kmsg (1584649) - 2021-02-17T20:54:34.7009406Z: init: (1) ERROR: UtilCreateProcessAndWait:489: /bin/mount failed with status 0x
2021-02-17T20:54:38Z kmsg (1584650) - 2021-02-17T20:54:34.7009416Z: ff00
2021-02-17T20:54:38Z kmsg (1584651) - 2021-02-17T20:54:34.7009436Z: init: (1) ERROR: MountPlan9:478: mount cache=mmap,noatime,trans=fd,rfdno=8,wfdno=8,msize=65536,aname=drvfs;path=C:\x5c;uid=0;gid=0;symlinkroot=/mnt/
2021-02-17T20:54:38Z kmsg (1584652) - 2021-02-17T20:54:34.7009446Z:  failed 17
2021-02-17T20:54:38Z kmsg (1584653) - 2021-02-17T20:54:34.7014236Z: init: (4) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
2021-02-17T20:54:38Z kmsg (1584654) - 2021-02-17T20:54:34.9312726Z: ISO 9660 Extensions: RRIP_1991A
2021-02-17T20:54:40Z kmsg (1584655) - 2021-02-17T20:54:39.5345646Z: WSL2: Performing memory compaction.
2021-02-17T20:55:04Z kmsg (1584656) - 2021-02-17T20:55:04.0888806Z: docker0: port 1(veth0d948f5) entered blocking state
2021-02-17T20:55:04Z kmsg (1584657) - 2021-02-17T20:55:04.0888816Z: docker0: port 1(veth0d948f5) entered disabled state
2021-02-17T20:55:04Z kmsg (1584658) - 2021-02-17T20:55:04.0889486Z: device veth0d948f5 entered promiscuous mode
2021-02-17T20:55:06Z kmsg (1584659) - 2021-02-17T20:55:05.8498426Z: eth0: renamed from veth3a34011
2021-02-17T20:55:06Z kmsg (1584660) - 2021-02-17T20:55:05.8501096Z: IPv6: ADDRCONF(NETDEV_CHANGE): veth0d948f5: link becomes ready
2021-02-17T20:55:06Z kmsg (1584661) - 2021-02-17T20:55:05.8501246Z: docker0: port 1(veth0d948f5) entered blocking state
2021-02-17T20:55:06Z kmsg (1584662) - 2021-02-17T20:55:05.8501246Z: docker0: port 1(veth0d948f5) entered forwarding state
2021-02-17T20:55:06Z kmsg (1584663) - 2021-02-17T20:55:05.8501456Z: IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
2021-02-17T20:55:41Z kmsg (1584664) - 2021-02-17T20:55:40.5360726Z: WSL2: Performing memory compaction.
2021-02-17T20:56:42Z kmsg (1584665) - 2021-02-17T20:56:41.5376486Z: WSL2: Performing memory compaction.
2021-02-17T20:57:43Z kmsg (1584666) - 2021-02-17T20:57:42.5389266Z: WSL2: Performing memory compaction.
2021-02-17T20:59:44Z kmsg (1584667) - 2021-02-17T20:59:43.5405906Z: WSL2: Performing memory compaction.
2021-02-17T21:00:45Z kmsg (1584668) - 2021-02-17T21:00:44.5415836Z: WSL2: Performing memory compaction.
2021-02-17T21:01:46Z kmsg (1584669) - 2021-02-17T21:01:45.5425626Z: WSL2: Performing memory compaction.
2021-02-17T21:02:47Z kmsg (1584670) - 2021-02-17T21:02:46.5435146Z: WSL2: Performing memory compaction.
2021-02-17T21:03:48Z kmsg (1584671) - 2021-02-17T21:03:47.5447206Z: WSL2: Performing memory compaction.
2021-02-17T21:04:44Z kmsg (1584672) - 2021-02-17T21:04:44.0893216Z: FS-Cache: Duplicate cookie detected
2021-02-17T21:04:44Z kmsg (1584673) - 2021-02-17T21:04:44.0893246Z: FS-Cache: O-cookie c=000000001f39d944 [p=00000000e7327a8b fl=226 nc=0 na=1]
2021-02-17T21:04:44Z kmsg (1584674) - 2021-02-17T21:04:44.0893246Z: FS-Cache: O-cookie d=00000000ae03ae1d n=00000000207764e4
2021-02-17T21:04:44Z kmsg (1584675) - 2021-02-17T21:04:44.0893256Z: FS-Cache: O-key=[8] 'e1bb000000000c00'
2021-02-17T21:04:44Z kmsg (1584676) - 2021-02-17T21:04:44.0893536Z: FS-Cache: N-cookie c=000000009f501731 [p=00000000e7327a8b fl=2 nc=0 na=1]
2021-02-17T21:04:44Z kmsg (1584677) - 2021-02-17T21:04:44.0893546Z: FS-Cache: N-cookie d=00000000ae03ae1d n=000000003c99d411
2021-02-17T21:04:44Z kmsg (1584678) - 2021-02-17T21:04:44.0893546Z: FS-Cache: N-key=[8] 'e1bb000000000c00'
2021-02-17T21:04:49Z kmsg (1584679) - 2021-02-17T21:04:48.5456506Z: WSL2: Performing memory compaction.
2021-02-17T21:05:51Z kmsg (1584680) - 2021-02-17T21:05:50.6080256Z: WSL2: Performing memory compaction.
2021-02-17T21:06:52Z kmsg (1584681) - 2021-02-17T21:06:51.9171156Z: WSL2: Performing memory compaction.
2021-02-17T21:07:53Z kmsg (1584682) - 2021-02-17T21:07:52.9384396Z: WSL2: Performing memory compaction.
2021-02-17T21:08:54Z kmsg (1584683) - 2021-02-17T21:08:53.9585746Z: WSL2: Performing memory compaction.
2021-02-17T21:09:55Z kmsg (1584684) - 2021-02-17T21:09:54.9628366Z: WSL2: Performing memory compaction.
2021-02-17T21:10:56Z kmsg (1584685) - 2021-02-17T21:10:55.9656256Z: WSL2: Performing memory compaction.
2021-02-17T21:12:57Z kmsg (1584686) - 2021-02-17T21:12:56.9679046Z: WSL2: Performing memory compaction.
2021-02-17T21:13:58Z kmsg (1584687) - 2021-02-17T21:13:57.9703846Z: WSL2: Performing memory compaction.



**and wsl2 memory compaction keep calling... cause docker desktop.exe using 99% memory..**

**Comment by MichalLytek** [comment]
@stephen-turner It happens for me when I run postgres and localstack, so it doesn't look like the image issue.
Here is my today's diagnosis id: `F80A00F3-84C6-46DE-AACC-ACDCDBB64241/20210223172959`

**Comment by ragepaw-git** [comment]
Same issue. I just had a complete desktop crash. Docker Desktop was using 92GB of ram and took down my system.

**Comment by koopa** [comment]
Woah, same just happened here. Some random program crashed in the middle of doing some work and one monitor went black. So i launched process list to see if there is anything suspicious going on and saw docker desktop using over 35GB of RAM. Didn't manage to kill it and couldn't run diagnostics. Everything froze soon after and i had to reboot.

**Comment by jord1e** [comment]
Hello, yesterday my computer froze with 100% CPU usage and 99% memory usage because of Vmmem, this issue seems to be linked.

Currently I am using docker-desktop again and now my memory usage is again very high whilst i have nothing running besides the Kubernetes integration (my computer hasn't even been on for one hour). I dit test a deployment today, more details below.

This was yesterday (after closing my IDE (WebStorm) and Firefox!). Please note that the _CPU-usage was also at 100%_, all containers had been stopped (except for the standard Kubernetes ones) and I needed to force close the docker process:
![afbeelding](https://user-images.githubusercontent.com/30464310/113000843-7fb70e80-9170-11eb-80d6-6b85faa5f3a1.png)
And this is today, after one hour:
![afbeelding](https://user-images.githubusercontent.com/30464310/113000904-8f365780-9170-11eb-832d-92bfb0629138.png)

The issue seems to be related to #8521 because i am testing a Kubernetes deployment which starts [`node:14-alpine`](https://hub.docker.com/_/node) containers.

Diagnostics aren't working for some reason.

I am running docker-desktop version `3.2.2` (build no. `61853`) which consists of docker engine `v20.10.5` with Kubernetes enabled (`v1.19.7`) and i am using the the WSL2 backend. Windows version `20H2 17-7-2020`, build `19042.867`.

Maybe @MichalLytek, @ragepaw-git and/or @koopa can also confirm that they where running Alpine containers (directly or indirectly via Kubernetes)?

These are my containers (deployed by Kubernetes by default + the Kubernetes dashboard), nothing out of the ordinary so the memory should be reclaimed (right?):
![afbeelding](https://user-images.githubusercontent.com/30464310/113002590-3bc50900-9172-11eb-8ccd-2ef7d052c22c.png)

Please note that at startup my memory usage is 4000 MB, this includes Debian WSL (which consumes 400MB).
![afbeelding](https://user-images.githubusercontent.com/30464310/113003762-53e95800-9173-11eb-9ed6-b3e99bd94834.png)

When i stop docker-desktop some of the memory stays:
![afbeelding](https://user-images.githubusercontent.com/30464310/113003279-da516a00-9172-11eb-8d99-1fcec89fc5c7.png)
And when i run `wsl --shutdown` everything is freed

**Comment by ragepaw-git** [comment]
No Kubernetes for me.

I have one docker container right now, and it is built on Alpine.

**Comment by LBognanni** [comment]
The same happened to me, I had no containers running! Docker Desktop.exe used 48Gb of ram before killing my workstation. From what I experienced, having the docker desktop window open on a stopped minio container was enough for it to balloon in mem usage. Maybe a problem with electron?

**Comment by danspark** [comment]
Had the same problem, couldn't produce an diagnostic afterwards.

![image](https://user-images.githubusercontent.com/23037278/113231577-ef60f280-9271-11eb-8c23-4f10a0295eb7.png)

![image](https://user-images.githubusercontent.com/23037278/113231595-f7b92d80-9271-11eb-9f8d-12f36673a454.png)

**Comment by pmalecka** [comment]
Same here, docker-desktop.exe, v3.2.2 (61853) consumes all memory (physical and virtual) until all processes running on the system crash with out-of-memory errors. This is bad.

**Comment by matthewhillier** [comment]
Just had this happen to me for the second time. v3.2.2 (61853). Luckily I noticed apps getting unnecessarily sluggish, so managed to catch the runaway memory before everything became unresponsive, but I had to exit Docker Desktop from the Whale icon in order to shut it down.

Specifically with today's event, I had a container running overnight and it looked like my machine had tried to wake-up from sleep. If memory serves, I think the last time this happened it was also after Windows waking up, so there's perhaps some argument going on with Windows' natural sleep routine.

**Comment by ragepaw-git** [comment]
I doubt it's related to waking from sleep because my system never sleeps
and it's happened multiple times to me.

**Comment by mylemans** [comment]
Would like to chime in: just had docker desktop used 7GB RAM. I did switch Windows users and I 'think' I tried to accidently run the docker exe again there (but it didn't appear), maybe that is a hint on what causes it?

**Comment by madsjakob** [comment]
I ran a lot of docker build commands and my system suddenly stopped working all of my 64 GB RAM was used up. I restarted docker and memory usage  went down to around 20 GB.

Seems like docker consumes 500 MB - 1GB everytime I build an image and does not free up any memory afterwards.

**Comment by robross0606** [comment]
I was fine on 3.2.2 but just upgraded to 3.3.1 on two completely different systems and am now seeing this on both.  They will start fine and be fine for a while.  Then you go back and check and, at some point `DockerDesktop.exe` (*NOT* `vmmem`) is using 20-30GB of RAM.  This is taking down entire systems.

**Comment by sparxooo** [comment]
Can confirm happened to me also - Docker Engine version v20.10.5, Docker Desktop v3.2.2

Was watching Youtube in Chrome and using Discord, no containers running. Suddenly video froze, and Docker Desktop is increasing by 1gb per 5-10 seconds until we got to 95% memory usage (16gb system ram). Had to terminate via task manager.

**Comment by bitobrian** [comment]
I have consistently seen this same issue after an undetermined amount of time. I have wslconfig memory set and no excessive memory usage with running containers. I just usually notice some sluggishness then realize I need to kill Docker Desktop.exe as it is hogging 90+% memory.

Diagnostics ID: 906778E3-91E4-4C9B-93D3-6D6DB11F75A3/20210510022515
At this point, I had already wsl -t every running instance to try and nail down the culprit. The last containers running were:
- Postgres: bitnami/postgresql:11-debian-10
- PgAdmin: dpage/pgadmin4
- Valheim server: lloesche/valheim-server

All containers were running under 500mb of memory and no significant processing going on. Majority of my development with docker comes from the VS 2019 integration. Otherwise, I typically use compose to keep most of my containers running.

**Comment by berviantoleo** [comment]
> I ran a lot of docker build commands and my system suddenly stopped working all of my 64 GB RAM was used up. I restarted docker and memory usage  went down to around 20 GB.
> 
> Seems like docker consumes 500 MB - 1GB everytime I build an image and does not free up any memory afterwards.
> 
> Edit:
> Using docker desktop 3.2.2 with engine 20.10.5

I also meet this issues. I using docker dekstop 3.3.3, engine 20.10.6.

**Comment by i-kk** [comment]
I experienced the same issue with Docker for Windows + WSL2.
'Fixed' it by limiting amount of RAM used:
Create file .wslconfig inside: C:\Users\<Your Username> with:
`[wsl2]
memory=4GB # Limits VM memory in WSL 2 to 4 GB
processors=2 # Makes the WSL 2 VM use two virtual processors`

**Comment by danspark** [comment]
> I experienced the same issue with Docker for Windows + WSL2.
> 'Fixed' it by limiting amount of RAM used:
> Create file .wslconfig inside: C:\Users<Your Username> with:
> 
> ```
> [wsl2]
> memory=4GB # Limits VM memory in WSL 2 to 4 GB
> processors=2 # Makes the WSL 2 VM use two virtual processors
> ```

I think that's another problem. The leak is with the actual Docker desktop app, not WSL as I also limit the used RAM but also get the leak from time to time

**Comment by jord1e** [comment]
> 
> 
> I experienced the same issue with Docker for Windows + WSL2.
> 'Fixed' it by limiting amount of RAM used:
> Create file .wslconfig inside: C:\Users<Your Username> with:
> 
> ```
> [wsl2]
> memory=4GB # Limits VM memory in WSL 2 to 4 GB
> processors=2 # Makes the WSL 2 VM use two virtual processors
> ```

Thank you for this, at least my computer won't freeze anymore.

This doesn't resolve the leak though. When you shut down Docker Desktop more then of 2 GB Vmmem is not released (and the Vmmem keeps increasing the longer Docker Desktop is running):
![afbeelding](https://user-images.githubusercontent.com/30464310/122785390-a1c5b600-d2b3-11eb-9e24-b4d7fc99a235.png)


> Thanks for the report. I've never seen that before. Is it repeatable or was it a one-off?

@stephen-turner it has been 5 months and this issue now has 19 participants. Can this be looked into again?

**Comment by stephen-turner** [comment]
We can look at it if and only if someone has a reliable repro case.

**Comment by sparxooo** [comment]
To add extra info - the machine I had the issue on is a 

Ryzen 5 3600
16GB 3200mhz ram
Lots of hard disks...
Geforce RTX 2060

Machine is used for Dev/general use/gaming, and is hibernated/put into standby rather than shut down.

If I do get this issue again, is there anything you need me to do to gather more info?

**Comment by stephen-turner** [comment]
Steps to reproduce is what we're lacking.

**Comment by ragepaw-git** [comment]
In my case, steps to reproduce are,

use Docker Desktop for Windows (number of containers irrelevant)
wait until PC runs out of memory (in my case 3 weeks to a month)

**Comment by robross0606** [comment]
> 19 participants in five months means that it's obviously very rare

I wonder how many participants are having this problem and don't notice it.  I've seen it on TWO computers in my one location -- the only two that use Docker Desktop.  They are different systems with different configurations.  The only real commonality is updated Windows 10 and Docker Desktop.  Wish I could tell you what causes it, but you only notice it when you happen to notice it.

**Comment by ragepaw-git** [comment]
In my case, I know that because of the amount of memory I have, it takes
weeks to exhibit the issue. Rebooting sets the clock back to zero, and I
have been rebooting a lot lately (for unrelated reasons).

**Comment by Chealer** [comment]
> I ran a lot of docker build commands and my system suddenly stopped working all of my 64 GB RAM was used up. I restarted docker and memory usage went down to around 20 GB.
> 
> Seems like docker consumes 500 MB - 1GB everytime I build an image and does not free up any memory afterwards.
> 
> Edit:
> Using docker desktop 3.2.2 with engine 20.10.5

I only just noticed I was possibly experiencing this, so can only confirm seeing once, but rebuilding an application brought my Windows 10 with its 16 GB to a crawl after Vmmem's RAM usage jumped from its usual ~5 GB to > 11 GB, with Docker Desktop 3.5.1.

**Comment by Chealer** [comment]
I just experienced the same leak once again, memory usage reaching 99% and causing me to struggle in calls, until I shut down Docker. After restarting, I'm back to a reasonable 62%.

This happened at the very next rebuild of the same application, so I would expect this to be easily reproducible. By the way, I have no clue why Docker rebuilt all the services from scratch. I am still on 3.5.1. This is not frequent but it's not the first time it happens.

**Comment by tomocrafter** [comment]
This happened to me, when I afked for about 2 hours while running few containers with docker compose and opening CLI from Docker Desktop for Win.

**Comment by EatonEmmerich** [comment]
I was running multiple docker containers but the ram resources doesn't seem to be freed for any of them.
After stopping all containers, and wsl2 idling:

![image](https://user-images.githubusercontent.com/4838128/133480222-97a39cf1-f5c0-4909-9ea5-1af24fd00537.png)
Diagnosis ID: C2BE2537-BB64-4613-AC94-623DF368DF14/20210915172104

**Comment by tobias-af** [comment]
All Containers stopped while Vmmem reserves most RAM-Memory:
![image](https://user-images.githubusercontent.com/64785823/134555490-76273d5c-ee89-4f1d-a19c-b1232a10a59a.png)

**Comment by nucktwillieren** [comment]
I found this problem when I used Docker Destop Version 3.3.
Now, it's 4.0.1, and this problem still happens to me.

I think the situation when docker causes high usage of Vmmem is running the "docker build" command.
Besides, building the larger packages cause higher memory leak. (Ex: building node_modules packages.)
(I made a video trying to reproduce this. Youtube: https://www.youtube.com/watch?v=hNUUTzvEkCk )
p.s. In this video, the command "make build-and-tag" is the same as
```
docker build -t ${NAME}:${VERSION}  . 
docker tag ${NAME}:${VERSION} ${NAME}:latest
```

For now, if I encounter this problem, I will type the following command in PowerShell(admin) to restart the WSL service. 
```
Restart-Service LxssManager
```
After that, the WSL will restart, the Docker engine will be shutdown and the memory will be free.

------

OS: Windows 10
Docker Backend: Windows WSL 2
Docker Desktop: Version 4.0.1
Docker Engine: v20.10.8

**Comment by tomocrafter** [comment]
@nucktwillieren No, this is not docker desktop for windows problem. this is https://github.com/microsoft/WSL/issues/4166 . which is problem that never returns heap allocated memory on wsl2 for win

**Comment by nucktwillieren** [comment]
@tomocrafter 
Thank you for your reply and your time.
And, sorry for that I misunderstood the purpose of this issue. 
I saw some replies were about the problem of Vmmem, so I thought I could provide further information about Vmmem.

**Comment by tomocrafter** [comment]
@nucktwillieren Oh, I replied to you because I got notification of your reply so didn't notice that so many people are misunderstanding this issue.
I also hope https://github.com/microsoft/WSL/issues/4166 will be fixed asap

**Comment by FrontMobe** [comment]
> I have consistently seen this same issue after an undetermined amount of time. I have wslconfig memory set and no excessive memory usage with running containers. I just usually notice some sluggishness then realize I need to kill Docker Desktop.exe as it is hogging 90+% memory.
> 
> Diagnostics ID: 906778E3-91E4-4C9B-93D3-6D6DB11F75A3/20210510022515 At this point, I had already wsl -t every running instance to try and nail down the culprit. The last containers running were:
> 
> * Postgres: bitnami/postgresql:11-debian-10
> * PgAdmin: dpage/pgadmin4
> * Valheim server: lloesche/valheim-server
> 
> All containers were running under 500mb of memory and no significant processing going on. Majority of my development with docker comes from the VS 2019 integration. Otherwise, I typically use compose to keep most of my containers running.

The problem is PGAdmin4!!!! It happens outside of docker as well. It only happens after you open the app.

**Comment by EatonEmmerich** [comment]
I dont have PGAdmin4 installed anywhere

**Comment by piv0** [comment]
I get the same issue on a M1 machine running the latest macOS Monterey, not sure this is just a WSL issue. The Docker app will eat up nearly all available memory over time.

**Comment by devminded** [comment]
In combination with WSL2 it is free **virtual memory** that goes to zero, even though there are 5GB of physical memory free. A hard reboot needed to resolve.
![win-mem](https://user-images.githubusercontent.com/10235454/157499592-7aa5e3a1-ae50-4ad6-9e63-18d661554601.png)
