### ISSUE TITLE
Unable to start Docker after 17.07 set of upgrades (same problem with RC3, RC4)

### ISSUE THREAD

**Issue by arvindshmicrosoft** [docker/for-win#1036]
### Expected behavior
Docker Edge on Windows 2016 should start normally

### Actual behavior
Docker Edge on Windows 2016 fails to start

### Information

Diagnostic ID 843F08C3-6717-4F1C-8BB2-00A69CABD94C/2017-08-24_13-02-23

[13:03:55.987][ApiProxy       ][Info   ] proxy >> GET /_ping
[13:03:55.988][ApiProxy       ][Info   ] Dial Hyper-V socket a6d71e0e-a0ac-4a7a-8761-0030c3af728c:23a432c2-537a-4291-bcb5-d62504644739
[13:03:55.988][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket a6d71e0e-a0ac-4a7a-8761-0030c3af728c:23a432c2-537a-4291-bcb5-d62504644739
[13:03:55.990][ApiProxy       ][Info   ] error reading response from Docker:  HvSocket has already been closed
[13:03:55.993][ApiProxy       ][Info   ] proxy >> GET /v1.31/containers/json
[13:03:55.993][ApiProxy       ][Info   ] Dial Hyper-V socket a6d71e0e-a0ac-4a7a-8761-0030c3af728c:23a432c2-537a-4291-bcb5-d62504644739
[13:03:55.993][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket a6d71e0e-a0ac-4a7a-8761-0030c3af728c:23a432c2-537a-4291-bcb5-d62504644739
[13:03:55.994][ApiProxy       ][Info   ] error reading response from Docker:  HvSocket has already been closed
[13:03:56.001][DockerDaemonChecker][Error  ] Docker daemon is not running

### Steps to reproduce the behavior
These problems all started after the 17.07 RC3 upgrade was offered and I accepted to upgrade.

**Comment by arvindshmicrosoft** [comment]
I seem to have found a workaround, which is to run the Docker for Windows front-end / system tray app as an Administrator. In that case Docker is able to start. But this should not be a requirement.

**Comment by hinell** [comment]
Just refer here #1025

**Comment by ebriney** [comment]
We just release a new version (17.09.0-ce-rc2-win29) that should fix the issue.
Can you test it and close the issue if it works?

**Comment by hinell** [comment]
@ebriney Can confirm that latest ``17.09.0-ce-rc3`` solved my problem in #1025.

**Comment by dbonnell** [comment]
I have version 17.09.0-ce-win32 (13529) and this issue is still present, even when starting Docker for Windows as Administrator.  I just tried a fresh install of Docker after uninstalling both Docker and Hyper-V, and re-installing both - same issue.  This is BEFORE switching Docker to Windows containers.

**Comment by dbonnell** [comment]
I just downgraded to the previous release and all is well again.  (I had to completely remove C:\ProgramData\Docker first though as it was throwing some networking error after switching to Windows containers, diagnostic 999F89B2-9438-42DB-93BE-1F94353964F5/2017-10-04_16-04-33).  I saved the volumes, images and windowsfilter directories and restored them after everything was working.  I didn't restore my containers, may have been able to but I have scripts to re-create them and all data is off-container so nothing material lost.  Hope that helps someone else get out of this pickle while the problem with the current version is fixed.

P.S. I found the downgrade hint in another similar error report.
