### ISSUE TITLE
Docker client ignores HTTP_PROXY envar and build args

### ISSUE THREAD

**Issue by chrsoo** [docker/for-win#1057]
### Expected behavior
The docker client **respects the proxy settings** and downloads parent images from docker.io.

### Actual behavior
The docker client **ignores the proxy settings** and fails with a timeout

### Information

  - Diagnostic ID is `9C89F33A-AA87-4CBF-B00C-1A004A366034/2017-09-04_13-00-29`
  - Docker is running on a client workstation with CNTLM proxying the corporate proxy to avoid authentication issues
  - The CNTLM  proxy configured by envar is bypassed by the docker client - no requests are logged by CNTLM using `docker` but requests are logged using `curl`
  - Providing the `HTTP_PROXY` and `HTTPS_PROXY` as envars or as `--build-arg` parameters makes no difference
  - Specifying the envars globally for the logged in user does not make a difference
  - Using the native Windows command console or gitbash does not make a difference
  - The Docker deamon is running and docker client calls are logged without errors
  - Docker version is `17.06.1-ce, build 874a737`
  - Windows 10 Enterprise, version is `1607 (OS Build 14393.1593)`

### Steps to reproduce the behavior
````
# On Windows 10 Enterprise with CNTLM installed export the proxy settings
$ export HTTP_PROXY=http://127.0.0.1:3128
$ export HTTPS_PROXY=http://127.0.0.1:3128
$ export http_proxy=http://127.0.0.1:3128
$ export https_proxy=http://127.0.0.1:3128

# Change to any directory containing a Dockerfile and build it
$ docker build .
Sending build context to Docker daemon  56.83kB
Step 1/2 : FROM frolvlad/alpine-oraclejdk8:slim
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

#  Note that the same request works for curl with the proxy set as environment variables
$ curl https://registry-1.docker.io/v2/ -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87    0    87    0     0      0      0 --:--:--  1:11:35 --:--:--   113
````

**Comment by chrsoo** [comment]
After a long investigation the following has become clear

* The docker client does not support the HTTP_PROXY and HTTPS_PROXY as indicated by the Docker docmentation
* The docker client uses the proxy configuration of the Docker demon
* **When configuring a proxy running on localhost (127.0.01) in the Docker demon the IP address is substituted with the IP of the Windows Hyper-V Docker VM in the Docker client** (c.f. the command `docker info`)
* Using the default localhost configuration of CNTLM fails as the Docker VM cannot access localhost on the host machine; instead it tries localhost in the client VM

In order to make CNTLM work with Docker it must run on an IP that can be reached by the Docker client VM.

There are several solutions

1. Run CNTLM on the host IP
1. Run CNTLM on a second IP address configured on the host
1. Run CNTLM in a Docker container and thus accessible on Docker's virtual network

The first and second option means exposing CNTLM on the LAN making it possible for any machine on the network to access internet borrowing the Windows user's identity and likely violating any security policy in place (it could be that port 3128 is blocked by the Windows firewall thus making this point moot).

This said 1 or 2 may be necessary to bootstrap option 3.

I have successfully downloaded, installed and configured [btrepp/cntlm](https://hub.docker.com/r/btrepp/cntlm/) as the proxy for the Docker demon and this now makes the docker client work.

Although this resolves my problem of using Docker behind a NTLM corporate proxy the HTTP_PROXY and HTTPS_PROXY variables still do not work as advertised in the Docker documentation. Before closing I would expect either making the environment variables work or at a minimum to update the [Docker command line documentation](https://docs.docker.com/engine/reference/commandline/cli/) with additional information for Docker on Windows.

**Comment by chrsoo** [comment]
Update: for some reason `docker build` works with this solution but I still can't get `docker pull` to work. 

This seems very strange to me but it looks like that there is some major difference in how binaries are retrieved from the Docker Hub using the two commands...

**Comment by chrsoo** [comment]
Update 2: seems I was too quick regarding option 3) above. Using cntlm in a container and configuring the Docker IP for the Proxy does not work either for build or pull. Sorry for the confusion. I have only managed to run docker with CNTLM bound to a the host IP or to a secondary IP as per 1) and 2).

**Comment by cancin** [comment]
Any news on this topic? We experience the same problems...

**Comment by cancin** [comment]
My original problem description from the forums:

> I am new to Docker and just startet my first steps with Docker for Windows on Windows 10. I installed the newest version of Docker and updated Windows10.

> I am running my system in a corporate environment behind a common security layer. For outbound connections we have to use an ntlm proxy. To do so I installed cntlm on my local machine and configured the ntlm client and Docker (defining the proxy properties in the UI) appropriately. If I configure Docker to use “Windows containers” everything works like a charm. If I switch to “Linux Containers” the call seems to disapear.

> A simple docker run hello-world quits with following error message: “Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: getsockopt: connection refused.”

> Obviously the Linux Container mode seems to do things differently from the Windows mode. The call in Linux mode doesnt even reach the local ntlm client. Wireshark doesnt show any network traffic. What is the difference between the two modes.


Problem solved in my context!
Running cntlm in gateway mode AND using the correct IP (i.e. the "external IP" of the Windows network adapter). 
Obviously in Linux mode the additional virtualization layer needs the docker proxy to be defined differently.

**Comment by lmcarreiro** [comment]
Same problem here. Even when I put the user and password in the proxy url `http://<user>:<password>@<proxy-host-at-company-domain>:<port>` I still get the following message:
`Error response from daemon: Get https://registry-1.docker.io/v2/: Proxy Authentication Required`

With CNTLM on localhost, I get this message:
`Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 10.0.75.1:3128: getsockopt: connection refused`

**Comment by lmcarreiro** [comment]
I just got it working, tested with `docker login` and `docker pull`, both worked fine. I didn't have to use CNTLM in gateway mode, so I think my local proxy aren't exposed to anyone in my company's intranet.

When we install Docker on windows, it creates a virtual ethernet adapter, I just had to configure the CNTLM to listen using the IP address of this network adapter, in this example, it's the IP `10.0.75.1`, my IP address in my company's network is the `10.22.204.126`:

```diff
C:\Users\leonardo>ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
+   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : mycompany.biz
   Link-local IPv6 Address . . . . . : fe80::85e2:37a7:e4f8:1ba4%6
-   IPv4 Address. . . . . . . . . . . : 10.22.204.126
   Subnet Mask . . . . . . . . . . . : 255.255.254.0
   Default Gateway . . . . . . . . . : 10.22.205.254
```

I just changed the `Listen` config in `cntlm.ini` that had just the port number to listen to `10.0.75.1:3128` instead of `3128`. This is my `cntlm.ini` content:

```
Username	leonardo
Domain		mycompany
Auth            NTLMv2
PassNTLMv2      1AD35398BE6565DDB5C4EF70C0593492
Proxy		proxy.mycompany.com.br:8080
NoProxy		*.mycompany.com.br, *.mycompany.biz, localhost, 127.0.0.*, 192.168.*, 10.*
Listen		10.0.75.1:3128
```

And in docker settings, the proxy config points to `http://10.0.75.1:3128`



![image](https://user-images.githubusercontent.com/13019179/40844370-1caf6d88-658a-11e8-9043-f495814c7496.png)
