### ISSUE TITLE
Cannot install Docker Desktop 3.5.0 on windows 10 20H2

### ISSUE THREAD

**Issue by yanxiaodi** [docker/for-win#11514]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
The latest Docker Desktop v3.5.0(66024) cannot be installed on Win10 20H2. It shows the below error:
![image](https://user-images.githubusercontent.com/3395915/123199359-d4192280-d502-11eb-92bc-83f46913e850.png)

### Expected behavior
Docker Desktop should be correctly installed on Win10 20H2.

### Information

  - Windows Version: Win10 20H2
  - Docker Desktop Version: 3.5.0 (66024)
  - WSL2 or Hyper-V backend?  N/A
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior

  1. Download the latest Docker Desktop from https://www.docker.com/products/docker-desktop
  2. Run the installation program and it shows the error.

I have uninstalled the previous version which was not stable recently. So would like to reinstall it. Also have deleted the related folders in `C:\ProgramData` and `C:\Program Files`.

**Comment by JochemE** [comment]
I have the same issue and a workaround is to install 3.4.0 for now.
My error message showed that it was trying to download to an invalid temp folder.
`c:\users\jochemvandenende\AppData\Local\Temp\...` where my actual temp folder is
`c:\users\jochem.van.den.ende\AppData\Local\Temp\...` (note the `.`'s in the username).

**Comment by StefanScherer** [comment]
Thanks for the report and thanks @JochemE for the detail. I can reproduce the problem. We're looking into it to fix it.

**Comment by StefanScherer** [comment]
@yanxiaodi @JochemE Here is an internal build of Docker Desktop which contains the fix for your problem. 
https://desktop-stage.docker.com/win/stable/amd64/66053/Docker%20Desktop%20Installer.exe
Please let me know if it works for you.

**Comment by vladimir-shopov** [comment]
I have just tried this internal installer build and it seems to be solving the issue with **.**(dot) in the Windows user folder.

**Comment by MikeWilliams-UK** [comment]
Same happens for me, I have a dot in my username.

**Comment by stephrobert** [comment]
same issue

**Comment by StefanScherer** [comment]
We're preparing a patch release which should be available later today. We apologize for the inconvenience. :-)
If you have time then I suggest to wait for that patch release. The internal build I shared above has a different version number (3.6.0) and you have to manually uninstall it to be able to install an official version 3.5.x.

**Comment by wkjfh** [comment]
I managed to get past the problem in the. user, but now the following error appears:

`Component CommunityInstaller.EnableFeaturesAction failed: Not found 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()`

**Comment by nsilvaWilson** [comment]
@StefanScherer your internal build installer seems to work fine for me. Thanks for the quick turnaround!

**Comment by JochemE** [comment]
> @yanxiaodi @JochemE Here is an internal build of Docker Desktop which contains the fix for your problem.
https://desktop-stage.docker.com/win/stable/amd64/66053/Docker%20Desktop%20Installer.exe
Please let me know if it works for you.

@StefanScherer i had 3.4.0 installed as a fallback and i could successfully install the internal build on top of it 👍

**Comment by stephen-turner** [comment]
Everyone who's watching this: the patch release will now be tomorrow. Apologies for the delay.

**Comment by riveromj** [comment]
> @yanxiaodi @JochemE Here is an internal build of Docker Desktop which contains the fix for your problem.
> https://desktop-stage.docker.com/win/stable/amd64/66053/Docker%20Desktop%20Installer.exe
> Please let me know if it works for you.


this solves the problem. 
Thanks @StefanScherer

**Comment by lorenrh** [comment]
We have just released 3.5.1 containing a fix for this issue.
Sorry for the delay.

**Comment by yanxiaodi** [comment]
Thanks @lorenrh @riveromj @stephen-turner @StefanScherer for your effort.❤

**Comment by AngieJ25** [comment]
I have tried installing that fix but it still doesn't work for me.  Here is the error message:
![image](https://user-images.githubusercontent.com/16796801/124266604-19ef6f80-db2f-11eb-99d8-1511ca2d06f6.png)

**Comment by MikeWilliams-UK** [comment]
Why are you reporting a bug for 3.6.0 in an issue for 3.5.0?

**Comment by AngieJ25** [comment]
My docker desktop does not load at all.  I have 3.5.0 installed but whenever I try and uninstall it it just hangs (pic attached).  And whenever I try and install any version over the top of it, the installation fails.  I'd like to uninstall and reinstall 3.5.0 if possible but I don't care if it's 3.5.0 or 3.6.0, I just need Docker to work on my machine again.
![image](https://user-images.githubusercontent.com/16796801/124449650-8fe81680-dd7b-11eb-991c-bb81492ae00d.png)
