### ISSUE TITLE
Docker Engine failed to start

### ISSUE THREAD

**Issue by soroshsabz** [docker/for-win#12066]
ITNOA

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9C071691-ABCF-4A7A-A88A-DC7795DA4671/20210902100300

### Actual behavior

Docker Engine does not start :(

### Expected behavior

After booting my computer, I expected to start Docker Engine correctly

### Information

  - Is it reproducible? Yes, after every reboot, or trying to start manually
  - Is the problem new? yes
  - Did the problem appear with an update? No (but this problem is occur when I install new [Windows Cumulative Update  2021/09](https://support.microsoft.com/en-us/topic/september-1-2021-kb5005101-os-builds-19041-1202-19042-1202-and-19043-1202-preview-82a50f27-a56f-4212-96ce-1554e8058dc1)
 
  - Windows Version: Windows 10 Version 21H1 (OS Build 19043.1202)
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  I use Windows Container (but WSL 2 based engine is enable in setting)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

My docker settings like below

```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": false,
  "data-root": "N:/Docker"
}
```

### Steps to reproduce the behavior

  1. Try to run Docker Desktop
  2. Docker Desktop try to start Docker Engine
  3. Docker Engine failed to start after couple of minutes
  4. I cannot do anything :(

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 210
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

![image](https://user-images.githubusercontent.com/17947618/131833668-b662acb2-eb59-4725-a0f7-060152059585.png)

**Comment by soroshsabz** [comment]
I see docker log file and find below log for error

`[15:39:07.216][GoBackendProcess  ][Error  ] msg="(8eb1ef14) b6d11a5e-BackendCMD C<-S NoResponse GET /settings (0s): Get \"http://ipc/settings\": open \\\\.\\pipe\\dockerBackendApiServer: The system cannot find the file specified.[[STACK]]"`

[log.txt](https://github.com/docker/for-win/files/7098417/log.txt)

**Comment by soroshsabz** [comment]
I try to change (switch) container to Linux container with WSL backend.

I see below error

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\ssoroosh\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The network was not found.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```
and see `[10:47:32.932][IPCServer         ][Error  ] (766ea316) 3e3ae1f7-CSharpAPI S->C axios/0.21.1 GET /settings (98ms): Internal Server Error` in below log file

[log.txt](https://github.com/docker/for-win/files/7103720/log.txt)

**Comment by Danissrt** [comment]
I had a similar problem as well as an error with hyper-v so in settings I activated the use of WSL2 instead of hyper-v.
![image](https://user-images.githubusercontent.com/90037739/131988678-6362fa30-5e79-4c4d-98da-b1187087cb18.png)

**Comment by soroshsabz** [comment]
My docker does not work with WSL too 😔

**Comment by KurtBildeSDU** [comment]
And I can confirm soroshsabz - I have the exact same experience :-/ - also on Docker 4.0 Win10 21H1

**Comment by neil90** [comment]
I am receiving the same error

**Comment by KurtBildeSDU** [comment]
Just to let you know, that it seems like the "settings" file is corrupt. If you delete the %appdata%\Docker\settings.json and restart docker, then it work again.

**Comment by soroshsabz** [comment]
@KurtBildeSDU I don't change settings.json before docker failure. so this settings.json is exactly same as before (when docker is work correctly)

**Comment by KurtBildeSDU** [comment]
Nor did I, but I did update docker to a newer version, and it seems like "update" misses some params from that file. Have you updatede to 4.01?!?

**Comment by soroshsabz** [comment]
Currently I remove `docker` directory and `Docker Desktop` directory in `%appdata%` and reinstall docker from latest setup file from docker hub, but after install I see below error

```
`System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\ssoroosh\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The network was not found.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
`
```

and my Diagnostic id is : 5BCDC324-A8CA-44F2-9CDA-DE2A62E609EB/20210917055010

**Comment by soroshsabz** [comment]
@KurtBildeSDU 

After I switch to windows container, I see below error:

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 210
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

```

and my Diagnostic id is : 5BCDC324-A8CA-44F2-9CDA-DE2A62E609EB/20210917060906

**Comment by soroshsabz** [comment]
Oh! wait a minutes, [winget](https://github.com/microsoft/winget-pkgs) docker package is outdate, I try to update to 4.0.1

**Comment by soroshsabz** [comment]
@KurtBildeSDU I update to new version 4.0.1 but does not work correctly

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 210
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

```

**Comment by soroshsabz** [comment]
@KurtBildeSDU for Linux container

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\ssoroosh\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The network was not found.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

```

Diagnostic ID: 5BCDC324-A8CA-44F2-9CDA-DE2A62E609EB/20210917071549

**Comment by soroshsabz** [comment]
@KurtBildeSDU  I have new scenario, I remove docker image (data-root), so specially in Windows container after two weeks, we can successfully start docker engine

but we cannot run docker engine with default (and original) `data-root` :(

**Comment by nikinsider** [comment]
> Just to let you know, that it seems like the "settings" file is corrupt. If you delete the %appdata%\Docker\settings.json and restart docker, then it work again.

This fixed the issue for me! Many thanks.

**Comment by Peredery** [comment]
problem still not resolved

**Comment by soroshsabz** [comment]
After I updated to 4.1.0, the problem still not resolved

#12229

**Comment by soroshsabz** [comment]
@mikeparker Did you can any help for resolving this problem? my docker is not working more than one month

**Comment by fmiqbal** [comment]
> @mikeparker Did you can any help for resolving this problem? my docker is not working more than one month

Have you tried downgrading ?

**Comment by soroshsabz** [comment]
@fmiqbal I have same problem in version 4.0.0 and 4.0.1 and 4.1.0

And see many issue with same problem in version 3.6.0 like #12133 

What is version that I can downgrade to it?

**Comment by soroshsabz** [comment]
@mat007 Did you need any more info to start resolving this issue?

**Comment by soroshsabz** [comment]
I have same problem in 4.1.1 too. :( ( related to #12270 )

**Comment by soroshsabz** [comment]
```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16599\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 212
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by soroshsabz** [comment]
I have another experiment that,

I can run successfully `.\dockerd.exe` and all docker functionality work good.

So our problem is, why `Docker Desktop` does not work

**Comment by soroshsabz** [comment]
@mikeparker What is the main difference between `dockerd.exe` and Docker Desktop?

**Comment by LBates2000** [comment]
Also having the same issue after upgrading to 4.1.1 (69879). Was originally able to get it running by switching to Windows containers but now I can no longer do that either.

**Comment by soroshsabz** [comment]
I uninstall and reinstall new version 4.2.0

And my problem is not resolve

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 212
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by soroshsabz** [comment]
version/4.2.0

**Comment by soroshsabz** [comment]
\version/4.2.0

**Comment by soroshsabz** [comment]
@stephen-turner Any Idea to resolve this long live bug? I could not find your source code to debug it.

**Comment by stephen-turner** [comment]
As no-one else is reporting this (or at most one or two others), it's presumably something in your local setup. Maybe some corporate security software is blocking it. You could see if the self-diagnose functionality reports anything.

**Comment by fmiqbal** [comment]
maybe docker logs from `C:\Users\USERNAME\AppData\Local\Docker` will shed some light ?

**Comment by soroshsabz** [comment]
> As no-one else is reporting this (or at most one or two others), it's presumably something in your local setup. Maybe some corporate security software is blocking it. You could see if the self-diagnose functionality reports anything.

@stephen-turner I attach all diagnostics info in this issue, and as I can see in issues list of this project, many people have this problem.

**Comment by UniquePants** [comment]
Same problem for me after installing the latest windows update today.
Updated docker desktop from 4.1.1 to 4.2 to see if this resolves the issue, but it does not. 

Deleting AppData/Local/Docker and AppData/Roaming/Docker folders as suggested many times by others does not change anything.

From Microsoft.NET Framework:
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Docker.Core.Features.Features.<IsEnabled>d__16.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\Features\Features.cs:Zeile 91.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.App.<Initialize>d__28.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:Zeile 117.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Core.TaskExtension.<Forget>d__0.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\Extensions.cs:Zeile 30.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

From AppData/Local/Docker/log.txt:
(only the first part because of maximum character limit)
````
Version: 4.2.0 (70708)
Sha1: eb84a759291f14fe31a97526cb8b137e6e541763
Started on: 2021/11/15 15:19:10.058
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home
Edition: Core
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\Chocs\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:19:10.122][GUI               ][Info   ] Starting...
[15:19:10.283][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[15:19:10.316][GoBackendProcess  ][Info   ] Started
[15:19:10.320][DevEnvBackendProcess][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.dev-envs.exe 
[15:19:10.322][DevEnvBackendProcess][Info   ] Started
[15:19:10.356][IPCClient         ][Info   ] (026378d3) 141c36f3-GoBackendClient-CSharp C->S BackendAPI GET /settings
[15:19:10.363][IPCClient         ][Info   ] (64ad3c05) 141c36f3-GoBackendClient-CSharp C->S BackendAPI GET /ping
[15:19:10.370][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[15:19:10.371][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[15:19:10.372][SettingsLoader    ][Warning] Failed to fetch settings from backend, retrying in 1 sec
````

**Comment by mat007** [comment]
@UniquePants your error looks very different from the others, can you open a separate issue?

**Comment by UniquePants** [comment]
> 
> 
> @UniquePants your error looks very different from the others, can you open a separate issue?

actually it was solved after upgrading from windows build 20h2 to windows 21H1, therefore I deleted my comment and did not create new issue :)

**Comment by AdamTateDesign** [comment]
I just had this isssue. I had created a .wslconfig file and reduced the RAM usage which was causing a failure due to running out of memory. Deleting the file and re-installing WSL fixed the issue.

**Comment by soroshsabz** [comment]
> > @UniquePants your error looks very different from the others, can you open a separate issue?
> 
> actually it was solved after upgrading from windows build 20h2 to windows 21H1, therefore I deleted my comment and did not create new issue :)

I Upgraded my Windows 10 to 21H2, but my problem is not resolved.



> I just had this isssue. I had created a .wslconfig file and reduced the RAM usage which was causing a failure due to running out of memory. Deleting the file and re-installing WSL fixed the issue.

@AdamTateDesign Please add your .wslconfig

thanks

**Comment by soroshsabz** [comment]
ITNOA

I upgraded to version 4.3.2 but my problem is not resolved

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 212
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

@stephen-turner  How to change timeout value for `System.ServiceProcess.ServiceController.WaitForStatus`?

**Comment by KurtBildeSDU** [comment]
My suggestion is that you pay for the pro subscription - then you will be able to get support from Docker!!!!

Happy New year!

-Kurt

Den 31. dec. 2021 kl. 11.51 skrev soroshsabz ***@***.***>:

﻿

ITNOA

I upgraded to version 4.3.2 but my problem is not resolved

System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 212
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()


@stephen-turner<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstephen-turner&data=04%7C01%7Ckub%40sdu.dk%7C7e96d30a38674ef8673408d9cc4b7b3a%7C9a97c27db83e4694b35354bdbf18ab5b%7C0%7C0%7C637765446834459231%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vN5Rj47%2B%2FzefPyQm2Xx%2BIV2b%2BdF6OiOBPAEnGEJ2Eeg%3D&reserved=0> How to change timeout value for System.ServiceProcess.ServiceController.WaitForStatus?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdocker%2Ffor-win%2Fissues%2F12066%23issuecomment-1003342840&data=04%7C01%7Ckub%40sdu.dk%7C7e96d30a38674ef8673408d9cc4b7b3a%7C9a97c27db83e4694b35354bdbf18ab5b%7C0%7C0%7C637765446834615473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nw%2FMTlU5rH5xfSTBGzBP2owe%2FU0E%2FGU6t5Gj%2BJe%2B6Xk%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL3YLVO7AXSOOQY7MGBHSD3UTWDKPANCNFSM5DIX6FJA&data=04%7C01%7Ckub%40sdu.dk%7C7e96d30a38674ef8673408d9cc4b7b3a%7C9a97c27db83e4694b35354bdbf18ab5b%7C0%7C0%7C637765446834615473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IMe7MPwOVxB42Git%2FrYtui1K4jNoaGxcI1XEwAq4vqk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckub%40sdu.dk%7C7e96d30a38674ef8673408d9cc4b7b3a%7C9a97c27db83e4694b35354bdbf18ab5b%7C0%7C0%7C637765446834615473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AA6mEVEgrVLkdaanO1atJfY2oA1qSkgj%2BhIis1VQEoI%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckub%40sdu.dk%7C7e96d30a38674ef8673408d9cc4b7b3a%7C9a97c27db83e4694b35354bdbf18ab5b%7C0%7C0%7C637765446834615473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EjIaLwb%2FedNeohiviQKTT0i03UiCRrMBdM3K9ebX3jk%3D&reserved=0>.

**Comment by soroshsabz** [comment]
version/4.3.2

**Comment by soroshsabz** [comment]
related to #6159

**Comment by KurtBildeSDU** [comment]
Both closed… get hold of Docker via the payed support as the solutions provided by the community doesn’t seems to work on your setup!

**Comment by soroshsabz** [comment]
After many month, I found my problem

As you can see in #11899 , My problem is one bug from Docker Desktop, that panic.txt is `readonly` after I change this from [forums docker guideline](https://forums.docker.com/t/error-message-when-trying-to-switch-to-windows-container/113809/10?u=soroshsabz)

My problem is resolved (very very thanks to [Tomas Slaman](https://forums.docker.com/u/tomasslaman/summary))
