### ISSUE TITLE
4.7.0 fails to start after upgrade from 4.6.1 - Windows Container mode

### ISSUE THREAD

**Issue by CJCombrink** [docker/for-win#12652]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
         - experimental features were never enabled
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9AB086F4-9AD3-4702-9D85-3B33BE648346/20220408090558

### Actual behavior
Docker Desktop fails to start after upgrade from 4.6.1 to 4.7.0.
It looks like it upgraded without issue.
Starting throws an Error: "System.Exception: Paths contain symlinks"

### Expected behavior
Docker starts without issue 

### Information

  - Windows Version: Windows 10 Pro 20H2
  - Docker Desktop Version: 4.7.0
  - WSL2 or Hyper-V backend?  Windows Containers
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No - Physical Machine

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Will attach

### Steps to reproduce the behavior

Estimated (did not try to reproduce):
1. Install Docker Desktop 4.6.1
2. Change to Windows Containers
3. Open TCP port
4. Upgrade to 4.7.0

**Comment by CJCombrink** [comment]
With the error shown I could "Switch to Linux Containers..." from the taskbar icon.
This enabled Docker Desktop to start again.

Switching back to "Windows Containers" throws the same exception again.

**Comment by CJCombrink** [comment]
The exception is:
```
System.Exception:
Paths contain symlinks
   at Docker.Core.PermissionUtils.CheckPath(String path, Boolean allowDockerAppData) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 250
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 46
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 70
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 70
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 70
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 70
   at Docker.Backend.HttpAPI.WindowsContainersController.FixPermissions(String path) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 72
   at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\PR-17669\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 35
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

```

**Comment by ebriney** [comment]
@CJCombrink Can you run this command in an admin cmd.exe please:
`dir /AL /S C:\ProgramData\Docker`

**Comment by CJCombrink** [comment]
@ebriney 
Running the given command looks like it goes into an infinite loop, printing many many files and does not seem to stop

**Comment by ebriney** [comment]
Ok, thanks, it will be enough to do a fix, not sure why I didn't see it with my tests on windows containers.
What image do you use?
I'll send you ASAP a build with a fix (hopefully today).
Are you stuck?
If you can lose your layers just uninstall this version and reinstall previous version: https://desktop.docker.com/win/main/amd64/76265/Docker%20Desktop%20Installer.exe

**Comment by CJCombrink** [comment]
@ebriney 
I base my images off `mcr.microsoft.com/dotnet/framework/sdk:latest`
No I am not stuck - Uninstalled Docker Desktop and re-installed 4.7.0 and it seems to be working now.
(I think I already lost all layers when I did the factory reset)

**Comment by fidokuba** [comment]
I seem to be in the same boat- updated to 4.7.0, first time it loaded up fine, managed to create a container.
However after restarting my pc later in the day and going to start Docker for Windows, the exact same exception was being thrown preventing it from running.

Have resorted to uninstalling and reverting back to 4.6.1 which seems to start up fine again.

**Comment by ebriney** [comment]
@CJCombrink @fidokuba I have a build with a patch that seems to work, can you test it and give me yourfeedback:
https://desktop-stage.docker.com/win/main/amd64/77294/Docker%20Desktop%20Installer.exe

Thanks, have a good week-end.

**Comment by MichaelKilden** [comment]
Same problem on startup: Docker.Core.PermissionUtils.ApplyACLOnChildren...
Patch solved my problem. Existing windows containers are running again.

**Comment by taurisjoe** [comment]
Thank you @ebriney for this quick fix.  Your patch worked for me.

**Comment by CJCombrink** [comment]
@ebriney 
Sorry for only being able to test now.

I updated another 4.6.1 install with the new patch provided and the upgrade went through without any issues. 
Docker upgraded tot 4.7.0 (Build 77294) and started without issues

**Comment by mat007** [comment]
Thank you for confirming the fix everyone, we will release a Docker Desktop 4.7.1 with it.

**Comment by CJCombrink** [comment]
I am closing this issue since it seems like there is a fix and I have a working install again.
Unfortunately I won't be able to test the exact same setup (upgrading 4.6.1) with a 4.7.1 since all my installs are upgrade to 4.7.0 already

**Comment by ebriney** [comment]
Fixed in 4.7.1: https://desktop.docker.com/win/main/amd64/77678/Docker%20Desktop%20Installer.exe

**Comment by eshvatskyi** [comment]
I'm still getting exception on try to install Docker

`Application: Docker Desktop Installer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Docker.Core.PermissionUtils.CheckPath(System.String, Boolean)
   at Docker.Core.PermissionUtils.CheckACLBeforeRestrictAndCheckSymlink(Docker.Core.ILogger, System.String)
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(Docker.Core.ILogger, System.String, Int32)
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(Docker.Core.ILogger, System.String)
   at CommunityInstaller.Program.Main(System.String[])
`

**Comment by mat007** [comment]
Hi @eshvatskyi, can you try [this internal build](https://desktop-stage.docker.com/win/main/amd64/78501/Docker%20Desktop%20Installer.exe)?

**Comment by eshvatskyi** [comment]
I could try

**Comment by mat007** [comment]
It’s a different build, we’ve fixed a problem with the detection of symlinks in between.

**Comment by eshvatskyi** [comment]
@mat007 my \DockerDesktop - is a link on second herd-drive
