### ISSUE TITLE
Docker Desktop Application is kept/keep logging me out. 

### ISSUE THREAD

**Issue by ghost** [docker/for-win#12745]
I have been using Docker Desktop and a MacOS environment as well as a Widows 10/11 environment and everyday, I have to re-login to the docker desktop and is been annoying.
![Screenshot 2022-05-24 073954](https://user-images.githubusercontent.com/11844123/170063182-d274fa25-98f1-4262-9fb6-a17f67e077c0.png)
The above is not sign in, and the botttom is allows me to log in.
![Screenshot 2022-05-24 074411](https://user-images.githubusercontent.com/11844123/170063925-abbb6c91-35e0-41af-bab8-60e33b930283.png)
after couple of hours or maybe after when i turn off my computer off and turn it on the next day. ti logs me out.

**Comment by keldon2295** [comment]
Same issue

**Comment by sindrekjr** [comment]
Same issue. It seems to only happen on PC reboot.

**Comment by dortizbover** [comment]
Same issue.

**Comment by benlumia007** [comment]
this issue does not just happens in Windows 10 or Windows 11, this issue also happens on MacOS as well.

**Comment by arnoldp-workstreampeople-com** [comment]
Same here

**Comment by Bastians-Bits** [comment]
Same here. Happens after every reboot on Windows 10.

**Comment by AlfinIndrawan** [comment]
I though this is just me. disable two factor auth because it so annoying

**Comment by trungutt** [comment]
Hi, could anyone who has the issue upload an diagnostic ID please?

**Comment by pmarko** [comment]
Same issue here. Introduce "Remember me" feature. It is super annoying.

**Comment by benlumia007** [comment]
can someone upload diagnostic ID for both MacOS and Windows. I'm on Linux right now so i can't upload at the moment.

**Comment by dmckernanacv** [comment]
> can someone upload diagnostic ID for both MacOS and Windows. I'm on Linux right now so i can't upload at the moment.

I included one in https://github.com/docker/for-mac/issues/6362

**Comment by BENNIEV-ZA** [comment]
Same issue on MacOS

**Comment by trungutt** [comment]
Hi, could everyone who has the issue try out these custom builds? They probably won't resolve the issue, but at least they gave us more insight on what was happening, please upload your diagnostic to help us troubleshoot this issue

Mac Intel: https://desktop-stage.docker.com/mac/main/amd64/82239/Docker.dmg
Mac M1: https://desktop-stage.docker.com/mac/main/arm64/82239/Docker.dmg
Windows: https://desktop-stage.docker.com/win/main/amd64/82239/Docker%20Desktop%20Installer.exe

**Comment by trungutt** [comment]
I'd like to have diagnostic the next time when you get logged out

**Comment by ppumkin** [comment]
Same issue. Windows 10. Super annoying. My browser is logged in I gotta keep clicking login in the app which takes me to browser then back to docker.

**Comment by arnoldp-workstreampeople-com** [comment]
It is solved for me with the latest Docker Desktop update

<img width="367" alt="image" src="https://user-images.githubusercontent.com/72133207/178254512-316c308d-c72c-42aa-b9eb-7432ee20d1f9.png">

**Comment by arnoldp-workstreampeople-com** [comment]
> Thank you all for complaining and spamming my mailbox and when somebody asks for help to fix the issue, you all stayed quiet. You people are why open source software still sucks.

I think your comment is the least helpful in this thread

**Comment by dmckernanacv** [comment]
> Thank you all for complaining and spamming my mailbox and when somebody asks for help to fix the issue, you all stayed quiet. You people are why open source software still sucks.

This is the point of open-source, its a community. They are sharing that they are also having the problem. If you're receiving too many emails, unsubscribe from the thread and check back periodically to see if it's fixed, or setup an email filter.

**Comment by ppumkin** [comment]
@codedmonkey  - May I remind you that there's probably a good percentage of people here that PAY to use Docker.
Literally, this is in Docker while I am logged in with a Business license. 
![image](https://user-images.githubusercontent.com/1249683/178271841-f1ff5fbc-f653-43af-a053-348b6ff9a1e8.png)

**Comment by dmckernanacv** [comment]
@trungutt Here is my diagnostic ID, sorry for the delay, had a busy week: 6912E677-27DE-4E09-9E49-3767548B75E8/20220711131512

**Comment by brandonshough** [comment]
Keeps happening to me too on Windows and Mac OS

**Comment by brandonshough** [comment]
How is this still happening? Almost every reboot... UGH

**Comment by AndeYashwanth** [comment]
For me it's happening without rebooting windows 10. I just quit docker desktop yesterday and put laptop to sleep. When I start docker now I see that I got signed out.
So maybe windows reboot is not required. Just quitting docker desktop or putting windows to sleep and waking up is causing the issue.
I'm in 4.11.1 (84025)

**Comment by 1Mark** [comment]
Resolved in 4.12.0

**Comment by arnoldp-workstreampeople-com** [comment]
> Resolved in 4.12.0

I have 4.12.0 and it just logged out.

**Comment by thomasjo** [comment]
> > Resolved in 4.12.0
> 
> I have 4.12.0 and it just logged out.

I can confirm that the problem is still present in 4.12.0 on macOS 12.6.

**Comment by 1Mark** [comment]
Yeah you're right I just had it happen again now.

**Comment by Karbust** [comment]
Keeps happening on Windows 10
Version: Docker Desktop 4.12.0 (85629)

**Comment by AACO** [comment]
I have the same issue.
Windows 11 21H2 22000.978
Docker Desktop 4.12.0 (85629)

**Comment by ursinsaluz** [comment]
Same
Windows 11

**Comment by benlumia007** [comment]
this issue is still going on.

**Comment by trungutt** [comment]
Hi, TBH there are several different causes behind the scene with the logout issue, we're still investigating at the moment. 

Please don't hesitate to upload new diagnostic and put it in the comment if you still experience the issue. If you could recall how that was happening, that would be very helpful for us.

**Comment by dmckernanacv** [comment]
For what it's worth, for me it was consistently after a restart of my computer. Sometimes I actually interacted with docker, other times it was just running containers in the background

**Comment by trungutt** [comment]
@rafrafek Thanks a lot, I'm able to see the failure in this diagnostic, your session expired too soon and it shouldn't. TBH I think a lot of our users experience the same issue... I need to discuss with internal team on it, my apology for this inconvenience

**Comment by trungutt** [comment]
Hi everyone, we changed some configuration on our side in order to resolve this logout issue. Please let us know if you continue to have it, and please don't forget to upload diagnostic in case

**Comment by morganestes** [comment]
@trungutt It just happened to me again this morning after a restart. Diagnostic ID `F3963A74-7EBB-438A-9E35-326B8E99D281/20221018152352`. I'm running Docker Desktop 4.12.0 (85629) on macOS Monterey 12.6

**Comment by igRo** [comment]
Hi @trungutt,

Was also logged out today after the restart. I see the following error in the log:

```
2022-10-19 14:07:18.614331+0200  localhost com.docker.backend[2558]: refreshing tokens: status code not OK but 403: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
2022-10-19 14:07:18.616232+0200  localhost com.docker.backend[2558]: failed to fetch new access token: status code not OK but 403: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
2022-10-19 14:07:18.616960+0200  localhost com.docker.backend[2558]: user logged out, online features will be disabled
```

Diagnostic ID `84ED142B-C021-4179-8B91-ECF04B326DBC/20221019132946`

Docker Desktop 4.12.0 (85629) @ macOS 12.6 (21G115)

**Comment by thomasjo** [comment]
I just got logged out after upgrading to Docker Desktop 4.13.0 (89412) on macOS 12.6 (21G115). Previous version was 4.12.0.

Diagnostic ID: `0BBC22FB-0F59-4AD0-B2CE-698CB0D556A3/20221020145501`

**Comment by SKumarSpace** [comment]
I was experiencing this issue on Windows, but as of Docker Desktop 4.12.0 (85629), it kept me logged in while updating Windows 11

**Comment by iyigit0** [comment]
This is new, this morning I was logged out but this time it showed this popup. See picture below.

![afbeelding](https://user-images.githubusercontent.com/114009141/197714844-fbc01607-1038-4cee-82dc-5705fe87e852.png)

**Comment by alex-necula** [comment]
The same happens to me. M1 Max, macOS 12.6

**Comment by alvaro-araya** [comment]
Hi,

Go to [https://hub.docker.com/settings/security](https://hub.docker.com/settings/security) and generate an access token, then using your terminal:

```bash
$ docker login -u your_username
```

When prompts for the password use your access token.

Windows 11 22H2, WSL version: 0.70.4.0, Docker Desktop v4.13.0

**Comment by steelcracker** [comment]
Happens for me as well regularly.

2CA2873B-E1BF-4B32-8FBA-5F4DEDC351D6/20221108183154
Launched Docker Desktop on Win10 today after a computer boot. In my case it also opened a browser url which said "You were logged out".

**Comment by iyigit0** [comment]
So we have payed for around 10 engineers an huge amount of money. And this is what you have build ?

**Comment by aristofun** [comment]
Still happens on MacOS 13.1 and Docker desktop 4.15.0 (93002)

**Comment by benlumia007** [comment]
works fine with me!

**Comment by aristofun** [comment]
No wonder people flying away from Docker to other solutions - for a year you can't fix the silly but terribly frustrating bug. With all due respect, I'm gonna drop your products and services for good the moment I see alternative that fits my usecase.

**Comment by benlumia007** [comment]
people are using docker no matter what if you're still having issues. Docker isn't just a local development. THere are other services as such as vagrant.  Docker also release a Linux version of the desktop which also has issues when a container is using a non-root user.

**Comment by benlumia007** [comment]
I'm on MacBook Pro 16" Intel which works fine, I'm also on a MacBook Pro 16" M1 Max which also works fine. and I'm also on a Mac studio M1 Max as well, and Windows 11.

**Comment by sjorsverhoef** [comment]
I keep getting logged out on m1 mac using docker desktop. I don't even use a second machine so this is the only place the credentials are used. Before I had to re-login every day and now I have to login every time I reboot my mac using v4.18.0 (104112.

I need a Docker account because my company got noticed and reached out to by Docker because we have a lot of docker users and need Docker desktop accounts to comply with Docker billing. This costs a lot of money and I don't want to cause the company I work for trouble by forgetting to log in. Please look into this issue as it is very relevant to me.

**Comment by pr0b3r7** [comment]
This issue persists in Docker Desktop 4.19.0 (106363) + macOS 13.3.1 (a) (22E772610a) -- Any updates, feedback on how to prevent? @trungutt - Thank you, best regards

**Comment by pickledbrill** [comment]
Docker Desktop 4.19.0 on MacOS still have this issue. Also have a weird issue telling me have issue getting the user list of organization, even though I'm a Personal user.

**Comment by W1773ND** [comment]
I was able to solve this issue by emptying the browser's local storage and session storage relative to https://hub.docker.com/

To do this, go to your browser's developer tools --> Application --> Storage->Clear site data (with the "including third-party cookies" option selected) 
Check that Local Storage and Session Storage have been cleared, then resume the login process from docker desktop as normal.

> Win 11 (22H2)
> Docker Desktop 4.21.0

**Comment by soup-bowl** [comment]
What is considered the normal session length by Docker? It might help in providing diagnostic information. I'm frequently annoyed by this, but it could just be the session length I'm annoyed by rather than experiencing an actual bug. Like e.g. is the session timeout supposed to be "as long as the application is opened X times a week"?

**Comment by shawnaxsom** [comment]
> What is considered the normal session length by Docker? It might help in providing diagnostic information. I'm frequently annoyed by this, but it could just be the session length I'm annoyed by rather than experiencing an actual bug. Like e.g. is the session timeout supposed to be "as long as the application is opened X times a week"?

Our current logged-in duration for Docker Desktop is 30 days if inactive, or 90 days max, unless your ISP is set otherwise.

This was increased on May 31st, (server-side, regardless of Docker Desktop version), which may have helped some users here that have reported issues.

Along with diagnostics, it is helpful to mention the frequency of logouts if you do continue to have issues to see how it compares to these limits.

**Comment by mcx808** [comment]
> Our current logged-in duration for Docker Desktop is 30 days if inactive, or 90 days max, unless your ISP is set otherwise.

What do you consider 'active'? For me it seems every time docker restarts I need to login, however I start docker when my machine boots and uptime is typically > 30 days between reboots.

**Comment by heyask** [comment]
me too. every time I reboot my m1 max mac, docker desktop loses session. 
but quit and reopen docker desktop doesn't loses login session. hmm...

**Comment by Luke-JH** [comment]
Same issue. Ubuntu Linux

**Comment by bsousaa** [comment]
@heyask @Luke-JH can you share a diagnostics id?

**Comment by Luke-JH** [comment]
> @heyask @Luke-JH can you share a diagnostics id?

Diagnostics ID:     b91f1ab3-3e53-4320-a1d7-356475ae5d41/20230824132420

**Comment by heyask** [comment]
> @heyask @Luke-JH can you share a diagnostics id?

I updated to 4.22.1 (118664), and it doesn't loses session

**Comment by zidk** [comment]
with "Start Docker Desktop when you log in activated" checked, the program ask me for log in again every os restart

if I turn off this option and manually open the program after a restart, this issue doesn't happen, I'm not sure is a matter of timing with the internet connexion (openvpn at startup) or with other system service and their launching order.

On macbook M1  | ventura 13.5.1  | Docker Desktop 4.22.1 (118664)

**Comment by oozone** [comment]
The same issue on Ubuntu 22.04 Jammy, Docker desktop v4.22.1 (118664) (latest).
With every reboot, with docker desktop on auto start I need to login again.
It's _very_ annoying.

**Comment by ccsplit** [comment]
I am also having the same issue with Windows 11 Docker Desktop v4.23.0 (120376) (latest). As a sidenote, I attempted the workaround suggested by https://github.com/docker/for-win/issues/12745#issuecomment-1708937633. However, it still prompted stating credentials were invalid and I needed to re-login.

Diagnostic ID: `96A972FC-D5B8-4B13-BC75-0A8BC07E54B8/20230915142444`

**Comment by nogurenn** [comment]
Happens on every boot. Logged in via GUI and CLI as per suggestions.

![image](https://github.com/docker/for-win/assets/15997393/8ba6395b-b628-4bfb-93cd-1f8c8a87837f)

**Comment by pr0b3r7** [comment]
Issue persists in:

- 4.22.1 (118664) on macOS Ventura 13.5.2 (22G91)
- 4.23.0 (120376) on macOS Ventura 13.5.2 (22G91)

**Comment by damianh** [comment]
Happens to me (Win11)on every boot / wake. Very annoying.

**Comment by NikkiSatmaka** [comment]
This happens to me everyday as well, on Debian 12 and Mac m1

**Comment by olivierchatry** [comment]
Happen to me everytime as well, on win11

**Comment by celarye** [comment]
The same thing happens to me on Windows 11 as well.

**Comment by bsousaa** [comment]
@Celarye @olivierchatry @NikkiSatmaka @damianh @pr0b3r7 can you please share a diagnostics id? https://docs.docker.com/desktop/troubleshoot/overview/

**Comment by hlourencomarques** [comment]
The same issue happens to me with Docker Desktop 4.22.1 (118664) on Windows 10 Enterprise 22H2 (19045.3324)

**Comment by celarye** [comment]
@bsousaa I hope this helps: `18BD5FEC-2A6B-4A40-8514-B522532A1015/20230922110740`

**Comment by olivierchatry** [comment]
@bsousaa C6AC8E8E-CB49-47EC-8879-0C3124F53DBF/20230922120241

**Comment by ihor-sviziev** [comment]
@bsousaa I have the same issue on my Mac (with apple silicon) - every time I close and then after some time starting Docker Desktop - it signs me out.
My Diagnostics ID E27C59CC-514B-4202-94C5-89872498DCEB/20230927075655

**Comment by akoessler** [comment]
A reproducible occurence: When Docker Desktop starts (system autostart) but there is no network connection yet (e.g. wifi not yet connected) it will just log out and requires a re-login.

Diagnostics ID of such a case: EA6763F9-FDE1-482A-B01D-67F17B8F4A5D/20230927080908

**Comment by bsousaa** [comment]
We did some changes to the auth backend. Can you confirm if you are still facing the issue? (you may need to refresh your auth token)

**Comment by ccsplit** [comment]
@bsousaa, personally I have not been asked to login again for at least the last two days on restart, so it appears to have worked on my end for Windows 11.

**Comment by celarye** [comment]
It seems to be fixed for me as well.

**Comment by celarye** [comment]
I just noticed that there still seem to be cases where Docker signs you out on startup, restart seems fine for now. Seems like it has to do with Docker launching before having an internet connection...

**Comment by olivierchatry** [comment]
Seems to work for me now.

**Comment by akoessler** [comment]
No, still the same. If there is no network at startup it will immediately be logged out.

**Comment by NikkiSatmaka** [comment]
After updating to docker 4.24, everything works fine

**Comment by bsousaa** [comment]
@akoessler we are investigating the sign-out when there is no network on startup.

**Comment by ViggoV** [comment]
> @akoessler we are investigating the sign-out when there is no network on startup.

I am having this problem as well. My job enforces a combination of antivirus/firewall (WithSecure) and Cloudflare WARP/Zero Trust, which has been known to cause some issues in the past. May be related.

**Comment by Nelwhix** [comment]
same on windows 10

**Comment by raoulvdberge** [comment]
This is still an issue.

**Comment by Geoelycom** [comment]
I'm trying to authenticate my aws to push my container to ecr and I'm stuck on this issue. This is still an issue. I have downloaded and upgraded to the latest version but the issue persists. can someone tell me how they resolve theirs? I'm on macOS. docker version 4.24.2

**Comment by Geoelycom** [comment]
> Hi,
> 
> Go to https://hub.docker.com/settings/security and generate an access token, then using your terminal:
> 
> ```shell
> $ docker login -u your_username
> ```
> 
> When prompts for the password use your access token.
> 
> Windows 11 22H2, WSL version: 0.70.4.0, Docker Desktop v4.13.0

This solves it for me.
docker version 4.24.2 (macOS)

**Comment by celarye** [comment]
This is still an issue for me on the latest versions of Docker Desktop on both Windows and MacOS.

Every time this happens my containers start without accessing my bind mounts, needing me to restart docker engine after manually logging in.

**Comment by matthiasr** [comment]
It seems that this happens whenever Docker Desktop starts without internet access. _Typically_ that's at boot time, but this is not required. I could immediately provoke this on a longrunning mac:

```
❯ uptime
14:54  up 12 days,  3:21, 3 users, load averages: 1.29 1.92 2.00
❯ uname -a
Darwin matthias-0.local 22.6.0 Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:25 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6020 arm64
```

Diagnostic ID:

```
724DCC1C-34D4-4102-A267-741AD9802CB2/20231204145053
```

Steps:

0. Log into Docker Desktop
1. Quit Docker Desktop
2. Disconnect WiFi & wired ethernet
3. Start Docker Desktop -> it starts signed out

**Comment by raoulvdberge** [comment]
I hope docker doesn't send emails to my employer because they are assuming I'm using it without license because they can't keep me signed in.......

**Comment by sjorsverhoef** [comment]
@raoulvdberge Thank you! You exactly describe my problem. Please fix this Docker!

**Comment by SevenFo** [comment]
same on windows 11

**Comment by erkjbro** [comment]
Seems that Docker Desktop will generate new access tokens when I log in, but after a reboot it won't make use of them (in my case). My last one was generated yesterday and upon reboot today it's logged out once again.

Diagnostic ID: 8B4155F8-2981-480A-BA95-25A01A1C0155/20240111025728

![Screenshot 2024-01-10 205405](https://github.com/docker/for-win/assets/14104008/12a711de-0215-46ba-9c0c-e4b3a654a0f5)
![Screenshot 2024-01-10 205501](https://github.com/docker/for-win/assets/14104008/7b54eaee-ecc1-410a-91fc-b276f72a2917)

**Comment by nehalkpatel** [comment]
Same happens to me, about once a week. Does not even require a reboot; Docker Desktop on Win11 just tells me i need to sign in again. Diagnostics ID: `E4713567-DBFA-4882-9642-BD2984F87822/20240129162637`

**Comment by CelloLiu** [comment]
I still have the same issue here! I'm using the version 4.26.1 on windows 11. Please fix it ASAP, thanks.

**Comment by m4ss1m0g** [comment]
I still have the same issue here! I'm using the version 4.27.1 on windows 11

**Comment by luiz-fernandoalves** [comment]
Same here for ubuntu 22.04.3

**Comment by soup-bowl** [comment]
Interestingly each morning the Dashboard application seems to show me as signed out (shows a sign in button), but the right click menu shows my account name, and clicking the "log in" button on the OAuth page doesn't change the GUI state. Verified (possibly) by the fact that I checked the Security part of my account, and it hasn't been creating any new tokens as the current one is still valid.

![A screenshot of both the corner of the Docker Desktop window showing "sign in", and the right click context menu showing the logged in status with the username obscured](https://github.com/docker/for-win/assets/11209477/86c35d32-41d3-4d5c-977d-5837404f0bd9)
(red line was my username - logged in).

Perhaps there is a bug in the Dashboard GUI that can be causing some false positives on being signed out? This goes away after closing and re-opening the window.

My version is 4.27.1 (136059) on Windows 10.

**Comment by celarye** [comment]
I have recently noticed the exact same issue as @soup-bowl. I am not actually getting logged out anymore, the GUI in Docker Desktop shows me as it.

I am also on version 4.27.1 (136059) on Windows 11.

Here is my diagnostic ID: 18BD5FEC-2A6B-4A40-8514-B522532A1015/20240214123138

**Comment by m4ss1m0g** [comment]
I manually generated a token and login with cli `docker login -u <username> -p dk_pat_xyz` then I clicked on the docker desktop login button, closed **without** completing the authentication, closed (minimized) the docker desktop, and reopened show logged in.  At every reboot, I click the login button without completing the auth process with the browser, close/reopen the docker desktop windows (NOT the reboot of service), and the login button showing I'm logged in. I think is a UI problem.

Windows 11, Docker Desktop 4.27.1 (136059)

**Comment by COnlinWangX86** [comment]
hi Docker team
same issue happened in Windows and version4.27.2, please help to check and fix it 
Diagnostics  ID:
955F806F-6530-44FE-98B4-6DD54EAA94CE/20240222100440

**Comment by fexxdev** [comment]
Same using latest 4.27.2 and mac m3

**Comment by jeremiahyan** [comment]
same to me latest 4.28.0

**Comment by m4ss1m0g** [comment]
I manually generated a token on the portal, then I logged in with CLI `docker login -u <username> -p dk_pat_xyz` 

1. On the docker desktop click the button to logout
2. Run the command `docker logout`
3. Generate a token on the Docker Hub web portal
4. Run the command `docker login -u <username> -p dk_pat_xyz` 

Docker Desktop 4.28.0

**Comment by jeremiahyan** [comment]
> I manually generated a token on the portal, then I logged in with CLI `docker login -u <username> -p dk_pat_xyz`
> 
> 1. On the docker desktop click the button to logout
> 2. Run the command `docker logout`
> 3. Generate a token on the Docker Hub web portal
> 4. Run the command `docker login -u <username> -p dk_pat_xyz`
> 
> Docker Desktop 4.28.0

thx, I tried but still failed with following logs:
Error saving credentials: error storing credentials - err: exit status 1, out: `status code not OK but 500: {"message":"getting credential helper update: Post \"https://hub.docker.com/v2/users/login?refresh_token=true\": dialing hub.docker.com:443 host via direct connection because manual override has no HTTPS proxy: connecting to 202.160.129.6:443: dial tcp 202.160.129.6:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"message":"getting credential helper update: Post \"https://hub.docker.com/v2/users/login?refresh_token=true\": dialing hub.docker.com:443 host via direct connection because manual override has no HTTPS proxy: connecting to 202.160.129.6:443: dial tcp 202.160.129.6:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}`

**Comment by xaocon** [comment]
I'll put in my personal experience with the problem in case it helps. Docker Desktop v4.28.0 on Windows 11. I've installed via winget put installed to a non-default location `C:\dev\docker\` to help get around a different issue when a space is used in in the path.

Logging in via the app does redirect to the site and redirects to the app. The app seems to get the request as it pops up but I immediately get notice that I'm not signed in. I can typically log in via the cli (run as admin) and the login is reflected in the windows app, however, it doesn't always work and if it does, it does not survive reboot.

**Comment by justStarG** [comment]
"Processing login data..." after redirect, and it keeps at the step "Processing login data..." for a long time.

**Comment by alexzhangs** [comment]
Same here with macOS 14.2.1 and Docker v4.28.0.

I figured it out it's a firewall related issue here for me.

For some reason I need a proxy to access to domain: hub.docker.com. The signing in was successful on web page, but Docker Desktop keeps signing me out.

My solution:
Go to Docker Desktop Settings -> Features in development, and enable below option:
* Enable SOCKS proxy support

Hope this helps for ones in the same situation.

**Comment by FinnSour** [comment]
Same issue occurring on Docker Desktop v4.28.0, Windows 10
Unclear what is causing it to log out, but I come back and its logged out and my containers are all no longer able to function on networking.

Trying to log in by clicking the Sign In button does not effectively log in, the sign in button remains and containers continue to not function.
Shutting down/quitting docker desktop and then re-opening it successfully logs back in-- no credential entry necessary.
Restarting docker desktop does not do the same. Full Quit and reopen required.

Edit: Diagnostic ID generated after I returned to find docker desktop logged out. I then quit and restarted DD to find myself logged back in. 778C10C1-6436-45D9-AA7F-143AF50595FA/20240325001553

When it happens again I'll generate another diagnostic before quitting DD. Though I'm not confident it will work. I tried yesterday and after 20 minutes it still said "diagnosing..."

**Comment by bartekpacia** [comment]
I know comments like this are worthless, but... come on! Please fix this. It's been happening on my Mac since forever, and it's SO annoying!

**Comment by FinnSour** [comment]
> Same issue occurring on Docker Desktop v4.28.0, Windows 10 Unclear what is causing it to log out, but I come back and its logged out and my containers are all no longer able to function on networking.
> 
> Trying to log in by clicking the Sign In button does not effectively log in, the sign in button remains and containers continue to not function. Shutting down/quitting docker desktop and then re-opening it successfully logs back in-- no credential entry necessary. Restarting docker desktop does not do the same. Full Quit and reopen required.
> 
> Edit: Diagnostic ID generated after I returned to find docker desktop logged out. I then quit and restarted DD to find myself logged back in. 778C10C1-6436-45D9-AA7F-143AF50595FA/20240325001553
> 
> When it happens again I'll generate another diagnostic before quitting DD. Though I'm not confident it will work. I tried yesterday and after 20 minutes it still said "diagnosing..."

It happened again. I ran diagnostics and attempted to upload before I quit and re-logged.

I don't know if it uploaded, because it never actually gave me the ID. I presume it was because DD thought I was logged out and thus had nowhere to send the file? If for some reason it actually uploaded it'd be 778C10C1-6436-45D9-AA7F-143AF50595FA/20240325201206. I've reserved the zip if a verified docker employee wants me to provide it manually

After logging back in it generated and uploaded another diagnostic: 778C10C1-6436-45D9-AA7F-143AF50595FA/20240325202259

**Comment by TerryTang0759** [comment]
> Same here with macOS 14.2.1 and Docker v4.28.0.
> 
> I figured it out it's a firewall related issue here for me.
> 
> For some reason I need a proxy to access to domain: hub.docker.com. The signing in was successful on web page, but Docker Desktop keeps signing me out.
> 
> My solution: Go to Docker Desktop Settings -> Features in development, and enable below option:
> 
> * Enable SOCKS proxy support
> 
> Hope this helps for ones in the same situation.

I've tried with your way, it is OK now. Ths!!!

**Comment by ghostlhq** [comment]
> Same here with macOS 14.2.1 and Docker v4.28.0.
> 
> I figured it out it's a firewall related issue here for me.
> 
> For some reason I need a proxy to access to domain: hub.docker.com. The signing in was successful on web page, but Docker Desktop keeps signing me out.
> 
> My solution: Go to Docker Desktop Settings -> Features in development, and enable below option:
> 
> * Enable SOCKS proxy support
> 
> Hope this helps for ones in the same situation.

Work for me, thx a lot!

**Comment by Youjin1985** [comment]
I cannot even login - I'm signed out as soon as I login. What the hell?

**Comment by 381e35** [comment]
This still happens 2 years later...

**Comment by xinjinzhang** [comment]
for me this reason
[getting credential helper update: Post \"https://hub.docker.com/v2/users/login?refresh_token=true\": dialing hub.docker.com:443 request from host routed via automatic system PAC file proxy socks5://127.0.0.1:1086: SOCKS proxy support is not enabled in settings"]

<img width="1430" alt="image" src="https://github.com/docker/for-win/assets/11190472/097226f6-b9d7-4dd8-8341-3653a40a69f7">

**Comment by xuejianbin** [comment]
> for me this reason [getting credential helper update: Post "https://hub.docker.com/v2/users/login?refresh_token=true": dialing hub.docker.com:443 request from host routed via automatic system PAC file proxy socks5://127.0.0.1:1086: SOCKS proxy support is not enabled in settings"]
> 
> <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/11190472/326645457-097226f6-b9d7-4dd8-8341-3653a40a69f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NTc5MTIsIm5iZiI6MTcxNDQ1NzYxMiwicGF0aCI6Ii8xMTE5MDQ3Mi8zMjY2NDU0NTctMDk3MjI2ZjYtYjlkNy00ZGQ4LTgzNDEtMzY1M2E0MGE2OWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA2MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOGNlNGZjMTJiYzAyOTdjNmY5ZmI5ZWE1NjU0ZjQ5NWUzZDc3ZDg5NzlkZDU5Y2FhMTBhMzZkZTM1NWY3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fT-_mfhQjTwAZXQuDxdZoopb47u0yZM8SwknSqJ4StY">

It works for me. Great!!!

**Comment by ezhufeg-gmail** [comment]
I had the same issue at the beginning after docker desktop installed. I realized that it may be related to proxy setting, and after proxy was configured properly for my docker desktop, login was successful.

**Comment by jpbriend** [comment]
Many issues related to sign-in have been reported in this thread, we would like to apologize for disrupting your workflow and thank you for reporting the issue and the associated environment.

A bug was solved in version `4.30`: when Docker Desktop is starting, if network connectivity is not available (ex: Docker Desktop starts faster than Wifi connects), then Docker Desktop signs the user out.
Now Docker Desktop should automatically reconnect using the stored credentials 10 seconds maximum after network connectivity is available.
I encourage everybody who had this issue (being signed out when starting the laptop with Docker Desktop starting at startup) to upgrade to version `4.30+`.

SOCKS proxy support was added recently. We are able to detect PAC files and use this PAC file when you enable SOCKS proxy support (this is what [xinjinzhang](https://github.com/xinjinzhang) found). PAC files and SOCKS proxy are useful in corporate environment but very often end-users are not aware their workstation is configured with a SOCKS proxy. It's "transparent" and often not communicated.
With version `4.30`, the SOCKS proxy support UI setting (`Enable SOCKS proxy support`) is gone and replaced by an automatic detection of the proxy on you workstation: Docker Desktop will automatically used the proxy configured on your workstation. This should solve the issues related to proxies (common in corporate environments).

The UI issue raised around February has been solved in `4.29`: the `Sign In` button was not correctly refreshed, making you think Docker Desktop is not logged in while it was. If other issues related to the button (and inconsistent state), please open a dedicated ticket and we'll have a look at it.

@FinnSour your issue seems to be related to hibernation. Would you mind creating a dedicated issue so we can keep the investigations going on with you?

As a reminder, whenever you face a login issue, please indicate the way you sign in (Docker CLI `docker login` or the `Sign In` button in the UI), the various actions you did, the context and generate a diagnostic. The more details we have, the better we can investigate. Dedicated issues also help us communicate individually with you.
Thank you for your patience.

**Comment by Youjin1985** [comment]
> Many issues related to sign-in have been reported in this thread, we would like to apologize for disrupting your workflow and thank you for reporting the issue and the associated environment.
> 
> A bug was solved in version `4.30`: when Docker Desktop is starting, if network connectivity is not available (ex: Docker Desktop starts faster than Wifi connects), then Docker Desktop signs the user out. Now Docker Desktop should automatically reconnect using the stored credentials 10 seconds maximum after network connectivity is available. I encourage everybody who had this issue (being signed out when starting the laptop with Docker Desktop starting at startup) to upgrade to version `4.30+`.
> 
> SOCKS proxy support was added recently. We are able to detect PAC files and use this PAC file when you enable SOCKS proxy support (this is what [xinjinzhang](https://github.com/xinjinzhang) found). PAC files and SOCKS proxy are useful in corporate environment but very often end-users are not aware their workstation is configured with a SOCKS proxy. It's "transparent" and often not communicated. With version `4.30`, the SOCKS proxy support UI setting (`Enable SOCKS proxy support`) is gone and replaced by an automatic detection of the proxy on you workstation: Docker Desktop will automatically used the proxy configured on your workstation. This should solve the issues related to proxies (common in corporate environments).
> 
> The UI issue raised around February has been solved in `4.29`: the `Sign In` button was not correctly refreshed, making you think Docker Desktop is not logged in while it was. If other issues related to the button (and inconsistent state), please open a dedicated ticket and we'll have a look at it.
> 
> @FinnSour your issue seems to be related to hibernation. Would you mind creating a dedicated issue so we can keep the investigations going on with you?
> 
> As a reminder, whenever you face a login issue, please indicate the way you sign in (Docker CLI `docker login` or the `Sign In` button in the UI), the various actions you did, the context and generate a diagnostic. The more details we have, the better we can investigate. Dedicated issues also help us communicate individually with you. Thank you for your patience.

This is incorrect information.
I just tried to login with newest 4.30.0 version - "Sign in" in docker desktop - website https://login.docker.com/ opens - I enter login and password - Dockep app opens again with popups:  Processing Login Data - Verifying credentials for ... - then browser with "You have been signed out" appears.

**Comment by Youjin1985** [comment]
> With version `4.30`, the SOCKS proxy support UI setting (`Enable SOCKS proxy support`) is gone and replaced by an automatic detection of the proxy on you workstation: Docker Desktop will automatically used the proxy configured on your workstation. This should solve the issues related to proxies (common in corporate environments).

This one was totally terrible design desision. I use Socks5 proxy from another machine in LAN, and set http_proxy for applications I need - how your update could deal with that now, when proxy is on another workstation.

**Comment by jpbriend** [comment]
> > Many issues related to sign-in have been reported in this thread, we would like to apologize for disrupting your workflow and thank you for reporting the issue and the associated environment.
> > A bug was solved in version `4.30`: when Docker Desktop is starting, if network connectivity is not available (ex: Docker Desktop starts faster than Wifi connects), then Docker Desktop signs the user out. Now Docker Desktop should automatically reconnect using the stored credentials 10 seconds maximum after network connectivity is available. I encourage everybody who had this issue (being signed out when starting the laptop with Docker Desktop starting at startup) to upgrade to version `4.30+`.
> > SOCKS proxy support was added recently. We are able to detect PAC files and use this PAC file when you enable SOCKS proxy support (this is what [xinjinzhang](https://github.com/xinjinzhang) found). PAC files and SOCKS proxy are useful in corporate environment but very often end-users are not aware their workstation is configured with a SOCKS proxy. It's "transparent" and often not communicated. With version `4.30`, the SOCKS proxy support UI setting (`Enable SOCKS proxy support`) is gone and replaced by an automatic detection of the proxy on you workstation: Docker Desktop will automatically used the proxy configured on your workstation. This should solve the issues related to proxies (common in corporate environments).
> > The UI issue raised around February has been solved in `4.29`: the `Sign In` button was not correctly refreshed, making you think Docker Desktop is not logged in while it was. If other issues related to the button (and inconsistent state), please open a dedicated ticket and we'll have a look at it.
> > @FinnSour your issue seems to be related to hibernation. Would you mind creating a dedicated issue so we can keep the investigations going on with you?
> > As a reminder, whenever you face a login issue, please indicate the way you sign in (Docker CLI `docker login` or the `Sign In` button in the UI), the various actions you did, the context and generate a diagnostic. The more details we have, the better we can investigate. Dedicated issues also help us communicate individually with you. Thank you for your patience.
> 
> This is incorrect information. I just tried to login with newest 4.30.0 version - "Sign in" in docker desktop - website https://login.docker.com/ opens - I enter login and password - Dockep app opens again with popups: Processing Login Data - Verifying credentials for ... - then browser with "You have been signed out" appears.

Can you generate a Diagnostic and share the ID please?

**Comment by jpbriend** [comment]
> > With version `4.30`, the SOCKS proxy support UI setting (`Enable SOCKS proxy support`) is gone and replaced by an automatic detection of the proxy on you workstation: Docker Desktop will automatically used the proxy configured on your workstation. This should solve the issues related to proxies (common in corporate environments).
> 
> This one was totally terrible design desision. I use Socks5 proxy from another machine in LAN, and set http_proxy for applications I need - how your update could deal with that now, when proxy is on another workstation.

Proxy can still be configured manually. What I said is that if the Windows host machine has a PAC file configured, then Docker Desktop will use it.

**Comment by Youjin1985** [comment]
> Can you generate a Diagnostic and share the ID please?

Of course, thank you, here it is:
8D61C702-4519-4067-A3F6-B4F1C4698EA4/20240529064226

**Comment by jpbriend** [comment]
@Youjin1985 you are running Docker Desktop on Mac, please use [for-mac](https://github.com/docker/for-mac/issues) next time.

Your problem comes from this:
`Post "https://hub.docker.com/v2/access-tokens/desktop-generate": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

Can you check if you have network connectivity to https://hub.docker.com/v2/access-tokens/desktop-generate?
For example, on my side, this what I get:
```
curl -v https://hub.docker.com/v2/access-tokens/desktop-generate

* Host hub.docker.com:443 was resolved.
* IPv6: (none)
* IPv4: 54.156.140.159, 44.221.37.199, 52.44.227.212
*   Trying 54.156.140.159:443...
* Connected to hub.docker.com (54.156.140.159) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.docker.com
*  start date: Apr  4 00:00:00 2024 GMT
*  expire date: May  3 23:59:59 2025 GMT
*  subjectAltName: host "hub.docker.com" matched cert's "*.docker.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M03
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /v2/access-tokens/desktop-generate HTTP/1.1
> Host: hub.docker.com
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< date: Wed, 29 May 2024 07:01:56 GMT
< content-type: application/json
< content-length: 40
< x-xss-protection: 1; mode=block
< x-ratelimit-limit: 180
< x-ratelimit-reset: 1716966176
< x-ratelimit-remaining: 178
< x-trace-id: 4dc2781375a7fb5020d5cd7bdf647240
< x-frame-options: deny
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000
<
{"message":"unauthorized","errinfo":{}}
* Connection #0 to host hub.docker.com left intact
```

**Comment by Youjin1985** [comment]
> Can you check if you have network connectivity to https://hub.docker.com/v2/access-tokens/desktop-generate?
> For example, on my side, this what I get:
I confirm, there is no network connectivity to this address from my mac with docker-desktop.
Using curl, request hangs on *   Trying 128.121.146.109:443...
Using LAN http_proxy with curl, I immediately get response like yours. 

I just set same proxy manually in Settings - Resources - Proxies and was able to login. Thank you so much.


> @Youjin1985 you are running Docker Desktop on Mac, please use [for-mac](https://github.com/docker/for-mac/issues) next time.

Sorry about this

**Comment by jpbriend** [comment]
@Youjin1985 Happy Dockering :)

**Comment by Chang-huilin** [comment]
> > Can you check if you have network connectivity to https://hub.docker.com/v2/access-tokens/desktop-generate?
> > For example, on my side, this what I get:
> > I confirm, there is no network connectivity to this address from my mac with docker-desktop.
> > Using curl, request hangs on *   Trying 128.121.146.109:443...
> > Using LAN http_proxy with curl, I immediately get response like yours.
> 
> I just set same proxy manually in Settings - Resources - Proxies and was able to login. Thank you so much.
> 
> > @Youjin1985 you are running Docker Desktop on Mac, please use [for-mac](https://github.com/docker/for-mac/issues) next time.
> 
> Sorry about this

A successful solution was finally found,thanks :)

**Comment by tennessine** [comment]
Still the problem in 2025.04.22 in China with macos12.7.6

**Comment by webstackdev** [comment]
Still the same problem May 16 2025, KUbuntu 24.10. Clicking "Sign in" takes me to the login page in Chrome, which remembers my login and automatically the desktop signs me in. Then immediately signs me back out. This is a very long thread with hundreds of posts now, I'll have to block out a few hours of my free time this weekend to read through it all. Sure would be nice if it worked out of the box. Latest version of Docker Desktop at time of writing - 4.41.1.

curl -v https://hub.docker.com/v2/access-tokens/desktop-generate shows "unauthorized". I can log into Docker Hub with my account, so not sure how to fix this.

**Comment by jpbriend** [comment]
@webstackdev can you generate a diagnostic and share the ID with me?
You can find the documentation on how to generate one from the App or from the CLI here: https://docs.docker.com/desktop/troubleshoot-and-support/troubleshoot/#diagnose

**Comment by luisfi-dev** [comment]
> [@webstackdev](https://github.com/webstackdev) can you generate a diagnostic and share the ID with me? You can find the documentation on how to generate one from the App or from the CLI here: https://docs.docker.com/desktop/troubleshoot-and-support/troubleshoot/#diagnose

I'm facing the same issue as @webstackdev ([https://hub.docker.com/v2/access-tokens/desktop-generate](https://hub.docker.com/v2/access-tokens/desktop-generate) shows "unauthorized", and Docker Desktop logs out immediately after logging in). Here's my diagnostic ID: 587D391C-B206-42F8-A6FC-9F31661328BC/20250527003228

**Comment by jpbriend** [comment]
For errors on Linux, it's 99% of the time issues with `pass` not correctly configured.
`pass` is used to securely store the access_token to maintain the Signed In session.

Make sure you follow this documentation to correctly initialize `pass` on Linux: https://docs.docker.com/desktop/setup/sign-in/#signing-in-with-docker-desktop-for-linux

**Comment by glauberdm** [comment]
Still.

Docker Desktop 4.43.1 (198352) 
Fedora release 42 (Adams)
Pass configured 
<img width="307" height="42" alt="Image" src="https://github.com/user-attachments/assets/2bc56309-8ce4-4e26-a404-625e2e942d04" />
I can download images and use Docker CLI. However, in Docker Desktop, it still loops, showing 'not logged', and I can't select features that require logging.

**Comment by lifetin** [comment]
me to +1

**Comment by armeldemarsac92** [comment]
Bugfix: Docker Desktop on Fedora - Fixing GPG "database_open waiting for lock" Error

Symptoms

When starting Docker Desktop on a Fedora (or similar systemd-based) system, the application fails to start.

Checking the logs (journalctl --user -u com.docker.backend -f) reveals a persistent GPG error related to authentication, even after reboots, resets, or reinstalling:
Extrait de code

[main.auth][E] an error occurred during authentication process. User is signed out: error getting credentials - err: ... gpg: Note: database_open 134217901 waiting for lock (held by 6796) ...

This error also appears when running any gpg command, like gpg --list-keys:
Bash

$ gpg --list-keys
gpg: Note: database_open 134217901 waiting for lock (held by 6796) ...
gpg: keydb_search_first failed: Connection timed out

The Problem

This is not a Docker Desktop bug. It is a problem with the system's gpg-agent service.

A gpg-agent process (like the "ghost" PID 6796 in the logs) has previously crashed or hung. This crash left behind "stale" lock files in two different locations:

Database Locks: In the ~/.gnupg directory (e.g., pubring.kbx.lock).

Socket Locks: In the runtime directory (/run/user/...).

Any new attempt to use GPG (by Docker's credential helper, or by you) sees these locks, waits for the ghost process to release them, and eventually times out.

The Solution

The fix is to manually delete all stale lock files and sockets and then properly restart the GPG services using systemd.

This 3-step process clears all stale files and restarts the services cleanly.
Bash

# 1. Find and delete all stale database locks in your GPG home
    find ~/.gnupg -name "*.lock" -exec rm -f {} \;

# 2. Delete all stale service sockets from the runtime directory
    rm -f /run/user/$(id -u)/gnupg/*

# 3. Restart the GPG services using the correct systemd/Fedora method
    systemctl --user restart gpg-agent.socket
    systemctl --user restart gpg-agent.service

Explanation of the Commands

find ~/.gnupg ...: This command robustly finds any file ending in .lock inside your GPG directory and deletes it. This is more reliable than a simple rm command.

rm -f /run/user/...: This clears the broken runtime socket files (like S.keyboxd) that the GPG agent uses to communicate.

systemctl --user restart ...: This is the most important step. On Fedora, gpg-agent is managed by systemd. These commands tell systemd to forcefully stop the broken services and start fresh ones. This is the correct way to "reset" the agent, which simple killall commands will not do.

After running this sequence, gpg --list-keys will work again, and Docker Desktop will start and log in successfully.
