### ISSUE TITLE
Docker can not start properly after 4.9 update on window 11

### ISSUE THREAD

**Issue by EngDuraid** [docker/for-win#12784]
Docker can not start properly after 4.9 update on window 11.
I tried to remove docker and reinstall it and this is does not work.

**Comment by hantsy** [comment]
Also stopped on Windows 10. Also reinstalled several times.

After I restarted the system, try to start it immediately some time it was successful. Most of time, click the icon and show the UI to start, and then crash.

**Comment by FernandoGomez** [comment]
Same here.  I tried 4.9.1 and it just sits there until it crashes.

**Comment by EngDuraid** [comment]
I just uninstall the versions (4.9 and 4.9.1) and rollback to 4.8.2 (79419) and the problem solved.

**Comment by nimdasx** [comment]
same here, 4.9.1 after restart windows, docker desktop can't start... starting then crashes

**Comment by jatin711-debug** [comment]
Yes, True on Windows 10, I was tryna debug and fix for 5-6 hours, I tried stopping service and restart again. 
I really think somehow settings.json file inside docker is corrupted maybe. After I delete settings.json and run it, it runs like default settings but after stopping daemon and starting again this loops carry on of crashing. 
To Be Noted: I think this error started from 4.9.0. 2 days back in 4.8 , it was running smoothly, but after I updated on 4.9.0, Error started. There is also error while switching from Linux to Windows container.
command -> DockerCli -SwitchDaemon  seems to do nothing, mostly crashes.
Best thing to do is to downgrade docker desktop, I installed 4.4 Version

**Comment by hantsy** [comment]
Struggled with 4.9.0 and 4.9.1 for a few days, I decided to return back to 4.8.2 and save my life.

**Comment by rfay** [comment]
I couldn't make 4.9.0 or 4.9.1 install and stay alive, so rolled back to 4.8.2 (Windows 11).

I was able to 
1. Uninstall everything and manually remove .docker, AppData/Local/Docker*, etc
2. Install 4.9.1
3. Start it
4. Use it

But then when I exited Docker Desktop or rebooted it would never come up again

**Comment by rfay** [comment]
Diagnostics using command-line tool: 4EB47BB2-AFFE-49A7-B331-0CA7D8093B1A/20220618182810

**Comment by Jens-G** [comment]
I have no hard prove for it but it might have to do sth. with the existence of a **c:\temp** folder. At least I can reproduce it when that folder is missing. Creating it instantly solves the problem at least on  my machine.

**Comment by hantsy** [comment]
@Jens-G Interesting.

**Comment by rfay** [comment]
I tried creating C:\temp, which did not previously exist (fresh Win11). It does not seem to have changed the behavior.

**Comment by ythuang** [comment]
on Windows 10 Pro 21H1 , docker desktop 4.9.1 start-stop-crash, created c:\temp, it started correctly ...

**Comment by LuigiMaestrelli** [comment]
Same problem here on windows 11.
After installing docker from scratch ir runs fine until I restart the pc, after that it never works again.
tried creating the temp  folder, but it changed nothing.

**Comment by AlexKovynev** [comment]
It look like it only autostart problem. If disable it and run later all fine. If not disable don't run not only docker but also wsl freeze.

**Comment by jatin711-debug** [comment]
No updates from Docker Devs ? Come on

**Comment by rfay** [comment]
Here's what I tried, and thought I was almost successful (Win11)

1. Uninstall docker desktop
2. Completely uninstall WSL2 and components following [article](https://pureinfotech.com/uninstall-wsl2-windows-10/)
3. Reboot
4. `wsl --install`
5. Install Docker Desktop 4.9.1

It came up, yay! I exited using the menu and restarted via windows menu and it came up, yay! But... then I restarted the machine and it won't come up at all. You launch it from the start menu and it says "Docker Desktop stopped" and then just disappears. #fail

**Comment by rfay** [comment]
Tweeted to @docker, https://twitter.com/randyfay/status/1539396666184245249

**Comment by K2ouMais** [comment]
This have been a problem already on Windows 10 for ages, but the Docker team doesnt seem to bother about it.

I am still on Windows 10 and have the exact same problem.

There is no way you cant set Docker on Startup, because it wont start for you. It just crashes.

Even without  an automatic start it will fail/crash on the first start too, so you have again to click the docker icon for it to start properly.

It is a shame, because the Docker Forum is full of people having the same problem, but nothing is beeing done.

**Comment by rfay** [comment]
Docker team, I'm happy to give you remote access to the Windows 11 system that demonstrates this.

**Comment by 1054429861** [comment]
same problem on win10, 4.9.1 always stopping and quit

**Comment by hantsy** [comment]
It seems this issue tracker is just a discussion channel for the community users, not a real issue tracker.

**Comment by StefanScherer** [comment]
Thanks for raising this. We're looking into it, we didn't encounter this effect on our Windows 11 machines.

**Comment by K2ouMais** [comment]
This is not a windows 11 issue. Take a look at the docker forum and you will see this is a very old problem that now reaches also Windows 11. I am having this issue now for almost 1 year and this never got an answer from the docker team at all.

**Comment by ythuang** [comment]
below is what the windows event log recorded.
===
Faulting application name: Docker Desktop.exe, version: 4.9.1.0, time stamp: 0xd6c6e7a3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1741, time stamp: 0xe9b4a91b
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x17a0
Faulting application start time: 0x01d8876eccd6d6e9
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9a8e0db8-0509-4c50-965d-248b95b1f23b
Faulting package full name: 
Faulting package-relative application ID: 
====
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskCanceledException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at HttpOverStream.NamedPipe.NamedPipeDialer+<DialAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at HttpOverStream.Client.DialMessageHandler+<SendAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.IPC.Client+<SendAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.ServiceAPIClient+<UpdateHostsAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by nimdasx** [comment]
> same here, 4.9.1 after restart windows, docker desktop can't start... starting then crashes

then I downgrade to version 4.8.2 -> running normal (on laptop with 8GB ram).
btw, I have pc with 12GB ram, version 4.9.1 is running normal.
so I decided to upgrade ram on my laptop, then version 4.9.1 running normal.

so solution for me is : upgrade ram

**Comment by akpatternica** [comment]
@nimdasx i have 32 GB of ram. It look like it something else.

**Comment by hantsy** [comment]
@nimdasx I do not think it is a problem about the ram size.
I used a laptop with 16G, version 4.8.2 worked well. 
And Docker for Windows runs on HyperV and WSL. I have changed the wslconfig to adjust the ram and cpu cores, no help at all.

**Comment by fnfzlznddzn** [comment]
Same problem here, update 4.9 is completely broken.
Had to uninstall it to reinstall 4.8.2, which fixed the problem... but made me lose a lot of data...

**Comment by StefanScherer** [comment]
We have an [internal build 81706](https://desktop-stage.docker.com/win/main/amd64/81706/Docker%20Desktop%20Installer.exe) which we would like to get feedback if it solves the start problem. If it still doesn't start, you could also [send and upload diagnostics from the command line](https://docs.docker.com/desktop/windows/troubleshoot/#diagnosing-from-the-terminal) so we get a better understanding. Thank you.

**Comment by nimdasx** [comment]
@hantsy @akpatternica oh correct its not related to ram. after i restart laptop, problem witch docker 4.9.1 appear again

**Comment by AstrisDev** [comment]
@StefanScherer windown 11 21H2 22000.739, yor internal build didn't solve the start problem. Uploaded diagnostic info: Diagnostics ID:  391206CC-6B35-489A-8D12-E558636C37A2/20220624125157

**Comment by AlexKovynev** [comment]
@StefanScherer for me it solve

**Comment by rfay** [comment]
So far so good! Windows 11, had 4.8.0 on there. Installed [81706](https://desktop-stage.docker.com/win/main/amd64/81706/Docker%20Desktop%20Installer.exe) and 
* I started docker after installation (when are we going to get a "start now" button after installation? Or a start-after-installation checkbox?). It came up. Set it to start on login.
* Stopped docker desktop and started it again. It came up and was reachable.
* Rebooted machine and docker desktop came up successfully.

Yay, thanks for working on this @StefanScherer . I'll keep this running and see how it does with ddev tests.

**Comment by doliveira19** [comment]
For me, the "temporary solution" was:

- Open "Task Manager"
- Close the task "Docker Desktop Service"
- Re-open Docker Desktop
- Wait for the GUI to show (do not click on "start" if it pops-up...wait for the GUI to show)
- Click on "start" when prompted to start Desktop Service

**Comment by gabrielsoldani** [comment]
Mentioned this in #12794. As a workaround, deleting `%AppData%\Docker\settings.json` fixes it every time for me, but next time it crashes on startup again.

**Comment by 01011011** [comment]
Thanks @gabrielsoldani so if I delete the file and restart computer, it would start up the first time successfully?  I am running VMs that are saved and once closed they restart from the image I originally save, so it might fix the problem temporarily until there is a real fix.  I will try.

**Comment by 01011011** [comment]
I can confirm that deleting the %AppData%\Docker\settings.json file and then restarting computer worked (but only for that initial time), if you restart the computer again, it will still crash.

This is not happening only on Win 10, this is Windows 11 problem as well.

**Comment by 01011011** [comment]
I want to also confirm, that second time I deleted the setting.json file and restarted the computer, docker did not even attempt to start.  I had to manually start it which it worked, but there was no auto-start. :(

**Comment by gabrielsoldani** [comment]
Deleting this file also makes Docker Desktop ask again if you agree to some of its terms and, if it wasn't clear from the name, will wipe your settings out.

**Comment by 01011011** [comment]
Yes, I did understand that, that would be fine with me as long as it would start.  But it only worked the first time I restarted, after that I deleted the file and Docker did not even try to start.

**Comment by rfay** [comment]
@StefanScherer I had this problem with a Win10 machine that automatically updated itself to 4.9.1 on reboot (thought it wasn’t supposed to do that any more?) and got the diagnostics via command-line, 6336DFC1-4E32-4205-B071-45EE3395B9C7/20220626131649 -

I then installed [81706](https://desktop-stage.docker.com/win/main/amd64/81706/Docker%20Desktop%20Installer.exe) and it installed and I was able to start it and then `docker ps` (that's definite progress). I stopped it and restarted, OK, then stopped and restarted again and it didn’t come up. It’s an odd sequence of “Docker Desktop Stopped”→”Docker Desktop Starting”, and then sudden exit. Diagnostics via command-line at  6336DFC1-4E32-4205-B071-45EE3395B9C7/20220626140056

I'll keep this Win10 machine out of the DDEV test rotation and you're welcome to have remote access to it.

**Comment by ChristianGrimberg** [comment]
I have the same problem on Windows 11 Pro:
```txt
System.InvalidOperationException:
Failed to unregister distro: exit code: -1
 stdout: Unregistering...
There is no distribution with the supplied name.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 160
   at Docker.Engines.WSL2.WSL2Provisioning.<UnregisterDistroAsync>d__16.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<UnprovisionAsync>d__9.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoDestroyAsync>d__34.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.DestroyTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\DestroyTransition.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<DestroyAsync>d__16.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RemoveDataAsync>d__25.MoveNext() in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 194
```
I re-registered the WSL distributions and got the same result.

**Comment by StefanScherer** [comment]
@rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

**Comment by igor-markin** [comment]
> @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

I'm downloading to check. Will this version be automatically updated further?

**Comment by StefanScherer** [comment]
> I'm downloading to check. Will this version be automatically updated further?
@igor-markin Thank you. And yes, it will show further updates, for example the next official release 4.10.0.

**Comment by K2ouMais** [comment]
> @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

This doesnt solve my problem, that I am having with Docker for ages now.

I just made a video and will post it here, for you all to see.

https://youtu.be/iDHbKODpmRc

**Comment by djs55** [comment]
@K2ouMais thanks, that looks like a different error to the one fixed in the test build. Could you upload diagnostics and quote the ID here?

**Comment by K2ouMais** [comment]
> @K2ouMais thanks, that looks like a different error to the one fixed in the test build. Could you upload diagnostics and quote the ID here?

Sure.

Diagnostics ID:     032419A8-8A9A-4FAC-96E2-C88E91A6CCCD/20220628125112 (uploaded)

**Comment by gabrielsoldani** [comment]
@StefanScherer commented [7 hours ago](https://github.com/docker/for-win/issues/12784#issuecomment-1168271043):
> @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

Works on my machine. Thanks :^)

**Comment by jolopher** [comment]
In my case, I solved my problems by unchecking "Containers", "Hyper-V", and "Windows Hypervisor Platform" in the Windows Features.

**Comment by rfay** [comment]
Thanks so much @StefanScherer - I installed [89898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) on the two machines (Win10 and Win11) that were showing this problem. On both of them I did "Quit Docker Desktop" and then started it several times, and also rebooted several times. Both held up fine.

The one issue you'll not be happy with is that on both systems the right pane of the dashboard (the main pane) was always empty and white, and I imagine you want content there.

**Comment by fabrice102** [comment]
Thanks so much @StefanScherer, build 89898 also solved the issue in my Win 11 VM.

**Comment by nimdasx** [comment]
> @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

@StefanScherer  thanks, tested and rebooted windows 2x, still working fine.

**Comment by vovanluc1** [comment]
@StefanScherer, working fine for build 89898. Thanks.

**Comment by ythuang** [comment]
> @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.

Startup is smooth on Win10 21H2 for build 81898

**Comment by StefanScherer** [comment]
Thank you all for the feedback!
@rfay the problem with the empty screen is fixed, but this fix didn't get into this internal build.

**Comment by ythuang** [comment]
> > @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.
> 
> Startup is smooth on Win10 21H2 for build 81898

but it seems to cause pycharm 2022.1.3 's skeleton generator to be stuck
reverting back to 4.9.1 seem to fix the issue...

**Comment by alpanachaphalkar** [comment]
> > @rfay and others, we have a new [internal build 81898](https://desktop-stage.docker.com/win/main/amd64/81898/Docker%20Desktop%20Installer.exe) that stabilises the startup process. We would love to get feedback on this version if it solves the problems you see on your machines. Thank you.
> 
> Docker still not started. Dignostics ID: 3BB36A81-1291-483C-A124-3D17F3AA34C1/20220629092940

Docker started after i ran with admin privileges. Thanks @StefanScherer!

**Comment by kavehghelich** [comment]
Docker Desktop was crashing during start up after windows restart following installing/updating to 4.9.
Just ran WSL once (in PowerShell) and the problem gone, even with next windows restarts.

**Comment by maxcleme** [comment]
This issue has been fixed in latest release, please consider updating to latest version and give us your feedback!

[4.10.0 Release notes](https://docs.docker.com/desktop/release-notes/#docker-desktop-4100)

**Comment by binary-signal** [comment]
issue is still present with Docker desktop version 4.10.1 build  (82475)

**Comment by adonism2k** [comment]
> issue is still present with Docker desktop version 4.10.1 build (82475)

Same here.

Windows Version: 21H2 (19044.1526)
Docker Desktop Version: 20.10.17
WSL2 or Hyper-V backend? WSL2

### Steps to reproduce the behavior and still doesn't work
1. Reinstall Docker Desktop
2. Delete the settings.json file and then restart the computer
3. Delete C:\Users{user}.docker, C:\Users{user}\AppData\Local\Docker, and C:\Users{user}\AppData\Roaming\Docker. and then restart the computer.
4. Start and stop Docker service in Service Configuration Panel. and then restart the computer.

**Comment by altjx** [comment]
Still present in version 4.10.1

https://user-images.githubusercontent.com/4023423/180612014-f31c2eb5-5d64-433e-8ce4-e556d4bf5327.mov

**Comment by Devoney** [comment]
Still present in 4.11.0, just installed Docker after installing WSL on a fresh Win11 install.

**Comment by blackr1234** [comment]
Win 11 Home 21H2
Docker Desktop 4.10.1

1. Turn on feature "Windows Hypervisor Platform"
1. Restart
1. Start Docker
1. It asks for WSL
1. Download and install the update
1. Click Restart button in Docker Desktop
1. Docker engine is running

**Comment by amm834** [comment]
> Win 11 Home 21H2 Docker Desktop 4.10.1
> 
> 1. Turn on feature "Windows Hypervisor Platform"
> 2. Restart Windows
> 3. Start Docker
> 4. It asks for WSL
> 5. Download and install the WSL update
> 6. Click the Restart button in Docker Desktop
> 7. Docker engine is finally running

Where is restart button? I don't see that.

**Comment by InfamousUser** [comment]
Crashing/hanging intermittently here, Windows 10 and Docker 4.11.1. Just managed to get it running after many restarts.

**Comment by squallstar** [comment]
This is also happening for me on 4.11.0 and 4.11.1:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/574210/184830402-d35511f5-6663-424c-87f5-47c00eab93c2.png">

```
-------------------------------------------------------------------------------->8
Version: 4.11.0 (83626)
Sha1: 6b4b2fc653596c121c0b4e62f7a4ba67635066f3
Started on: 2022/08/16 07:55:54.904
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22622
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-08-16T07:55:55.951512500Z][DockerService     ][Info   ] Starting service
[2022-08-16T08:00:26.131103600Z][IPCServer         ][Info   ] (23ff1380) 1618e160-ServiceAPI S<-C 629d9480-ServiceAPIClient-CSharp GET /version
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 103
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.ResolvePipeAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 24
   at Docker.Core.BackendAPI.ServiceAPIClient.CreateSystemHttpClientAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 135
   at Docker.Core.BackendAPI.ServiceAPIClient.TryGetVhdxSize(String path)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
   at Docker.Engines.SettingsAdjuster.CopyVhdxSizeAsync(Settings settings)
   at Docker.App.<InitializeAsync>d__12.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 72
   at Docker.App.InitializeAsync(Singletons singletons)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 222
   at Docker.Program.Main(String[] args) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 118
[2022-08-16T08:00:26.373696400Z][IPCServer         ][Info   ] (23ff1380) 1618e160-ServiceAPI S->C 629d9480-ServiceAPIClient-CSharp GET /version (240ms): OK
[2022-08-16T08:00:26.823064200Z][IPCServer         ][Info   ] (c5e1f3ed) 1618e160-ServiceAPI S<-C 587266bf-ServiceAPIClient-CSharp GET /hyperv/vhdx-size
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 137
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 31
[2022-08-16T08:00:26.976115600Z][IPCServer         ][Info   ] (c5e1f3ed) 1618e160-ServiceAPI S->C 587266bf-ServiceAPIClient-CSharp GET /hyperv/vhdx-size (154ms): OK
[2022-08-16T08:00:29.112073900Z][IPCServer         ][Info   ] (de2c8b47) 1618e160-ServiceAPI S<-C 4532f3e0-ServiceAPIClient-CSharp POST /dns/refresh-hosts
   at Docker.Core.BackendAPI.ServiceAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 0
   at Docker.Core.BackendAPI.ServiceAPIClient.UpdateHostsAsync(CancellationToken cancellationToken)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 101
   at Docker.Engines.WSL2.LinuxWSL2Engine.<SendState>d__35.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 353
[2022-08-16T08:00:30.058459700Z][IPCServer         ][Info   ] (de2c8b47) 1618e160-ServiceAPI S->C 4532f3e0-ServiceAPIClient-CSharp POST /dns/refresh-hosts (938ms): OK
[2022-08-16T08:05:31.407556700Z][IPCServer         ][Info   ] (e5756dc9) 1618e160-ServiceAPI S<-C 2b9ff98b-ServiceAPIClient-CSharp GET /version
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 103
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.ResolvePipeAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 24
   at Docker.Core.BackendAPI.ServiceAPIClient.CreateSystemHttpClientAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 135
   at Docker.Core.BackendAPI.ServiceAPIClient.TryGetVhdxSize(String path)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
   at Docker.Engines.SettingsAdjuster.CopyVhdxSizeAsync(Settings settings)
   at Docker.App.<InitializeAsync>d__12.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 72
   at Docker.App.InitializeAsync(Singletons singletons)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 222
   at Docker.Program.Main(String[] args) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 118
[2022-08-16T08:05:31.407556700Z][IPCServer         ][Info   ] (e5756dc9) 1618e160-ServiceAPI S->C 2b9ff98b-ServiceAPIClient-CSharp GET /version (0ms): OK
[2022-08-16T08:05:31.530947700Z][IPCServer         ][Info   ] (e55e1e75) 1618e160-ServiceAPI S<-C fce279c1-ServiceAPIClient-CSharp GET /hyperv/vhdx-size
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 137
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 31
[2022-08-16T08:05:31.530947700Z][IPCServer         ][Info   ] (e55e1e75) 1618e160-ServiceAPI S->C fce279c1-ServiceAPIClient-CSharp GET /hyperv/vhdx-size (1ms): OK
[2022-08-16T08:05:33.119731700Z][IPCServer         ][Info   ] (eb7459c1) 1618e160-ServiceAPI S<-C cd7fdeb4-ServiceAPIClient-CSharp POST /dns/refresh-hosts
   at Docker.Core.BackendAPI.ServiceAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 0
   at Docker.Core.BackendAPI.ServiceAPIClient.UpdateHostsAsync(CancellationToken cancellationToken)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 101
   at Docker.Engines.WSL2.LinuxWSL2Engine.<SendState>d__35.MoveNext() in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 353
[2022-08-16T08:05:33.208728900Z][IPCServer         ][Info   ] (eb7459c1) 1618e160-ServiceAPI S->C cd7fdeb4-ServiceAPIClient-CSharp POST /dns/refresh-hosts (88ms): OK
```

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/184846784-f2894d92-5787-4bc6-95c2-c481dd530a2e.png)


maybe docker running too fast, I just add an scheduler like: auto start docker after startup 30s and it just work, you can try it like me

**Comment by InfamousUser** [comment]
If it is "running too fast" that is their problem, it's a bug. It happens for me when I only restart Docker, so it cannot have anything to do with other stuff not ready due to recent Windows startup.

**Comment by sdjlsmooks** [comment]
You can diagnose the issue with com.docker.diagnose.exe file in the resources directory.
Mine was in "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"

There is also a log.txt file in your AppData directory (i.e.   c:\users\<username>\AppData\Local\Docker\log.txt).
You may see numbered log files  like log.107.txt, log.108.txt and such   The "log.txt" will be the latest log file being used.

In that file my issue was 
[2022-08-18T23:24:23.832525500Z][GoBackendProcess  ][Info   ] 2022/08/18 17:24:23 notifying bugsnag: exec: "powershell": executable file not found in %PATH%

The docker startup was looking for the powershell executable in the system path.

My local powershell was in 

C:\windows\system32\WindowsPowerShell\v1.0\

I added that entry to the PATH under ControlPanel/System and Security/System/System Properties/Advanced Tab/Environment Variables.   There are 2 choices, one for your current user, the other for "System Variables"  I chose to add the path above to the "System Variables" PATH so it would be seen by all users.

That seemed to work for me.  Though CAVEAT.  My system is currently using a deprecated version of windows and docker reported that warning to me when I rebooted.

**Comment by imranhamid83** [comment]
An update of docker knocked off my docker installation and I could start it in windows mode. After 3 days of struggle I managed to fix it; I was at brink of re-installing windows but following worked for. 

Uninstall Docker
Delete C:\ProgramData\Docker folder with the followings:
C:\Users\YourLoginName\AppData\Roaming\Docker
C:\Users\YourLoginName\AppData\Roaming\DockerDesktop
C:\Users\YourLoginName\AppData\Local\Docker

Re-install docker and it should work
