### ISSUE TITLE
[Last version - 4.12.0 (85629)] Docker Desktop failed to start on Windows

### ISSUE THREAD

**Issue by SirMishaa** [docker/for-win#12978]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 444AB862-4598-4D07-BB79-3A6B59D93B6D/20220923195639

### Information

  - Windows Version: Windows 11 (Version 21H2 (22000.795))
  - Docker Desktop Version: 4.12.0 (85629)
  - WSL2 or Hyper-V backend? WSL 2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, I'm running on my local computer

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
See https://gist.github.com/SirMishaa/84583a2147088d840d4fec9b0954b8fd

### Steps to reproduce the behavior

Update to the latest version. Then it won't be able to start anymore, with the message "Failed to start". 

![image](https://user-images.githubusercontent.com/42717232/192046916-15731692-63b9-4285-a8db-463125741995.png)

**Comment by SirMishaa** [comment]
Please use this issue for update

**Comment by Brightlaz** [comment]
I resolved the issues by enabling virtualization in BIOS for Intel CPU's
Follow this procedures accordingly, it'll resolve your issue;

1. Shutdown your pc 
2. Switch on your pc, while it's starting, press the menu option key or advanced mode button for startup option(On my system, it was the ESC button)
3. Click the advanced tab and select CPU configuration (if missen click on any configuration option seen there)
4. Enable Intel Vitualization Technology (- check the button on my pc) 
5. Click on Exit and dont forget to save your changes before exiting and continuing ur system startup
6. After this your Docker hub will be working just fine, it worked well for me, I had the same issue

**Comment by SirMishaa** [comment]
I'll check if it's not enabled anymore in bios, but I was already using WSL 2 for months and I had already Virtualization Technology enabled on my Ryzen 9 5950X (AMD) for it for months too.

 This come from after the update to the latest version, so this is weird that is related to the virtualization.

**Comment by michalhudecek** [comment]
Same issue here. Docker is completely broken on Windows after the update to v4.12.

**Comment by michalhudecek** [comment]
I also uploaded the diagnostics with ID: 847C0482-3D8D-4CB9-9156-3B73F11239F3/20220927054625

**Comment by stoffpalette** [comment]
After Docker Desktop suddenly failed to start (maybe after an Update of Windows), i stopped Docker, uninstalled Docker, deleted all Docker related Folders inside %AppData% and reinstalled Docker v4.12.0. Windows Pro Version is 21H2 (Build 22000.978 / Windows Feature Experience Pack 1000.22000.978.0).

But Docker still reports "Engine failed to start".

I cant use the Troubleshoot Tools inside Docker (Error).

Therfore I executed `C:\Program Files\Docker\Docker\resources>com.docker.diagnose.exe gather -upload` with the following result:

```
[2022-09-29T09:02:28.909337900Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Gathering diagnostics for ID 25435638-D965-4C57-A4AE-64C514BBA8ED/20220929090228 into C:\Users\root\AppData\Local\Temp\25435638-D965-4C57-A4AE-64C514BBA8ED\20220929090228.zip.
This may take up to 15 minutes.
time="2022-09-29T11:02:28+02:00" level=info msg="Triggering Linux sysrq and log flushes via a unix socket: \\\\.\\pipe\\dockerDiagnosticd" type=unixsock
time="2022-09-29T11:02:28+02:00" level=warning msg="/flush failed: Post \"http://unix/flush\": open \\\\.\\pipe\\dockerDiagnosticd: The system cannot find the file specified." type=unixsock
unable to trigger dns-forwarder diagnostics: Post "http://ipc/diagnostics": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
time="2022-09-29T11:02:35+02:00" level=warning msg="unable to read kubernetes state from settings.json: assuming it is enabled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c1 pc=0xa1de51]

goroutine 9 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.findStringInKMSG({0xaa6ee0?, 0xc000627760?})
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:54 +0x51
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.vmRunning()
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:44 +0x25
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1172f20)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run.func1(0x1172f20)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xa1cb77?, 0x1172f20)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x4, 0x1172f20, 0xc000553ab8)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1173020?, 0xc000553ab8)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x11730a0?, 0xc000553ab8)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1173120?, 0xc000553ab8)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xc00042bab8?, 0xc000553ab8)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce(0xb02340?, 0xc00042bc20)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run(0x11738a0, 0x0?, {0x0, 0x0, 0x0})
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
github.com/docker/pinata/common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1180750)
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.go:32 +0x6e
created by main.gatherCmd
        C:/workspaces/4.12.x/src/github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:247 +0x9bf
```

**Comment by stoffpalette** [comment]
Just tried the following:
Stopped all Docker Tasks
Stopped the Docker Service
Started Docker as normal user

Now a prompt asks for starting the service with administrative permissions - but the same error "Engine failed to start" still occurs.

Then i did the same again, but started Docker with an administrative user - it works.

It seems that there is a problem related to permissions or UAC - at least with the current Windows 11 Version.

**Comment by SirMishaa** [comment]
The solution proposed by stoffpalette doesn't work for me. 

I uninstalled Docker and went back to version [4.11.1](https://docs.docker.com/desktop/release-notes/#docker-desktop-4111), it works perfectly with that and I haven't lost my images or volumes.

After the rollback, you may have the message : "Failed to stop" when trying to start Docker 4.11.1, if it's the case, run the following command : 
```
wslconfig.exe /u docker-desktop
```
Then, you can kill / stop docker and restart it. Everything should work.
(Don't worry, it shouldn't remove your volumes / images)

I **suggest you do this** while waiting for one of the Docker developers to deign to answer us. 

They must be very busy, as I have seen 15+ issues on the same problem and no one seems to respond or even offer a fix. Or maybe they just don't like Windows 😅.

**Comment by stoffpalette** [comment]
@SirMishaa Thanks for the hint about the "Failed to stop" message.

**Comment by stoffpalette** [comment]
If you are using Docker in conjunction with WSL2 another alternative is to install Docker inside the WSL virtual machine.

I am using Docker for Laravel-Development with Sail and just installed docker inside the Ubuntu Virtual machine.

It works, even with VSCode. Just had to recreate the database and tables and seed them.

[How to install Docker on Linux Ubuntu](https://docs.docker.com/engine/install/ubuntu/)

**Comment by cristiandeschamps** [comment]
Nothing worked for me, what finally worked is I started the [4.11.1](https://docs.docker.com/desktop/release-notes/#docker-desktop-4111) installation using the right click and run as administrator. Then I installed the 4.12 right after (no reboot) the same way (run as administrator) and it worked!

before the installation I made sure to delete the AppData\Local\Docker and AppData\Roaming\Docker folder.

**Comment by stoffpalette** [comment]
@SirMishaa 
> wslconfig.exe /u docker-desktop

Does not work for me. At least not with a normal user with no admin permissions.

**Comment by phiberoptick** [comment]
Try restarting the "LxssManager" service.  That seemed to get it to start for me.  It took a min the first time after restarting the service but I've had no issues since and Docker Desktop seems to start fine on it's own again.

**Comment by stoffpalette** [comment]
@phiberoptick a reboot does not help - so i don't think this solution will solve the problem for me?

**Comment by franmako** [comment]
> I uninstalled Docker and **went back to version [4.11.1](https://docs.docker.com/desktop/release-notes/#docker-desktop-4111)**, it works perfectly with that and I haven't lost my images or volumes.
> 
> After the rollback, you may have the message : "Failed to stop" when trying to start Docker 4.11.1, if it's the case, run the following command :
> 
> ```
> wslconfig.exe /u docker-desktop
> ```
> 
> Then, you can kill / stop docker and restart it. Everything should work. (Don't worry, it shouldn't remove your volumes / images)
> 

This doesn't work for me. When restarting Docker desktop after downgrading & running the wslconfig.exe /u docker-desktop. Docker desktop stays in the starting state and I get this error message.
![image](https://user-images.githubusercontent.com/7797468/194768368-e367133a-2d7c-4466-96ad-8d356a0e2c58.png)

**Comment by franmako** [comment]
The issue seems to have been resolved with the latest windows 11 update (KB5018427). There was also a WSL update to the kernel version 5.10.102.2. And I did a wsl --update after the windows updates. Docker Desktop is now working again on version 4.12

**Comment by stoffpalette** [comment]
@franmako: I already have this update installed. Still not getting it work with any of the proposed solutions.

**Comment by david-engelmann** [comment]
@stoffpalette [I was able to find a solution and documented in this comment](https://github.com/docker/for-win/issues/13020#issuecomment-1283055393)

**Comment by david-engelmann** [comment]
[Updated approach to try before uninstalling your main wsl distro](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765)
