### ISSUE TITLE
Multiple issues with wsl and daemon of Docker Desktop 4.16.3 Windows

### ISSUE THREAD

**Issue by BletaJonatan** [docker/for-win#13240]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: i currently cannot afford a pro subscription

------------------------------------------------------------------------------------------------------------------------------------------------

### Actual behavior
In "windows container mode" docker loads but when executing `docker run -d -p 80:80 docker/getting-started` in cmd as admin it gives me this error: ` docker: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.`

ok so just switch mode, i hear you say, but other problem arise when switching to "linux container mode".
when switching to linux container docker hangs, and after a few minutes a window with this error appears:

Docker.Core.HttpBadResponseException:
{"message":"2 errors occurred:\n\t* provisioning docker WSL distros: deploying \"docker-desktop\": importing WSL distro \"docker-desktop\": deploying WSL distro \"docker-desktop\" (\"C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\wsl\\\\wsl-bootstrap.tar\" -\u003e \"C:\\\\Users\\\\Jonatan\\\\AppData\\\\Local\\\\Docker\\\\wsl\\\\distro\"): exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

   in Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:riga 226
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:riga 54
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:riga 29
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:riga 91
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:riga 118
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:riga 72
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.Engines.Engines.<SwitchDaemonAsync>d__28.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:riga 267
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in Docker.Engines.Engines.<SwitchDaemonAsync>d__28.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:riga 288
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.Services.DesktopService.<SwitchDaemonAsync>d__4.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Services\DesktopService.cs:riga 39

closing the window and focusing on docker changes nothing, it will stay with "engine starting" indefinitely.

------------------------------------------------------------------------------------------------------------------------------------------------

### Expected behavior
Docker running on both wsl-2 and hyper-v, docker running in windows container mode or/and in linux container mode

------------------------------------------------------------------------------------------------------------------------------------------------

### Information

  - Windows Version: `Windows 10 Pro 64bit 22H2 (build SO 19045.2546)`
  - Docker Desktop Version: `Docker Desktop 4.16.3 (96739)`
  - WSL2 or Hyper-V backend? 
    Tried with both, the issue persists
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:
    No, running it on my home Desktop
  - I have already installed and uninstalled docker multiple times, while also trying older versions suggesting it either a compatibility 
    issue or something's wrong with my machine
  - I have also tried using `wsl --shutdown` and `netsh winsock reset` after but it didn't solve the issue
  - `wsl -l -v` doesn't show anything
  - wsl was already updated 
  - deleting folders didn't fix anything

------------------------------------------------------------------------------------------------------------------------------------------------

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[2023-02-12T12:17:39.835076700Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[FAIL] DD0001: is the application running? Docker is not running
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-02-12T12:17:40.540223700Z][com.docker.diagnose.exe][I] ipc.NewClient: b839872b-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1bdb440)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1bdb440)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x1bdb440)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1bdb440, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1bdb4c0, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1bdb540, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1bdbcc0, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x156e8a0?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1bdbcc0, 0x4a323db800000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000603d0?, 0xc0000603d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-12T12:17:40.540223700Z][com.docker.diagnose.exe][I] (dac97a61) b839872b-diagnose C->S diagnosticsd GET /ping
[2023-02-12T12:17:40.541223100Z][com.docker.diagnose.exe][W] (dac97a61) b839872b-diagnose C<-S NoResponse GET /ping (999.4µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[PASS] DD0023: is the Containers Windows Feature enabled?
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:41.064677800Z][com.docker.diagnose.exe][I] ipc.NewClient: 77630f26-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:63
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x1633bdc, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:57 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1bdb4c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1bdb4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x1bdb4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1bdb4c0, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1bdb540, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1bdbcc0, 0xc00061f728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x156e8a0?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1bdbcc0, 0x4a323db800000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000603d0?, 0xc0000603d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-12T12:17:41.065198000Z][com.docker.diagnose.exe][I] (94798bab) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-02-12T12:17:41.065709800Z][com.docker.diagnose.exe][W] (94798bab) 77630f26-com.docker.diagnose C<-S NoResponse GET /docker (511.8µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:41.065709800Z][com.docker.diagnose.exe][I] (94798bab-1) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:41.065709800Z][com.docker.diagnose.exe][W] (94798bab-1) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:42.071856400Z][com.docker.diagnose.exe][I] (94798bab-2) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:42.072367900Z][com.docker.diagnose.exe][W] (94798bab-2) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:43.079117600Z][com.docker.diagnose.exe][I] (94798bab-3) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:43.079117600Z][com.docker.diagnose.exe][W] (94798bab-3) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:44.082386300Z][com.docker.diagnose.exe][I] (94798bab-4) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:44.082386300Z][com.docker.diagnose.exe][W] (94798bab-4) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:45.088429500Z][com.docker.diagnose.exe][I] (94798bab-5) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:45.089486600Z][com.docker.diagnose.exe][W] (94798bab-5) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (537.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:46.105208900Z][com.docker.diagnose.exe][I] (94798bab-6) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:46.105208900Z][com.docker.diagnose.exe][W] (94798bab-6) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:47.120712300Z][com.docker.diagnose.exe][I] (94798bab-7) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:47.120912700Z][com.docker.diagnose.exe][W] (94798bab-7) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (200.4µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-12T12:17:48.135869600Z][com.docker.diagnose.exe][I] (94798bab-8) 77630f26-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-12T12:17:48.135869600Z][com.docker.diagnose.exe][W] (94798bab-8) 77630f26-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[FAIL] DD0038: is the connection to Docker working? HTTP GET https://login.docker.com: Get "https://login.docker.com": proxyconnect tcp: open \\.\pipe\dockerHTTPProxy: The system cannot find the file specified.
2023/02/12 13:17:48 exit status 0xffffffff

------------------------------------------------------------------------------------------------------------------------------------------------

### Steps to reproduce the behaviour

as far as i can tell knowing the steps to these issues would have allowed me to resolve it already, the issue also seems spread to multiple users.

**Comment by JoannaFalkowska** [comment]
I have a very similar issue. I'm on 4.16.3 (96739) on Windows 10. 

After restarting my PC, Docker initially claims that it started fine and shows the welcome screen, but then after a short while it errors out and shows "failed to start". Restarting Docker gives the same result.

Error message shown in a pop-up:
```
Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* starting WSL integration service: synchronising agents: starting added distros: 1 error occurred:\n\t* waiting for WSL integration for Ubuntu: timed out while polling for WSL distro integration to become ready in \"Ubuntu\"\n\n\n\n"}

   w Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:wiersz 226
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:wiersz 54
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:wiersz 29
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:wiersz 91
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:wiersz 118
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:wiersz 72
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Docker.Engines.Engines.<StartAsync>d__23.MoveNext() w C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:wiersz 109
```

Diagnostics:

```
C:\Program Files>Docker\Docker\resources\com.docker.diagnose.exe check
[2023-02-14T09:48:30.962666800Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-02-14T09:48:36.021561000Z][com.docker.diagnose.exe][I] ipc.NewClient: 2ffce28a-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x169b440)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x169b440)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x169b440)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x169b440, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x169b4c0, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x169b540, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x169bcc0, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x102e8a0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x169bcc0, 0x4ef184e900000010?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000423f0?, 0xc0000423f0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-14T09:48:36.022079900Z][com.docker.diagnose.exe][I] (77a1dac0) 2ffce28a-diagnose C->S diagnosticsd GET /ping
[2023-02-14T09:48:36.022079900Z][com.docker.diagnose.exe][W] (77a1dac0) 2ffce28a-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:36.024740500Z][com.docker.diagnose.exe][I] ipc.NewClient: ae68ad1f-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:63
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x10f3bdc, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:57 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x169b4c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x169b4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x169b4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x169b4c0, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x169b540, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x169bcc0, 0xc0002c1728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x102e8a0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x169bcc0, 0x4ef184e900000010?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000423f0?, 0xc0000423f0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-14T09:48:36.024740500Z][com.docker.diagnose.exe][I] (d007e172) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-02-14T09:48:36.025262300Z][com.docker.diagnose.exe][W] (d007e172) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /docker (521.8µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:36.026340300Z][com.docker.diagnose.exe][I] (d007e172-1) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:36.026340300Z][com.docker.diagnose.exe][W] (d007e172-1) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:37.037960900Z][com.docker.diagnose.exe][I] (d007e172-2) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:37.038483600Z][com.docker.diagnose.exe][W] (d007e172-2) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (504.1µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:38.052838500Z][com.docker.diagnose.exe][I] (d007e172-3) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:38.053936200Z][com.docker.diagnose.exe][W] (d007e172-3) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (1.0977ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:39.055312300Z][com.docker.diagnose.exe][I] (d007e172-4) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:39.055817800Z][com.docker.diagnose.exe][W] (d007e172-4) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:40.057366100Z][com.docker.diagnose.exe][I] (d007e172-5) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:40.057366100Z][com.docker.diagnose.exe][W] (d007e172-5) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:41.060149500Z][com.docker.diagnose.exe][I] (d007e172-6) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:41.060656000Z][com.docker.diagnose.exe][W] (d007e172-6) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (506.5µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:42.072990500Z][com.docker.diagnose.exe][I] (d007e172-7) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:42.073494700Z][com.docker.diagnose.exe][W] (d007e172-7) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (504.2µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-14T09:48:43.084839800Z][com.docker.diagnose.exe][I] (d007e172-8) ae68ad1f-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-14T09:48:43.085974100Z][com.docker.diagnose.exe][W] (d007e172-8) ae68ad1f-com.docker.diagnose C<-S NoResponse GET /ping (1.1343ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[WARN] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[WARN] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[WARN] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.
```

---

(Personally, I appreciate the efforts to fix it, but something about 4.16 seems to be truly cursed. I'm surprised it wasn't at least partially rolled back.)

**Comment by BletaJonatan** [comment]
i understand, the problem is even docker 4.13 doesn't work on my machine, and even though there may seem to be a problem with my installation of windows the error i encountered when downgrading where the same of other users who also downgraded, so as i thought it seems something internal of docker.

**Comment by gnjoseph** [comment]
I am also unable to install and run docker on my machine anymore, it just disables my WSL2.

**Comment by yodayuuki55** [comment]
https://github.com/docker/for-win/issues/13236#issuecomment-1426275262
I think you can try it, i fixed the same issue just now.

**Comment by BletaJonatan** [comment]
> [#13236 (comment)](https://github.com/docker/for-win/issues/13236#issuecomment-1426275262) I think you can try it, i fixed the same issue just now.

Thanks for trying, but I have already written in my issue that trying netsh winsock reset didn't fix the issue, whatever is on the internet I have already done it, this is something docker itself has to fix.

**Comment by BletaJonatan** [comment]
Can anyone on the developers team take a look at my logs?

**Comment by p1-0tr** [comment]
@BletaJonatan thanks for reporting your issue and sorry for the inconvenience. The error you get means that WSL is unable to deploy one of the distros needed by DD to run. Unfortunately the error we get is not very informative, so it is hard to say for sure what problem it is encountering, but the most common are permissions, but I guess it could also be disk space related.

Out of curiosity, are you able to run any WSL distros? E.g. to install Debian you can do `wsl --install -d Debian`.

Also to generate diagnostics you do not need to have any subscriptions. Here are docs https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal on the topic. A full diagnostic may give us some more pointers as to what is going wrong.

**Comment by BletaJonatan** [comment]
Thank you for taking a look at my issue, while running `wsl --install -d Debian` i get the error: 

Error during installation. Distro name: 'Debian GNU/Linux' Error code: 0x80072ee7

Also i already ran and added `"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check` at the end of my issue.
I did try to run `C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe gather -upload` and the result was this:

C:\Program Files\Docker\Docker\resources>com.docker.diagnose.exe gather -upload
[2023-02-21T14:25:27.029689300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Gathering diagnostics for ID C69D8147-9325-49A2-A791-41F43E8AFB3A/20230221142527 into C:\Users\Jonatan\AppData\Local\Temp\C69D8147-9325-49A2-A791-41F43E8AFB3A\20230221142527.zip.
This may take up to 15 minutes.
time="2023-02-21T15:25:27+01:00" level=info msg="Triggering Linux sysrq and log flushes via a unix socket: \\\\.\\pipe\\dockerDiagnosticd" type=unixsock
time="2023-02-21T15:25:27+01:00" level=warning msg="/flush failed: Post \"http://unix/flush\": open \\\\.\\pipe\\dockerDiagnosticd: The system cannot find the file specified." type=unixsock
unable to trigger dns-forwarder diagnostics: Post "http://ipc/diagnostics": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
time="2023-02-21T15:25:34+01:00" level=info msg="unable to query WSL distros: exit status 0xffffffff"
time="2023-02-21T15:25:34+01:00" level=info msg="Start gathering list of 123 elements (timeout=15m0s)" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering DiagKit" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering BackendGatherer" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering ProxyAPIGatherer" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering LifecycleServerGatherer" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering DiagKit took 1.6746ms" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Gathering system" type=list
time="2023-02-21T15:25:34+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_OperatingSystem) | ConvertTo-json -Depth 1 }]"
time="2023-02-21T15:25:34+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_ComputerSystem) | ConvertTo-json -Depth 1 }]"
time="2023-02-21T15:25:34+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_Processor) | ConvertTo-json -Depth 1 }]"
time="2023-02-21T15:25:36+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_BaseBoard) | ConvertTo-json -Depth 1 }]"
time="2023-02-21T15:25:36+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ Get-Item 'Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion' }]"
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
2023/02/21 15:25:37 exit status 0xffffffff

i would guess the id is this: C69D8147-9325-49A2-A791-41F43E8AFB3A/20230221142527

**Comment by p1-0tr** [comment]
> i would guess the id is this: C69D8147-9325-49A2-A791-41F43E8AFB3A/20230221142527

Yup, that is it, unfortunately it does not seem to have uploaded. But considering that WSL refuses to install a regular distro, the information from the diagnostic is probably less important, for now. Hopefully, instructions found here - https://learn.microsoft.com/en-us/windows/wsl/install - should help you get WSL working (failing that, I believe WSL issues are tracked here - https://github.com/microsoft/WSL).

Once your WSL installation is working could you reinstall DD and let me know how it goes?

**Comment by BletaJonatan** [comment]
Trying `wsl` in cmd gives me a response so i guess it works, now trying to update it (i have already updated, done everything regarding it on the microsoft website and set wsl 2 and it worked, i just decided to update again just for fun) gives me a error like last time so maybe it's something in my windows installation blocking certain connections/something just broken?
I don't know how an error with windows update function could possibly f* up my docker installation or if it even could/does.

I uninstalled docker, restarted the pc and reinstalled it again and every single issue appears once again, is there truly nothing in the multiple logs i provided that could hint at the issue or issues at play now?

**Comment by p1-0tr** [comment]
@BletaJonatan as I mentioned previously, the diagnostics bundle did not get uploaded correctly (this can happen e.g. if you are behind a proxy that for some reason blocks the upload). So there is not that much to go on, aside form the information that DD is unable to deploy a WSL distro and that you were not able to install a regular WSL distro from the MS store. So my best guess is that WSL is not functioning correctly, DD uses WSL, so it won't be able to function, in turn.

Could you confirm for me that you are able to install and run e.g. debian for WSL?

    wsl --install -d Debian
    wsl -d Debian -e uname -a

If that succeeds could you make sure that `%userprofile%\Local\Docker\wsl\distro` exists and run:
    
    wsl --import docker-desktop "C:\Program Files\Docker\Docker\resources\wsl\wsl-bootstrap.tar" "%userprofile%\Local\Docker\wsl\distro"

(if you've still got DD installed `C:\Program Files\Docker\Docker\resources\wsl\wsl-bootstrap.tar` should exist). This is the command that DD is failing on in your original report, and it should produce some more informative output on stderr as to why the operation fails.

**Comment by BletaJonatan** [comment]
ok so i MIGHT have found a universal fix for everyone who got this set of errors as me and it might help you guys too, now:
1) try to do every single fix in my issue and every comment regarding my issue.
2) install `Windows Repair from Tweaking.com` and open it, reboot in safe mode through the program and after having rebooted in safe mode run every single steps the app tells you too, after it finishes the pc will reboot as normal.
3) run `wsl --update` again and then try opening Docker Desktop.

As i thought it was probably a problem with Windows 10 itself, or maybe it was only an issue with either the 22H2 update, the microsoft store apps so also the windows update function or something else entirely.  

As of now docker seems to run in wsl mode, Hyper-v mode and in both windows and linux containers, i might need to start using it more extensively to know if it truly works as it should but as far as i can see everything works correctly :D .

**Comment by ibrahimnabil2001** [comment]
I had similar issues and all was resolved after updating windows.
that simple :)
