### ISSUE TITLE
Docker Desktop doesn't start.

### ISSUE THREAD

**Issue by fabriziodsp-ransom** [docker/for-win#13264]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 884AB42C-B5F9-434A-AF49-0AA527C306C6/20230226220041

### Actual behavior
Docker Desktop app doesn't start. Tried using the CLI and also didn't work. Error response from daemon: open \\.\pipe\docker_engine_linux
### Expected behavior
Docker Desktop to start normally.
### Information
**How to reproduce:** Open Docker Desktop or type in the CLI `docker ps`.
**Is the problem new?**: No, according to previous tickets, this is pretty much common.
**Did the problem appear with an update?**: It's the second time in my entire life that I use Docker. No.
**Windows Version:** v4.16.3
**WSL2**
**Are you running inside a virtualized Windows e.g. on a cloud server or a VM:** No

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Please investigate the following 1 issue:

1 : The test: is the WSL 2 Linux filesystem corrupt?
    Failed with: [  453.693257] EXT4-fs error (device sdf): ext4_journal_check_start:83: Detected aborted journal

**Comment by sam-thibault** [comment]
We have just released 4.17.0 that contains several fixes around the WSL integration.  Can you try the latest version?
Release notes (and links to installers) here: https://docs.docker.com/desktop/release-notes/

**Comment by fabriziodsp-ransom** [comment]
Hey! Thanks for the heads-up. For sure, will update later. Not closing until then.

**Comment by ntx-ben** [comment]
I've just upgraded from 4.15 to 4.17 and am still encountering the issue. I've reported this initially here: https://github.com/docker/compose/issues/9956#issuecomment-1450262074

**Comment by yilmazdurmaz** [comment]
please run `"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check` as asked in the issue template and add its result.

then also use `docker context ls` and add its output too.

**Comment by ntx-ben** [comment]
> please run `"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check` as asked in the issue template and add its result.
> 
> then also use `docker context ls` and add its output too.

Please find the full diagnostics below:

```
> & 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' check
[2023-03-01T23:40:52.832625400Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[FAIL] DD0004: is the Docker engine running? docker engine is still starting, waiting for internal network to respond for 3m56.241875514s
[2023-03-01T23:40:57.107571100Z][com.docker.diagnose.exe][I] ipc.NewClient: 4e600537-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-03-01T23:40:57.107571100Z][com.docker.diagnose.exe][I] (74166927) 4e600537-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-03-01T23:40:57.110792100Z][com.docker.diagnose.exe][I] (74166927) 4e600537-com.docker.diagnose C<-S 69c3ef5b-VMDockerdAPI GET /docker (2.6952ms): {"current_action":"waiting for internal network to respond","current_action_start":"2023-03-01T23:37:00.868916586Z","engine":"starting","error":""}

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[PASS] DD0013: is the $PATH ok?
Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0011: are the LinuxKit services running?
[WARN] DD0004: is the Docker engine running? docker engine is still starting, waiting for internal network to respond for 3m56.241875514s
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory
[WARN] DD0032: do Docker networks overlap with host IPs? Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory

Please note the following 3 warnings:

1 : The check: is the Docker engine running?
    Produced the following warning: docker engine is still starting, waiting for internal network to respond for 3m56.241875514s

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

2 : The check: does the Docker API work?
    Produced the following warning: Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory

If the Docker API is not available from the host then Docker Desktop will not work correctly.

3 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: Error response from daemon: dial unix /run/guest-services/docker.sock: connect: no such file or directory

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address


Please investigate the following 1 issue:

1 : The test: is the Docker engine running?
    Failed with: docker engine is still starting, waiting for internal network to respond for 3m56.241875514s

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.
```

Please find the result of `docker context ls` below:

```
docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                             KUBERNETES ENDPOINT                  ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine              https://10.0.14.180:6443 (default)   swarm
desktop-linux       moby                                                          npipe:////./pipe/dockerDesktopLinuxEngine
```

**Comment by yilmazdurmaz** [comment]
this one is different than what we were discussing in issue 9956. your context files are fine.
have you tried to restart your host pc? or check if Windows Defender/Security gave any warning/error? sometimes, a side effect of updates for all kinds of programs, having the same name/path but new content can cause extra headaches in the operating system itself. 

open `%USERPROFILE%\AppData\Local\Docker\log\vm\` and delete all logs in it (maybe make a backup). then check `dockerd.log` if you can spot something useful. if not, try to check if it has sensitive information in it, make redactions, and attach it here.

**Comment by Trey-Daviz** [comment]
Hey guys!  I am having the same issue.  I was hoping the upgrade to 4.17.0 would be the fix, but I have the same issues still.  It is forever stuck in the "Docker Starting" phase.  I have tried at least 10 different fixes from 10 different people with this issue but no dice.

**Comment by fabriziodsp-ransom** [comment]
Upgrading to the latest version solved my issue. I will create another ticket if needed. But until then: Thank you so much!
PS: I recommend to keep investigating about the folks that kept commenting that upgrading wasn't their solution.
Thanks!

**Comment by AshuOPragmatikosThrylos** [comment]
Issue persists even with 4.17.0

**Comment by AshuOPragmatikosThrylos** [comment]
@sam-thibault

**Comment by AshuOPragmatikosThrylos** [comment]
I am trying to install docker for the first time

**Comment by TABAENE** [comment]
Hi @yilmazdurmaz,
I am also getting this exact same issue which @ntx-ben @AshuOPragmatikosThrylos reported here. I tried multiple solution like installing/uninstalling 4.17.0 then went back to docker earlier release 4.12.0 but nothing worked.

**Comment by yilmazdurmaz** [comment]
> I am trying to install docker for the first time

The very first line in the error stack present a problem with WSL engine. And first install may relate to WSL more closely. so lets check it out. I see a few hint similarity to https://github.com/docker/for-win/issues/5256, but I am not sure. can you give it a shot? Although that problem was fixed at its time, underlying problem might still exist in WSL itself.

the problem might be in the WSL itself or in Hyper-V. it might not be set correctly. try `wsl -l -v`. you should see one similar to this (I keep docker off while not coding):
````
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop         Stopped         2
  Ubuntu-22.04           Stopped         2
  docker-desktop-data    Stopped         2
````
version 2 is WSL2 and it does not use Hyper-V. so if you have it enabled, it can prevent WSL2 to start.

**Comment by LeviPesin** [comment]
I also have the same problem. `wsl -l -v` produces:
```
   NAME                   STATE           VERSION                                                                       
 * Ubuntu-18.04           Stopped         2                                                                              
   docker-desktop         Running         2                                                                             
   docker-desktop-data    Running         2
```
Not sure why they are marked as "Running"...

**Comment by LeviPesin** [comment]
Seems like `netsh winsock reset` indeed resolves the issue!!!
