### ISSUE TITLE
Unsigned update for 4.21.0

### ISSUE THREAD

**Issue by Tom01098** [docker/for-win#13574]
### Description

When updating to 4.21.0, I am shown an admin prompt that warns the update is from an unknown publisher.

### Reproduce

1. Be on version 4.20.1 (110738) of Docker Desktop on Windows.
2. Update and restart for version 4.21.0 (113844).
3. The admin prompt reports that the update is from an unknown publisher. Previous updates have shown 'Docker, Inc'.

### Expected behavior

The update should be signed by Docker.

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 28
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 15.58GiB
 Name: docker-desktop
 ID: 0b8000f2-aa82-4609-a8b4-d615ee9be45f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Diagnostics ID

4036A451-A9DE-4A6B-AB96-CBEB9580AC35/20230701093956

**Comment by lorenrh** [comment]
Thanks for the report! I've escalated this internally and we are looking into it.

**Comment by lorenrh** [comment]
Hi! We've released a new version, and we've signed the binaries! Please let us know if you encounter this again, I'll close the issue for the time being.

**Comment by Crissante** [comment]
This is still occurring when updating from 4.20.1 to 4.21.1, is this expected @lorenrh?

**Comment by Tom01098** [comment]
@lorenrh Unfortunately as @Crissante points out above, this is still the case for me when attempting to update to 4.21.1 (114176).

**Comment by PrimeDominus** [comment]
+1 for still occurring @lorenrh

**Comment by bsousaa** [comment]
This should be fixed now. Can you please confirm? Thanks!

**Comment by Tom01098** [comment]
Hi @bsousaa, this now works for me. Thanks!

**Comment by Crissante** [comment]
The issue is fixed! Thanks @bsousaa!

**Comment by flybyray** [comment]
Might not be fixed for the update mechanism from `Docker Desktop` itself.

In this case a file is downloaded in the background to the location e.g. `%USERPROFILE%\AppData\Local\Docker Desktop Installer\update-1045309798.exe` 

[Check the 'update-1045309798.exe' details on virustotal 'Signature Verification: File is not signed'](https://www.virustotal.com/gui/file/04741304d2ae64cfffb3bbeb7de0936480cfff34465a92ae33ead11bdcbc369b/details)

And now compare it to the full installer downloaded manually: [Check the 'Docker Desktop Installer.exe' details on virustotal 'Signature Verification: Signed file, valid signature'](https://www.virustotal.com/gui/file/7d7e81a9f8273b1c404201eccf04ef67a26bbad85805d246007e9e7bc80ddd74/details)

**Comment by PrimeDominus** [comment]
What @flybyray has described is what I'm experiencing.

**Comment by lorenrh** [comment]
Thanks for your report!

We had an issue signing binaries, we have fixed the issue. If you still encounter it, you might need to delete the update that was downloaded y with
```
Get-bitstransfer –allusers | remove-bitstransfer
```
Then restart Docker Desktop, and try the update again.

**Comment by JoKneeMo** [comment]
I just got the update this morning and had the same issue.
Given the permission levels that Docker Desktop is ran at, I'm not trusting an unsigned update.
I was able to download the full version (that was signed) and update from it.
