### ISSUE TITLE
After updating to versions 4.22.0 and 4.22.1, Docker fails to start.

### ISSUE THREAD

**Issue by hualinli** [docker/for-win#13662]
### Description

The system is running the latest version of Windows 11. After upgrading from version 4.21.1 to 4.22.0 and subsequent versions, Docker hangs at the "Starting Engine" screen and eventually stops. However, if I uninstall the updated version and reinstall version 4.21.1, Docker can start normally.

### Reproduce

Download and install the latest version of Docker Desktop.

### Expected behavior

Docker is working properly.

### docker version

```bash
❯ docker version
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### docker info

```bash
❯ docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

508C3D9F-76AE-4AE9-969B-102C65753FA7/20230828134303

### Additional Info

Here is the output of the diagnose:

Please investigate the following 2 issues:

1 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The test: is the Docker API proxy responding?
    Failed with: failed to ping Docker proxy API with error: Get "http://ipc/desktop-diagnostics/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.

The Docker API proxy is needed to forward commands to Docker engine.

**Comment by dwissaaj** [comment]
Hey I also have this issue, i force to downgrade to version `4.21.0`
![Failed to run docker](https://github.com/docker/for-win/assets/71976179/37c9870d-81f2-483c-ad90-8f553736c75d)

**Comment by bsousaa** [comment]
@dwissaaj can you share a diagnostics id?

**Comment by returnL** [comment]
I had this problem too, downgraded to version 4.21.0 and back to normal
diagnostics id `B6DFC9F1-1B89-409F-8F47-BFD48E190372/20230829150011`

**Comment by ctalledo** [comment]
Hi @hualinli, @returnL, @dwissaaj,

Sorry to hear about the problem and thanks for reporting it.

We have a [DD 4.23 preview build](https://desktop-stage.docker.com/win/main/amd64/119233/Docker%20Desktop%20Installer.exe) that we think addresses the problem. When you have a chance, could you give it a try and let us know please.

Thanks again!

**Comment by hualinli** [comment]
Hi @ctalledo, I'm glad to receive your reply. I have installed the new version as quickly as possible. My issue has been resolved. Thank you very much for your assistance.

**Comment by ctalledo** [comment]
Thanks @hualinli for replying so quickly, that's very good to hear that it fixed the problem. Thanks for using Docker!

**Comment by returnL** [comment]
@ctalledo Thanks for your reply.
I upgraded from 4.21 to 4.23 and this problem still exists. 
diagnostics id `25F44B9D-0313-4664-9FA3-B1773BC59AD4/20230831024559`

**Comment by ctalledo** [comment]
Hi @returnL, thanks for your reply and for trying the v4.23 build. I can see from the diagnosis bundle that the issue reoccurs. Let us fix it and get back to you.

Thanks again!

**Comment by WankkoRee** [comment]
same issue after I upgraded from 4.21 to 4.22/4.23, my Diagnostics ID is `2460963B-F5C0-48DD-B92B-234C34C43AE3/20230903045645`.

**Comment by ococl** [comment]
same issue, my diagnostics id is: `36752F43-0090-46EC-A0DC-F8BDEFA40544/20230907071155`

**Comment by JeroenTekle** [comment]
Same issue, 4.22.1 Diagnostics ID: `C144F1CB-2CCF-4576-8822-272DB15E3646/20230908084123` and 4.23 Diagnostics ID: `C144F1CB-2CCF-4576-8822-272DB15E3646/20230908084827`

**Comment by ctalledo** [comment]
Thanks @WankkoRee, @ymind, and @JeroenTekle for reporting.

@JeroenTekle: in your case the symptom looks similar (Docker Desktop on WSL fails), but the underlying problem is different as I see this error message in the logs:

```
 WSLKeepAlive: running wsl-keepalive in "docker-desktop-data": WSL engine terminated abruptly
```

We are investigating. Thanks again for your patience.

**Comment by ziben** [comment]
same issue:    CC408C7F-49DB-4FCA-80A7-BD66546FBA39/20230913004019

**Comment by ococl** [comment]
4.23.0: 0C57CFA4-6512-45CB-B5B7-78BDAAC0B1E6/20230913064935

**Comment by ctalledo** [comment]
Hi folks, 

I think I've found the problem and fixed it (apologies again for the inconvenience). 

In case you want to try it, here's a patched Docker Desktop build (120989):

* [Docker Desktop v4.24 Preview Build](https://desktop-stage.docker.com/win/main/amd64/120989/Docker%20Desktop%20Installer.exe)

Please let me know if that fixes it. Thanks!

**Comment by WankkoRee** [comment]
@ctalledo Thank you very much. I installed `v4.24`, and it fixed the issue as expected.

![image](https://github.com/docker/for-win/assets/21287731/142240f6-6db2-43ef-98ab-f09159e2d472)

**Comment by returnL** [comment]
@ctalledo Thank you very much. This issue has been fixed in version 4.24 and it's working fine on my computer.

**Comment by ococl** [comment]
@ctalledo Thank you very much! Version 4.24 works fine!

**Comment by Aeonbrk** [comment]
@ctalledo  It works fine! on my computer -> win11 build 23545.1000

**Comment by ctalledo** [comment]
Thanks you @WankkoRee, @returnL, @ymind, and @Aeonbrk for confirming the fix works. It will be present in the upcoming 4.24 release. I'll keep this issue open until then. Thanks again for reporting the problem and apologies for the inconvenience.

**Comment by boellner** [comment]
4.24 didnt work for me, win 11 Version	10.0.22621 Build 22621

**Comment by ctalledo** [comment]
> 4.24 didnt work for me, win 11 Version 10.0.22621 Build 22621

Hi @boellner, could you please upload a [diagnosis bundle](https://docs.docker.com/desktop/troubleshoot/overview/) so we can investigate.

Thanks!

**Comment by onlyLTY** [comment]
> 嗨伙计，
> 
> 我想我已经找到了问题并解决了它（对于给您带来的不便再次表示歉意）。
> 
> 如果您想尝试一下，这里有一个修补过的 Docker Desktop 版本 (120989)：
> 
> * [Docker Desktop v4.24 预览版](https://desktop-stage.docker.com/win/main/amd64/120989/Docker%20Desktop%20Installer.exe)
> 
> 请告诉我是否可以解决问题。谢谢！

版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎9/‎2
操作系统版本	22631.2338
体验	Windows Feature Experience Pack 1000.22674.1000.0
在我的系统上有用，非常感谢

**Comment by Matteotti** [comment]
> Hi folks,
> 
> I think I've found the problem and fixed it (apologies again for the inconvenience).
> 
> In case you want to try it, here's a patched Docker Desktop build (120989):
> 
> * [Docker Desktop v4.24 Preview Build](https://desktop-stage.docker.com/win/main/amd64/120989/Docker%20Desktop%20Installer.exe)
> 
> Please let me know if that fixes it. Thanks!

This update resolves the same issue that was also occurring on my Windows 10 22H2 system. The Diagnostic ID for this issue is 65AB4234-4F5C-461E-90A7-4FB87B4B8D2C/20230922024049. Thanks a lot!

**Comment by PaszaVonPomiot** [comment]
For me on Win10 updating from 4.23 to 4.24 didn't help but after running diagnostics I noticed some connection error. So I disabled TinyWall (firewall) during Docker startup and the problem was resolved.

```
[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[SKIP] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[SKIP] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[2023-09-26T00:28:24.651886700Z][com.docker.diagnose.exe.ipc][I] ipc.NewClient: 04726d62-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-09-26T00:28:24.652449400Z][com.docker.diagnose.exe.ipc][I] (ad4f4d8b) 04726d62-diagnose C->S diagnosticsd GET /ping
[2023-09-26T00:28:25.663096000Z][com.docker.diagnose.exe.ipc][W] (ad4f4d8b) 04726d62-diagnose C<-S NoResponse GET /ping (1.0106466s): Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[FAIL] DD0004: is the Docker engine running? prereq failed: are the LinuxKit services running?
[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? prereq failed: is the Docker engine running?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0003: is the Docker CLI working? prereq failed: is the Docker engine running?
[PASS] DD0005: is the user in the docker-users group?
[FAIL] DD0038: is the connection to Docker working? prereq failed: is the Docker engine running?
[PASS] DD0014: are the backend processes running?
[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[SKIP] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[SKIP] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0030: is the image access management authorized? prereq failed: is the Docker engine running?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[WARN] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[WARN] DD0004: is the Docker engine running? prereq failed: are the LinuxKit services running?
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? prereq failed: is the Docker engine running?
[WARN] DD0032: do Docker networks overlap with host IPs? prereq failed: does the Docker API work?
```

**Comment by colevr1** [comment]
For all using Tinywall, to make docker desktop works with TinyApp, i did the following.
1. Opened Docker Desktop
2. Checked blocked connections with TinyWall:
![image](https://github.com/docker/for-win/assets/34273028/acab7cdf-aed0-4069-b9a1-48e37e5a4ce6)
Right click on every process involved (System and com.docker.backend.exe) and selected "Unblock"
3. For each rule added, i clicked on the tinywall modal which appears after the rule is added, and changed from "Unrestricted UDP..." to "No restriction" and added also "Apply same rules to child processes"
![image](https://github.com/docker/for-win/assets/34273028/ab8b6f26-cf0e-4785-a5e4-36d399b2147e)

After this, Docker Desktop was able to start. 

Now i will test it.
