### ISSUE TITLE
CANCELED [frontend internal] load build context

### ISSUE THREAD

**Issue by ghost** [docker/for-win#13942]
### Description

Running `docker compose up` fails with the error message "`CANCELED [frontend internal] load build context`" when the project directory contains a `node_modules` folder.

### Reproduce

1. Clone my repo: git clone https://github.com/TechGunnerINC/TechGunner.git
2. Run: sh init.sh (you will need WSL and Bun installed)
3. You'll see the error

### Expected behavior

Compose up successfully

## Actual behavior

![image](https://github.com/docker/for-win/assets/146823477/fc4160f0-ef5e-4aae-b25d-07ce84472a29)

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.2 (137060)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.782GiB
 Name: docker-desktop
 ID: b49e47aa-d6a8-4070-b025-91b7c00fcbd4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

4F728438-CBEC-4175-B3B5-38968FA62AC0/20240301092822

**Comment by moroz** [comment]
Add `node_modules` to `.dockerignore`

**Comment by ghost** [comment]
@moroz I have

**Comment by TrinsyCa** [comment]
Did you solve the problem? I'm getting the same error too. In the question [here](https://github.com/docker/for-win/issues/13812). I saw here that they mentioned the problem was solved when we downgraded the Docker version. However, I couldn't find how to downgrade the Docker version.


When I run the command `docker compose up -d` through the terminal, I get this error:

```cmd
PS C:\jobs\kle tech\greenpeacehotel\greenpeacehotel-api> docker compose up -d
[+] Running 9/9
 ✔ db 7 layers [⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                   24.2s
   ✔ 6a4a3ef82cdc Pull complete                                                                                    9.1s
   ✔ 5518b09b1089 Pull complete                                                                                    1.0s
   ✔ b6b576315b62 Pull complete                                                                                   16.6s
   ✔ 349b52643cc3 Pull complete                                                                                    2.5s
   ✔ abe8d2406c31 Pull complete                                                                                    3.9s
   ✔ c7668948e14a Pull complete                                                                                    6.0s
   ✔ c7e93886e496 Pull complete                                                                                    7.3s
 ! api Warning                                                                                                     2.1s
[+] Building 6.2s (7/30)                                                                                 docker:default
 => [api internal] load build definition from Dockerfile                                                           0.0s
 => => transferring dockerfile: 2.04kB                                                                             0.0s
 => [api internal] load metadata for docker.io/library/php:8.1-fpm                                                 4.4s
 => [api auth] library/php:pull token for registry-1.docker.io                                                     0.0s
 => [api internal] load .dockerignore                                                                              0.0s
 => => transferring context: 2B                                                                                    0.0s
 => CANCELED [api  1/24] FROM docker.io/library/php:8.1-fpm@sha256:32b7823afbac634b2e0115ca53a5d270fad0df3c7c021c  1.6s
 => => resolve docker.io/library/php:8.1-fpm@sha256:32b7823afbac634b2e0115ca53a5d270fad0df3c7c021c54714d811237fde  0.0s
 => => sha256:8ea9cef6db5ae39468fddf65e05346ec1b672585e014df044d40c60c280f4af6 225B / 225B                         0.6s
 => => sha256:ff65b997523ed8926becf7a45fbeab5cc1741dea6f7be0c518e8f7e6294201c8 0B / 104.36MB                       1.7s
 => => sha256:066c22b1a59f8746dc61446ce968c5f24e8cfc046095ad4a1dbdedd7f7c851bd 11.98kB / 11.98kB                   0.0s
 => => sha256:32b7823afbac634b2e0115ca53a5d270fad0df3c7c021c54714d811237fde8cc 1.86kB / 1.86kB                     0.0s
 => => sha256:13808c22b207b066ef43572e57e4fb8c6172e887dd9a918c089a174a19371b7a 13.63MB / 29.13MB                   1.7s
 => => sha256:e5a37c04f55f5931388694eba09bf484fbf3412999b6b063e9ab790ae96ab3a8 2.41kB / 2.41kB                     0.0s
 => => sha256:46d87a00aaae1ae22413715f1cacb07a29aa3dfb4fd90561b2966e73bd2efbc8 270B / 270B                         1.1s
 => => sha256:0100cea355849ea76bc8b1aa9f5a7b8acc816f02e0bc8d3836bface1a8a204ec 0B / 12.16MB                        1.7s
 => CANCELED [api internal] load build context                                                                     0.2s
 => => transferring context: 1.78MB                                                                                0.2s
 => [api] https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensio  1.4s
failed to solve: Canceled: context canceled
```

**Comment by wolfwell5** [comment]
![image](https://github.com/user-attachments/assets/6c624726-a5e9-43b1-be3c-592c5ebebf66)
add this in ignore file, but still face this
