### ISSUE TITLE
Install on Windows 11 Pro fails on ProgramData permission 

### ISSUE THREAD

**Issue by DanRoller** [docker/for-win#14136]
### Description

First install on Windows 11 Pro. 
C:\Users\dan00\Downloads>"Docker Desktop Installer.exe" install

C:\Users\dan00\Downloads>-------------------------------------------------------------------------------->8
Version: 4.30.0 (149282)
Sha1:
Started on: 2024/06/13 22:26:09.735
Resources: C:\Users\dan00\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22631
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\dan00\AppData\Local\Docker\install-log.txt
CommandLine: "Docker Desktop Installer.exe"  install
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-06-13T22:26:09.986198200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-06-13T22:26:09.986198200Z][Installer][I] No installation found
[2024-06-13T22:26:10.001826600Z][ManifestAndExistingInstallationLoader][I] Not run as admin, relaunching with UAC prompt
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\DockerDesktop' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 45
   at Docker.Installer.Program.Main(String[] args)Access to the path 'C:\ProgramData\DockerDesktop' is denied.

### Reproduce

(1) C:\Users\dan00\Downloads>"Docker Desktop Installer.exe" install
(2) Give permission to update Windows
(3) Crash

### Expected behavior

Expect to see installation proceed.

### docker version

```bash
didn't get that far
```

### docker info

```bash
Didn't get that far
```

### Diagnostics ID

?

### Additional Info

Version: 4.30.0 (149282)

**Comment by voonyee** [comment]
hi,
Thanks for reporting, looking at the error message you shared.
`System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\DockerDesktop' is denied.
`

Are you running that as the machine admin? If your admin account is different from your user account, you must add the user to the docker-users group, see the below doc:  
https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows

**Comment by DanRoller** [comment]
After trying to install, from my admin userid, I retried the install with an Administrator command, it fails with the same sort of problem.  I tried to create the C:\ProgramData\DockerDesktop from the Admin command, and that failed as shown below.  I'll try to tinker with the permissions of the C:\ProgramData folder.

:\Users\dan00\Downloads>"Docker Desktop Installer.exe" install

C:\Users\dan00\Downloads>System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\DockerDesktop' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\main-merges\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 45
   at Docker.Installer.Program.Main(String[] args)
C:\Users\dan00\Downloads>mkdir C:\ProgramData\DockerDesktop
Access is denied.

**Comment by DanRoller** [comment]
I've tried rerunning this with elevated permissions in CMD as well as a Windows Power Script and looked a permissions issue in the c:\ProgramData folder.
Used icacls C:\ProgramData /reset  to reset permissions.  In looking into permissions, I've chased "incorrectly ordered permissions", Group or user name of "NULL SID", or Account Unknown(S-1-15- etc.). 

But I'm no closer.  Installation isnt't working.

I did spend lots of time a month ago with Microsoft and Apple just to install iCloud.  Eventually, Apple, said skip the windows store and the first list on the iCloud page, and use second link to an alternate install that worked.

**Comment by DanRoller** [comment]
Resolved this problem and others by doing a clean install of windows 11.

**Comment by srok** [comment]
Here is 2026 I still get this. How does one get to the docker desktop when one cannot get past the “For security reasons C:\ProgramData\DockerDesktop must be owned by an elevated account” error on installation?

Yes installing from an adminstrative powershell.

I answered this myself, but so as to leave breadcrumbs for the next dev:

Delete the C:\ProgramData\DockerDesktop directory
Open PowerShell as administrator
Change to the directory the installer is in
Start-Process ‘Docker Desktop Installer.exe’ -Wait install

BY [mindcapers](https://forums.docker.com/u/mindcapers)

**Comment by EleftheriaBatsou** [comment]
> Start-Process ‘Docker Desktop Installer.exe’ -Wait install

Thank you @srok!!

(And for everyone who is a complete newbie: ProgramData is a hidden folder, so if you want to manually delete it, make sure to view your hidden folders as well.)

**Comment by Honghe** [comment]
encounter the same problem on windows 11 with latest docker desktop:

<img width="548" height="200" alt="Image" src="https://github.com/user-attachments/assets/b6611686-4118-42b1-9f4e-9ed0f85ad62c" />

and @voonyee, I can't see "docker-users" in "Local Users and Groups > Groups".

**Comment by Honghe** [comment]
@voonyee 
how i resolve this problem:
open powershell with admin:
```
Remove-Item -Recurse -Force 'C:\ProgramData\DockerDesktop'
```
and then install again.

notice: why delete 'C:\ProgramData\DockerDesktop' folder on Explorer gui not work, I don't know now. maybe it didn't actually delete the folder.

**Comment by AppliedEllipsis** [comment]
A friend recently had this issue.

We removed DockerDesktop from ProgramData and then recreated it with privileges and the installer worked after that.

run this in an admin elevated powershell terminal
```powershell
$dockerData = "C:\ProgramData\DockerDesktop"
New-Item -Path $dockerData -ItemType Directory -Force

# Take ownership and set admin as owner
$owner = New-Object System.Security.Principal.NTAccount("Administrators")
$dir = Get-Item $dockerData
$sd = $dir.GetAccessControl()
$sd.SetOwner($owner)
$dir.SetAccessControl($sd)

# Ensure inheritable permissions
icacls $dockerData /reset /T
icacls $dockerData /inheritance:e
```

**Comment by pablohcarmo** [comment]
Fixed it by deleting C:\ProgramData\DockerDesktop directory. No elevated privileges or something else needed.

**Comment by Ksdb104** [comment]
@pablohcarmo its fixed on me! thx!!!

**Comment by Kouroshilchi** [comment]
> A friend recently had this issue.
> 
> We removed DockerDesktop from ProgramData and then recreated it with privileges and the installer worked after that.
> 
> run this in an admin elevated powershell terminal
> 
> $dockerData = "C:\ProgramData\DockerDesktop"
> New-Item -Path $dockerData -ItemType Directory -Force
> 
> # Take ownership and set admin as owner
> $owner = New-Object System.Security.Principal.NTAccount("Administrators")
> $dir = Get-Item $dockerData
> $sd = $dir.GetAccessControl()
> $sd.SetOwner($owner)
> $dir.SetAccessControl($sd)
> 
> # Ensure inheritable permissions
> icacls $dockerData /reset /T
> icacls $dockerData /inheritance:e

thank you so much it works ✔
