### ISSUE TITLE
Docker Desktop - WSL update failed even after updating wsl from comman line (windows)

### ISSUE THREAD

**Issue by azegurb** [docker/for-win#14177]
### Description

wsl update failed: a manual wsl update is required

### Reproduce

Finish setting up Docker Desktop (version 4.28.0 or 4.32.0) - Use recommended setting (requires adminostrator password) -> Finish
it says **wsl update failed: a manual wsl update is required** and docker desktops stops running

### Expected behavior

docker must run as regular

### docker version

```bash
4.28.0
wsl update failed: a manual wsl update is required
```

### docker info

```bash
4.28.0
```

### Diagnostics ID

A078EEDA-C3A2-48AF-A544-7C0CCAB570BA/20240706190548

**Comment by Zenwoh** [comment]
What does `wsl --version` give you ?

**Comment by Rohanmrao** [comment]
I just had this issue resolved. I'm running windows 11. The way I fixed it was by using an older version of docker desktop (switched from 4.3 to 3.6)

`wsl -l -v` returns 
```
  NAME                   STATE           VERSION
* docker-desktop         Running         2
  docker-desktop-data    Running         2
  ```
  And I'm guessing this means everything works fine. I can even run containers successfully.

**Comment by tintronic1** [comment]
> ### Description
> wsl update failed: a manual wsl update is required
> 
> ### Reproduce
> Finish setting up Docker Desktop (version 4.28.0 or 4.32.0) - Use recommended setting (requires adminostrator password) -> Finish it says **wsl update failed: a manual wsl update is required** and docker desktops stops running
> 
> ### Expected behavior
> docker must run as regular
> 
> ### docker version
> ```shell
> 4.28.0
> wsl update failed: a manual wsl update is required
> ```
> 
> ### docker info
> ```shell
> 4.28.0
> ```
> 
> ### Diagnostics ID
> A078EEDA-C3A2-48AF-A544-7C0CCAB570BA/20240706190548
> 
> ### Additional Info
> _No response_

I'm having this same issue. Just installed latest Docker version for Windows on a Windows 10 Professional OS.
Each time I launch "Docker Desktop" the "Finish setting up Docker Desktop" version 4.31.1 (153621) prompts. I select "Use recommended settings) but get the "Dockder Desktop - WSL update failed" error with details:

wsl update failed: update failed: updating wsl: exit code: 4294967295: running WSL command wsl.exe C:\Windows\System32\wsl.exe --update --web-download: %1 no es una aplicación Win32 válida. 
Error code: Wsl/CallMsi/Install/0x800700c1
: exit status 0xffffffff

I run diagnostics, got Diagnostic ID: B7059B34-D269-4091-99E7-2546388B5C66/20240709235224

running wsl --update responds with (spanish language)
"%1 no es una aplicación Win32 válida.
Error code: Wsl/CallMsi/Install/0x800700c1"

wsl --version gets me the same response.

**Comment by Rohanmrao** [comment]
@tintronic1 maybe try a downgrade of your Docker Desktop version ?

**Comment by Zenwoh** [comment]
> I'm having this same issue. Just installed latest Docker version for Windows on a Windows 10 Professional OS. Each time I launch "Docker Desktop" the "Finish setting up Docker Desktop" version 4.31.1 (153621) prompts. I select "Use recommended settings) but get the "Dockder Desktop - WSL update failed" error with details:
> 
> wsl update failed: update failed: updating wsl: exit code: 4294967295: running WSL command wsl.exe C:\Windows\System32\wsl.exe --update --web-download: %1 no es una aplicación Win32 válida. Error code: Wsl/CallMsi/Install/0x800700c1 : exit status 0xffffffff
> 
> I run diagnostics, got Diagnostic ID: B7059B34-D269-4091-99E7-2546388B5C66/20240709235224
> 
> running wsl --update responds with (spanish language) "%1 no es una aplicación Win32 válida. Error code: Wsl/CallMsi/Install/0x800700c1"
> 
> wsl --version gets me the same response.

@tintronic1
First Docker Desktop install ever or an update ? If it's the first install it seems to me that WSL is not installed on your machine, please visit [this page to help you install WSL on Windows](https://learn.microsoft.com/en-gb/windows/wsl/install).

Not sure if those Win32 warnings have anything to do with Windows 32bit, but if you're running your OS in 32bit WSL won't work it seems.

**Comment by tintronic1** [comment]
> > I'm having this same issue. Just installed latest Docker version for Windows on a Windows 10 Professional OS. Each time I launch "Docker Desktop" the "Finish setting up Docker Desktop" version 4.31.1 (153621) prompts. I select "Use recommended settings) but get the "Dockder Desktop - WSL update failed" error with details:
> > wsl update failed: update failed: updating wsl: exit code: 4294967295: running WSL command wsl.exe C:\Windows\System32\wsl.exe --update --web-download: %1 no es una aplicación Win32 válida. Error code: Wsl/CallMsi/Install/0x800700c1 : exit status 0xffffffff
> > I run diagnostics, got Diagnostic ID: B7059B34-D269-4091-99E7-2546388B5C66/20240709235224
> > running wsl --update responds with (spanish language) "%1 no es una aplicación Win32 válida. Error code: Wsl/CallMsi/Install/0x800700c1"
> > wsl --version gets me the same response.
> 
> @tintronic1 First Docker Desktop install ever or an update ? If it's the first install it seems to me that WSL is not installed on your machine, please visit [this page to help you install WSL on Windows](https://learn.microsoft.com/en-gb/windows/wsl/install).
> 
> Not sure if those Win32 warnings have anything to do with Windows 32bit, but if you're running your OS in 32bit WSL won't work it seems.

Hi @Zenwoh
Thanks for your reply. 

Yes, this is my first Docker Desktop install ever.

WSL **is** installed. I even manually downloaded the latest WSL (version 2.2.4) as suggested in an older post about this issue. However, running the install file says WSL version 2.2.4 is already installed. Using the Reinstall option had no effect.

**Comment by rfay** [comment]
I have this. Have current latest stable WSL, 2.2.4.0. Tried to install Docker Desktop 4.33.1. Manually updated WSL2 (but there's nothing to update). Still has the same thing.  (Annoyingly, it refuses to downgrade back to 4.32.0, where it came from, saying it's up-to-date, so have to uninstall first.) Reverting to 4.32.0 seems to have solved the problem. DDEV test runner can run again.

Diagnostics ID: 714965AA-305C-4811-B395-B1F87D1BCF18/20240731225120

<img width="594" alt="image" src="https://github.com/user-attachments/assets/aa7bd4c2-4f52-4100-813d-457ef4aeba1b">

**Comment by valorisa** [comment]
Same here :

https://pastebin.com/WuGfRb6U [Diagnostics log]

![Capture d'écran 2024-08-14 162750](https://github.com/user-attachments/assets/fe0abec3-f030-442c-a187-21bb58e40263)
<img width="959" alt="Capture d'écran 2024-08-14 162917" src="https://github.com/user-attachments/assets/9b8dd37c-9384-4320-b8fd-ddd8976cd6a5">

**Comment by rfay** [comment]
The question I have is this:

Why does Docker Desktop think it has the right to update WSL for me? I didn't ask it to own my system. I don't think this is a correct design decision. I'll be happy to open a new issue. But why is it updating WSL?

**Comment by dahool** [comment]
I'm having the same issue with 4.33.1, the **first start** throw this error. second time it works.

I agree with @rfay tho, why Docker thinks it has the right to update wsl?

**Comment by vtsugi1** [comment]
Same issue for me. It only happens when Docker Desktop first launches upon startup. Then I have to close it and open it again, and it works fine.
When I run as admin, it opens fine but not as a user. Seems like it's trying to do wsl --update or something that requires admin permissions every time it starts up?


Windows 11 x64, Docker Desktop 4.33.1
wsl -v
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22621.3880

wsl --update
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.

**Comment by tintronic1** [comment]
Well, since I was unable to make Doker Desktop run and could not find a solution, I stopped trying.
A few weeks ago, while explaining the situation to a colleage I opened Docker Desktop to send him a prtscr, but it opened without issue!

I opened it again today and it is running. I did nothing docker-related inbetween. No update, no tinkering, nothing. There wasn't even a startup waiting time for some update, it just loaded without an issue.

To other people having this isse, is it still present or does it now load trouble-free?

**Comment by Zenwoh** [comment]
> I opened it again today and it is running. I did nothing docker-related inbetween. No update, no tinkering, nothing.

Maybe windows updated WSL on it's own and that solved the issue for you (somehow) ?

**Comment by dahool** [comment]
> Well, since I was unable to make Doker Desktop run and could not find a solution, I stopped trying.
> A few weeks ago, while explaining the situation to a colleage I opened Docker Desktop to send him a prtscr, but it opened without issue!
> 
> I opened it again today and it is running. I did nothing docker-related inbetween. No update, no tinkering, nothing. There wasn't even a startup waiting time for some update, it just loaded without an issue.
> 
> To other people having this isse, is it still present or does it now load trouble-free?

I'm still experiencing the same issue.
I just stopped using docker desktop and started using it directly on wsl.

**Comment by H4M5TER** [comment]
![image](https://github.com/user-attachments/assets/c8937a4f-3fe3-4cab-a329-ab6400ee3498)

it says wsl is already latest version
i dunno why docker desktop kept asking to update wsl and got 'failed'

$Env:LOCALAPPDATA\Docker\log\monitor.log

![image](https://github.com/user-attachments/assets/49232a9c-33a4-46a4-b141-2520fe60fd85)

**Comment by dahool** [comment]
looks like it has been fixed in 4.34.1

**Comment by Technorocker** [comment]
This still isn't working. I even uninstalled the wsl that was the features version and then went to download the wsl latest version and installed it that way. Then I've done the wsl --update and it says I have the latest version. 

Ive tried running docker desktop both reg and admin user permissions and I still get that warning.

**Comment by c88tm** [comment]
I went to the settings file located in `%appdata%\Docker\settings-file.json` and deleted the line that says
`"WslInstallMode": "manuallyConfigureWsl"`
Then the message disappeared.

**Comment by vtsugi1** [comment]
The issue was finally solved for me after updating to 4.35

**Comment by LqkUWp** [comment]
> I went to the settings file located in `%appdata%\Docker\settings-file.json` and deleted the line that says `"WslInstallMode": "manuallyConfigureWsl"` Then the message disappeared.

I just set `WslUpdateRequired` to `false`, then the warning disappears and everything is fine.

**Comment by elonderin** [comment]
### My Symptoms:

fresh win11 install: 
```
OS Name:                       Microsoft Windows 11 Pro
OS Version:                    10.0.26100 N/A Build 26100

> wsl -l
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605
```

#### Steps
1. installed from latest installer which was 4.36.0 but that then wants an update to 4.37.1 (some1 forgot to update a link on the DL page)

-> 
same message as in here:
https://github.com/docker/for-win/issues/14177#issuecomment-2288950021

when i discard the message, then DD shuts down a bit later in its own.
running as admin makes no diff

Seems like that docker cant even install the internal docker distro:

```
>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-22.04 (Default)
```

### My Fix

1. installed DD 4.27.1 (136059)
   - that worked and i also now have the DD distros:
    ```
    Windows Subsystem for Linux Distributions:
    Ubuntu-22.04 (Default)
    docker-desktop
    docker-desktop-data
    ```
2. upgraded to latest, i.e. 4.37.1 ->  still works

### More Info for the bug hunt:
the above happened while moving to a new dev rig. 
While playing around to fix this, i accidentally uninstalled DD from my old machine (where it worked), instead from my new rig (RDP can be a bitch 😉 ). Anyhow, i reinstalled the 4.36.0 in my old rig and it stilled worked. 

So i'm guessing, this has smth to do with DD not being able to create its 2 DD-distros on a virgin machine.

**Comment by HitkoDev** [comment]
> > I went to the settings file located in `%appdata%\Docker\settings-file.json` and deleted the line that says `"WslInstallMode": "manuallyConfigureWsl"` Then the message disappeared.
> 
> I just set `WslUpdateRequired` to `false`, then the warning disappears and everything is fine.

Yeah same, I got prompted to update WSL after updating Docker, so I ran `wsl --update` to install the latest version, and Docker still tried to do the update after restart. Looks like it just blindly abides the `WslUpdateRequired` value instead of actually checking the WSL version 😠

**Comment by obatabba** [comment]
### A Possible Fix

I encountered the same issue with a first-time-install docker 4.37.1 -which is the version you get in docker download page even though the latest version at the time of this comment is 4.38.0.

**_The Steps I Followed:_**

 I am running windows 10 pro, I have Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform and Windows subsystem for Linux all enabled in Windows Features.

I ran `wsl --update` in powershell and then installed Ubuntu with `wsl.exe --install Ubuntu`, confirmed the installation with `wsl --status` and got: 
`Default Distribution: Ubuntu`
`Default Version: 2`

I launched Docker Desktop, same error: Docker Desktop WSL Update Failed.

I updated Docker Desktop to 4.38.0 and started it again, same issue.

Running it as Administrator didn't help.

**Finally**, in Docker Desktop under the menu with question mark icon, I clicked **Reset To Factory Defaults**, closed the app and opened it again, and it worked!!

Note that I mentioned everything I tried because resetting to factory defaults wouldn't have solved the issue without updating WSL and installing a Linux distro, and I think enabling the mentioned Windows Features is necessary, So if you're encountering the same issue, make sure to do everything I mentioned.

Hope this will work for you too.

**Comment by rd2d2remembersall** [comment]
**Fixed**
Been having the same issue. None of the solutions provided above worked for me. Turns out i accidentally turned SVM mode off while restoring BIOS settings to default. WSL was updated, Hyper-V turned on in Windows, but ive never tried to run it. Check if its the case for you using the Task manager.    

![Image](https://github.com/user-attachments/assets/8bd89663-a52a-4220-aab0-bae5ce3acd7c)

**Comment by Re-dorn** [comment]
> I went to the settings file located in `%appdata%\Docker\settings-file.json` and deleted the line that says我转到位于 中的 `%appdata%\Docker\settings-file.json` 设置文件并删除了显示 `"WslInstallMode": "manuallyConfigureWsl"` Then the message disappeared.然后这条信息就消失了。

Finally, thx bro.
