### ISSUE TITLE
Build history items remain listed after deletion

### ISSUE THREAD

**Issue by ArnieGA** [docker/for-win#14288]
### Description

In the `Builds > Build history` component, items remain listed even after removed via their `Delete` button. This issue occurs with **any and all** items in the list. For example, checking the select all box and using the `Delete` button in the toolbar to remove all items, has the same results.

Quitting the application by right-clicking its icon on the system tray and selecting `Quit Docker Desktop`, and then reopening the application and trying again, doesn't help.  The only way I found to restore proper functionality was to restart the machine.

### Reproduce

1. Create local builds via command-line with `docker build`. Do not run them.
2. The build can either fail or succeed--it doesn't matter.
3. Head over to **Docker Desktop**.
   - In the case of successful builds, head over to the **Images** tab and remove the image.
   - In any case, head over to the **Builds** tab.
4. Before attempting to remove an item, click on its name first to see more info--it's supposed to be there along with the `Error`, `Logs`, and `History` tabs.
5. Go back to the **Builds** tab, and attempt to delete the item by clicking on the item's `Delete` button--the item remains there.
6. Click on its name again to see its info. A message will show instead of the previous information screen, which says:
   ```
                Application Error
      We've reported this to our error tracker
   "ref <some-id> is deleted: file does not exist"
            ┌────────────────────────┐
            │ Report issue on GitHub │
            └────────────────────────┘
   ```

Sometimes the item(s) will be removed from the list, but other times it/they won't no matter what.  Restarting the application by quitting out from it first will "restore" the information that appears when clicking on the items name, but performing steps 5 & 6 will result in the same issue.

### Expected behavior

Once an item is deleted, the list item should be removed.

### docker version

```bash
Docker version 27.1.1, build 6312585
```

### docker info

```bash
Client:
 Version:    27.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 7.371GiB
 Name: docker-desktop
 ID: 5eee0b38-dc6d-4019-926e-d50b0a947834
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

0E4331B9-CA54-4720-A0B5-A8872BBB80F0/20240827183851

### Additional Info

**System**:  Windows 11 Home 23h2.

**Comment by rescenic** [comment]
Yeah, I got this error too.

**Comment by Chris-Horne-Deloitte** [comment]
Same here.

**Comment by crazy-max** [comment]
Should be fixed with latest Docker Desktop 4.37: https://docs.docker.com/desktop/release-notes/#4370

**Comment by n-traore** [comment]
Still having this issue on Docker Desktop 4.37.1 (using Windows 10 Pro 22H2).

**Comment by barryguvenkaya** [comment]
> Still having this issue on Docker Desktop 4.37.1 (using Windows 10 Pro 22H2).

4.38.0 fixed it for me.

**Comment by n-traore** [comment]
@barryguvenkaya  Thanks for this, I can also confirm it works now with 4.38.0

**Comment by amoghnath** [comment]
This issue persists on v4.42.1

**Comment by margablaw** [comment]
Issue persists on v4.43.1 in Win11 Pro 24H2
