### ISSUE TITLE
Enable SCTP protocol in Docker for Windows

### ISSUE THREAD

**Issue by kprzybyla** [docker/for-win#2130]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

I'd like to enable SCTP protocol inside the Docker for Windows. The possible solution for this was proposed by @razaborg with issue on https://github.com/linuxkit/linuxkit/pull/1675 and @acetcom with issue https://github.com/linuxkit/linuxkit/pull/3025. After the fixes in LinuxKit and version update of LinuxKit in Docker modprobe should load the module correctly.

### Actual behavior

Unfortunately the solution does not work with the newest version of Docker that has LinuxKit 0.4 which contains the required changes for SCTP to work. As suggested by @justincormack in  https://github.com/linuxkit/linuxkit/pull/3025 this may be because Docker has their own kernel config files that override those from LinuxKit.

After installing kmod and running `modprobe sctp` the following error is raised:

```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file
aufs/modules.dep.bin'
modprobe: FATAL: Module sctp not found in directory /lib/modules/4.9.93-linuxkit-aufs
```

I also tried this with --privledge flag and it does not work.

I see that @acetcom created issue in Docker for Mac repository (https://github.com/docker/for-mac/issues/3016) but this issue is also present in Docker for Windows where I need it to work.

### Information

  - Windows Version: Windows 10 Enterprise Version 1607 (BUILD: 14393.2248)
  - Docker for Windows Version: Docker version 18.05.0-ce, build f150324
  - Docker Image: debian:stretch-slim

### Steps to reproduce the behavior

  1. ```apt update```
  2. ```apt install kmod```
  3. ```modprobe sctp```

**Comment by rn** [comment]
We have enabled SCTP in newer LinuxKit kernel (upstream for Docker for Mac/Windows) but unfortunately we are currently stuck on 4.9.93 because the AUFS patches do no apply to newer kernels. Enabling SCTP for older kernels is a bit iffy and I'd much rather see AUFS fixed to move onto newer kernels and then SCTP would also be available.

**Comment by kprzybyla** [comment]
Thank you for the response. I understand your reasoning I was actually suprised that Docker for Win is fixed with one kernel version since LinuxKit contains multiple versions but now I see why.

I'm not familiar with issue of AUFS patches for newer kernels, could you please share some date when it's planned to be fixed or link to an issue so I can track it if it's not some internel Docker issue? It will be much appreciated.

**Comment by rn** [comment]
I have no idea when the AUFS patches will be fixed. There have been several releases of the AUFS patches (typically once a month) and they still do not apply to newer 4.9 kernels (checked last late last week).

**Comment by jameswmcnab** [comment]
I'm not sure where to check but would it possible the check if the AUFS patches are now available for the newer 4.9 kernels? I'd love to see SCTP support as well.

**Comment by kprzybyla** [comment]
SCTP is now enabled and works in Docker 2.0.0.0-beta1-win75 with Linux Kernel 4.9.125 so I'm closing this issue since it got resolved.
