### ISSUE TITLE
"log-opts" unavailable in daemon.json

### ISSUE THREAD

**Issue by MPapst** [docker/for-win#2248]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `F46E9CF8-8784-4C0B-8068-169A2F32B504/2018-07-25_12-23-03`

### Expected behavior
When adding logging configuration to the daemon.json (According to the [Documentation](https://docs.docker.com/config/containers/logging/json-file/#options)), the Option `log-opts` should be available.

### Actual behavior
The Settings Window of the GUI shows `"log-opts" : Invalid option`:
![docker-forwin-gui](https://user-images.githubusercontent.com/16494676/43195332-114ae332-9005-11e8-8b89-6bcc9b5a37dd.png)
Docker failes to start.

### Information
  - Windows Version: Windows 10 Enterprise 1803
  - Docker for Windows Version: 18.03.1-ce

### Steps to reproduce the behavior
  1. Update daemon.json with `log-opts` as seen above
  2. Restart Docker

**Comment by thaJeztah** [comment]
Not seeing this problem on Docker for Mac 18.06 (so either it's fixed in a more recent release, or it's specific to Docker for Windows)

ping @ebriney PTAL


@MPapst note that all _values_ for the log-opts must be specified as strings (even numeric values), so the correct configuration would be;

```
  "log-opts" : {
    "max-size" : "5m",
    "max-file" : "3"
  }
```

**Comment by MPapst** [comment]
@thaJeztah, thanks - this fixes the restart issue. The GUI error remains.

**Comment by ebriney** [comment]
Ok, will check that, the code is not the same at all on Mac and Windows.

**Comment by gtardif** [comment]
@MPapst FYI with the new stable version (18.06.0 released today) docker-ce logs are rotated by default in the VM.

**Comment by thaJeztah** [comment]
@gtardif are those the _daemon_ logs, or logs for containers?

**Comment by gtardif** [comment]
yes, right, it's not the same ones, I jumped to quickly to a link between the 2. The daemon logs are rotated in the VM in the Stable version, not the container ones.

**Comment by ebriney** [comment]
@MPapst : I just checked on 18.06 and it works. 
Are you switched in windows containers mode?
Because it's not valid in windows daemon.

**Comment by ebriney** [comment]
![log-opts](https://user-images.githubusercontent.com/8415079/43266531-ec490892-90eb-11e8-84ed-58c904e83d9c.JPG)

**Comment by MPapst** [comment]
@ebriney: yes I am using Windows Containers.
Is there any documented way to get a rolling log file with windows containers?

**Comment by ebriney** [comment]
From https://docs.docker.com/engine/reference/commandline/dockerd : 
search `%programdata%\docker\config\daemon.json` in the page you will have all the options.
But I don't see any options concerning log rotation...
