### ISSUE TITLE
Open firewall ports takes a long time

### ISSUE THREAD

**Issue by sitex** [docker/for-win#286]
### Expected behavior

docker for windows is ready **_after few seconds_** (as it said in a tool-tip)

### Actual behavior

docker for windows is ready after 15 minutes

### Information

  - Diagnostic ID B28AE6BC-5E88-43F5-9C24-82D5F775D899/2016-12-04_14-49-38
  - windows 10 pro. version 1607. build 14393.447

### Steps to reproduce the behavior

  1. install docker for windows
  2. start docker for windows

**Comment by dgageot** [comment]
@sitex It looks like you are using the stable channel. Can you try Docker for Windows Beta31? It contains a lot of fixes to the boot sequence.

**Comment by sitex** [comment]
@dgageot things got worse with Docker for Windows Beta31 - 22 minutes to start
Diagnostic ID B28AE6BC-5E88-43F5-9C24-82D5F775D899/2016-12-05_15-33-12

**Comment by rneugeba** [comment]
@sitex thanks for filing a separate issue. Looks like on the stable branch, the majority of the time is spent here:
```
[14:30:33.833][HyperVGuids    ][Info   ] GUIDs installed
[14:30:33.843][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:30:34.239][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[14:45:18.003][Firewall       ][Info   ] Ports are opened
[14:45:18.007][HyperV         ][Info   ] Create
```

On the Beta channel the a large chunk of time is spent here:
```
[15:11:30.627][Moby           ][Info   ]  * Starting VPN proxy ... [ ok ]
[15:11:30.824][Moby           ][Info   ]  * Configuring host settings from database ... [ ok ]
[15:11:30.893][Moby           ][Info   ]  * Setting up proxy port service .../sbin/9pmount-vsock: starting in listening mode with serviceid=0B95
756A-9985-48AD-9470-78E060895BE7, tag=port, path=/port
[15:32:42.424][Firewall       ][Info   ] Ports are opened
[15:32:42.432][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[15:32:42.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 192.168.0.1
```

**Comment by rneugeba** [comment]
@dgageot both seems firewall related...any idea?

**Comment by sitex** [comment]
@rneugeba are you talking about Windows Firewall?
I've just switched off Windows Firewall and started Docker for Windows - same issue - 25 minutes to start (New High Score!)
Diagnostic ID B28AE6BC-5E88-43F5-9C24-82D5F775D899/2016-12-05_20-34-05

**Comment by rneugeba** [comment]
I had a closer look at the logs, as well as the logs reported by @kamkie on #283 (which looks like the same issue).

@kamkie `1.13.0-rc2-beta31` Windows build 14971:
```
[14:23:20.659][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
...
[14:41:23.747][Firewall       ][Info   ] Ports are opened
...
[18:10:29.772][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[18:10:30.808][Firewall       ][Warning] Firewall service is not running.
[18:58:44.642][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
...
[19:38:51.705][Firewall       ][Info   ] Ports are opened
``` 
@sitex `1.12.3-stable` Windows build 14393
```
[15:10:31.845][Firewall       ][Info   ] Closing ports...
[15:10:34.068][Firewall       ][Warning] Firewall service is not running.
...
[14:30:33.843][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:30:34.239][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[14:45:18.003][Firewall       ][Info   ] Ports are opened
```
@sitex `1.13.0-rc2-beta31` Windows build 14393:
```
[15:10:44.034][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
...
[15:32:42.424][Firewall       ][Info   ] Ports are opened
...
[20:07:07.590][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
...
[20:32:28.471][Firewall       ][Info   ] Ports are opened
```

So, in all cases it takes a *very* long time to open the Firewall ports. On a normal system with Beta31 we see something more like this:
```
[18:13:42.848][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
...
[18:13:44.484][Firewall       ][Info   ] Ports are opened
```
something like a couple of seconds vs 15-30 minutes as reported.

@dgageot any idea why this takes so long? Should we add some instrumentation to find out where the time is spent?

**Comment by kamkie** [comment]
on windows 14986 and docker for windows 1.13.0-rc3-beta32 (9266) problem still exists 
27CA4E77-3441-4D83-9240-B52F69F2EF03/2016-12-08_09-09-21

**Comment by astondg** [comment]
Just to add to the feedback I'm seeing a long Docker startup as well with a lot of time spent in a similar location in the logs on Windows 10 build 14393.576 and Docker 1.12.3 (8488)

7369A615-9854-4C40-844A-9262478A0217/2016-12-15_09-24-03

`[07:52:53.983][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.
exe...
[07:52:54.108][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[07:55:45.098][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[07:55:57.850][FeedbackSettings][Info   ] Open logs
[08:03:06.593][Firewall       ][Info   ] Ports are opened
[08:03:06.600][HyperV         ][Info   ] Create`

**Comment by davidflam** [comment]
I think I'm also having the same problem. Docker startup is slow compared to previous versions (1.21.1 was ok). It looks like the problem is with VPN proxy. Logs bellow are from a "clean" install on my system, about 30 seconds pauses while starting VPN proxy and opening ports. Maybe somekind of timeout? If I run some containers, the problem gets worse, increasing pauses to several minutes.

**Version**
```
Version: 1.13.0-rc5-beta35 (9606)
Channel: Beta
Sha1: d603c07c049bd3ef899e3ac09ead2a5db339679d
Started on: 2017/01/07 13:19:29.019
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
```

**Possible Problem**
```
[13:47:57.034][Moby           ][Info   ] /sbin/9pmount-vsock: mount successful for serviceid=C378280D-DA14-42C8-A24E-0DE92A1028E2 tag=db path=/Database
[13:47:57.071][Moby           ][Info   ]  [ ok ]
[13:47:57.126][Moby           ][Info   ]  * Configuring kernel parameters ... [ ok ]
[13:47:57.162][Moby           ][Info   ]  * Starting VPN proxy ... [ ok ]
[13:48:27.205][Moby           ][Info   ]  * Starting DHCP Client Daemon ... [ ok ]
[13:48:27.268][Moby           ][Info   ]  * Starting networking ... *   lo ... [ ok ]
[13:48:27.299][Moby           ][Info   ]  * Initializing random number generator ... [ ok ]
[13:48:27.379][Moby           ][Info   ]  * Starting VPN proxy ... [ ok ]
[13:48:27.406][Moby           ][Info   ]  * Starting busybox acpid ... [ ok ]
[13:48:27.457][Moby           ][Info   ]  * Running system containerd ... [ ok ]
[13:48:27.475][Moby           ][Info   ]  * Running system containers ... binfmt rng-tools [ ok ]
[13:48:27.562][Moby           ][Info   ]  * Starting VPN proxy ... [ ok ]
[13:48:27.691][Moby           ][Info   ]  * Configuring host settings from database ... [ ok ]
[13:48:27.774][Moby           ][Info   ]  * Setting up proxy port service .../sbin/9pmount-vsock: starting in listening mode with serviceid=0B95756A-9985-48AD-9470-78E060895BE7, tag=port, path=/port
[13:49:09.260][Firewall       ][Info   ] Ports are opened

```

**Comment by sitex** [comment]
I have updated Docker to v.1.13.0-beta39.
And it looks like the issue is solved.

**Comment by kamkie** [comment]
for me problem still exists 
27CA4E77-3441-4D83-9240-B52F69F2EF03/2017-01-29_11-46-42

**Comment by rneugeba** [comment]
@sitex thanks for reporting back and glad it's working for you now...

@kamkie thanks for trying Beta39. Your case looks slightly different. We try to open some ports in the firewall and only if that succeeds start some other components. On your system it takes something like 19 minutes for the firewall code to complete, thus delaying everything...

I've filed an internal tracking issue

**Comment by davidflam** [comment]
I can confirm that is working as expected since 1.13.0-beta39.

**Comment by LiuSai-Dream** [comment]
If anyone can post download link of 1.13.0-beta39 docker. Thanks.

**Comment by rneugeba** [comment]
@LiuSai-Dream why do you need Beta39? Do you see the issue with the latest Beta/Stable? If so could you provide a diagnostics ID so we can take a look?

**Comment by rneugeba** [comment]
@kamkie could you try again with the latest beta. We added some additional logging which may help us diagnosing this.
thanks

**Comment by kamkie** [comment]
Version: 1.13.1-beta42 (10069) on windows 10 15031
 27CA4E77-3441-4D83-9240-B52F69F2EF03/2017-02-15_19-42-43

**Comment by rneugeba** [comment]
@kamkie thanks for the updated logs

**Comment by dgageot** [comment]
@kamkie @sitex @davidflam @astondg @furio We just release version `17.03.0-rc1` of Docker for Windows with overhauled code for the firewall management. Please give it a try and tell us if it's better now.

**Comment by davidflam** [comment]
@dgageot I've just tried Docker version 17.03.0-rc1 and it is much faster. Under 30 seconds.

**Comment by kamkie** [comment]
@dgageot it is much better now, but still i have some problems

installation took 20 minutes but after that docker was working 

after restart docker was working but still marked as starting (commands like `docker ps`) and it "crashed" 27CA4E77-3441-4D83-9240-B52F69F2EF03/2017-02-22_22-55-49
> Docker command did not complete within the allowed timeout
but even after that `docker ps` is working

response from docker ps before timeout
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
8d970c73ee97        d4w/nsenter         "/usr/bin/nsenter1..."   46 seconds ago      Up 45 seconds                           nifty_khorana
```

**Comment by rneugeba** [comment]
@kamkie it looks like the original issue is fixed (looking at the logs) so I'm closing this issue. Could you open a new issue with the new issue your are seeing?
Thanks

**Comment by robnardo** [comment]
Mine took a long time, then crashed.  Crash report ID: 4F7AE5C5-FEA5-4D2F-8F87-9C58348EF5BA/2018-05-17_09-10-04
