### ISSUE TITLE
Docker desktop crashes on opening

### ISSUE THREAD

**Issue by dnhlms** [docker/for-win#3262]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:  B1A67DE6-5B04-46E4-BB80-F27FE90959B5/20190119164419

### Expected behavior
I started docker desktop.  My goal is to increase the memory allowed to the container.  Docker Desktop shows it started and is in the system tray.  When i click on it, i get the menu and expect to be able to pick a settings option.

### Actual behavior
When i click the icon, the menu shows only briefly and i am greeted with the crash notification screen.

### Information

  - Windows Version:  Windows 10
  - Docker for Windows Version:  I don't remember and i can't get to the settings page to see it.  The docker for windows.exe has a version of 2.0.0.30215 and a product version of 2.0.0.2

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ysokolovski** [comment]
Same problem. After upgrade to Docker Desktop, it crashes when I try to access the tray menu. Please fix ASAP.

**Comment by dnhlms** [comment]
I uninstalled and installed the edge 2.0.1.0 and that problem is resolved.  It isn't my preference to run a beta but it was so unusable i had ot.

**Comment by cyberflying** [comment]
Same problem. "Docker for Windows.exe" and "Docker.Watchguard.exe" is running.

**Comment by JoBrad** [comment]
Same issue. Uploaded crash diagnostics. I can run the CLI tools without any issues.

**Comment by ste93cry** [comment]
Same issue here, after updating to the latest Docker Desktop version

- Diagnostics ID: 8A085406-7A2B-4235-A87D-4D624EC55EF0/20190126122426
- Windows Version: 10.0.17763.253
- Docker for Windows Version: 2.0.0.30215

**Comment by boskjoett** [comment]
Same problem. I am amazed Docker can release such a poor quality for Windows.

**Comment by JoBrad** [comment]
Upgrading to the edge version resolved this for me, as @maloufde described.

**Comment by tuantrannav** [comment]
I had to "reset to defaults", then it stopped crashing.

**Comment by ste93cry** [comment]
Resetting to defaults fixed the issue for me too

**Comment by rnwood** [comment]
This is the same as issue #3300. Duplicating my comment from there:
I experienced this too. It's caused by a 401 response coming back from a request made to the docker hub.

A workaround is to remove all the items containing "docker" from Windows Credential Manager control panel and then start the tray app again. You'll need to sign into Docker Hub again using the option in the context menu.

**Comment by ggirard07** [comment]
Looks like a duplicate of #3230 too (which has way more attention than this issue)

**Comment by LoickVirot** [comment]
Got the same problem. Resolved by resetting docker to default too.

**Comment by bhaskarpramanik** [comment]
Same issue seen after my windows 10 upgrade. Good pointer on 401 thing!
Can docker store "user profile/permissions" retrieved after first login, somewhere on the disk (for sometime, till "auth token" invalidates) and stops going to hub every time tray item is opened? Just a thought :)

**Comment by RyanMitchellWilson** [comment]
Still happening. I've clicked Reset to factory defaults about 10 times and all that happens is that it starts resetting then throws the same error over and over.
