### ISSUE TITLE
Docker Shared Volume permissions causes ActiveDirectory Lockout

### ISSUE THREAD

**Issue by BookOfGreg** [docker/for-win#3346]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - ~I have uploaded Diagnostics~
  - ~Diagnostics ID:~

### Expected behavior
An alert that volume had failed or not had permission for use. OR automatically reset/purge user credentials.

### Actual behavior
My machine is locked out on startup and the ActiveDirectory admin has to let me in every morning and afternoon.

### Information

  - Windows Version: 10, 1803 and 1809
  - Docker for Windows Version: 2.0.0.2 (30215) and older

This troubleshooting section is relevant but does not elaborate that you could get locked out the domain using this tool.
https://docs.docker.com/docker-for-windows/troubleshoot/#volumes

### Steps to reproduce the behavior

  0. Do not be localadmin on an ActiveDirectory domain.
  1. Turn on sharing C drive without permissions by clicking on the share C:// box and applying:
![image](https://user-images.githubusercontent.com/637868/52348309-ec647180-2a1b-11e9-96f4-6934f347ec50.png)
  2. Restart docker:
![image](https://user-images.githubusercontent.com/637868/52348345-fd14e780-2a1b-11e9-90ec-3bd7e0c6768d.png)
  3. Get locked out your account. Validate by locking machine and walking over to IT dept 😄 

#### Alternate
  0. Do not be localadmin on an ActiveDirectory domain.
  1. Turn on sharing C drive without permissions by clicking on the share C:// box and applying.
  2. Change your AD password
  3. Restart docker.
  4. Get locked out and start walk of shame to IT.

**Comment by kim-sondrup** [comment]
I am experiencing the same problem.  
When looking at the Windows Event Viewer I can see Docker Destktop try to login multiple times within the same second even after it fails.
I can not confirm that Docker Desktop is the only trigger for my account being lockout but it's behavior is part of the problem for sure.

The shown log entries all have the same caller process `C:\Program Files\Docker\Docker\Docker Desktop.exe`  

![image](https://user-images.githubusercontent.com/8328984/69131917-546bdc00-0ab3-11ea-901c-b08db6ed4218.png)

**Comment by lhopkins-tucasi** [comment]
/remove-lifecycle stale

This has been happening to me for months... very frustrating

**Comment by mat007** [comment]
@lhopkins-tucasi have you tried with the latest 2.2.0.3? We believe this should now be fixed as there is no logon events being issued anymore.

**Comment by lhopkins-tucasi** [comment]
> @lhopkins-tucasi have you tried with the latest 2.2.0.3? We believe this should now be fixed as there is no logon events being issued anymore.

Sounds good, I'll give that a shot now. Thanks for the suggestion

**Comment by lhopkins-tucasi** [comment]
@mat007 I'm still getting the problem daily with 2.2.0.3

The area that you set the credentials is now gone though, which makes me think the login creds  must be stored somewhere still... Need to work out how to clear them out

**Comment by mat007** [comment]
@lhopkins-tucasi you may have some data still stored in the Windows «Credential Manager», look in «Windows Credentials» and delete anything which has Docker in the name.
Although we have changed the file sharing implementation the old code is still there and maybe it tries to make use of the old stored credentials somehow…
