### ISSUE TITLE
Docker not Starting Windows 10

### ISSUE THREAD

**Issue by Schnabbel** [docker/for-win#340]
### Expected behavior
Docker starting up normally
### Actual behavior
Docker not starting but throwing an error message instead
### Information
 - Diagnostic ID: 49AA8D2A-F004-404C-99BF-0D1E4AA28B1E/2016-12-19_18-06-35

 - host distribution and version (Windows version, build number, etc): Windows 10 Edu N 64bit Build 14393
   
   Already tried reinstalling Docker, did not solve the problem.

### Steps to reproduce the behavior

  1. Start Docker

  2. Get Error
      [Log_Error.txt](https://github.com/docker/for-win/files/661672/Log_Error.txt)

**Comment by rneugeba** [comment]
@Schnabbel thanks for the report. It looks like the system is starting ok, but very slow and there are a few other things which I believe have been fixed in the Beta channel. Could you try the latest Beta from https://download.docker.com/win/beta/InstallDocker.msi

**Comment by Schnabbel** [comment]
@rneugeba Unfortunately installing the latest Beta didn't fix the problem. I uploaded a new diagnosis with the Beta version here: 49AA8D2A-F004-404C-99BF-0D1E4AA28B1E/2016-12-19_22-44-18

**Comment by rneugeba** [comment]
@Schnabbel did something fix your issue?
