### ISSUE TITLE
Proxy configuration propagation doesn't work.

### ISSUE THREAD

**Issue by asakaxgit** [docker/for-win#3676]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
After setting proxies on Settings GUI (and restart), containers have environment variables related to proxy (ex. http_proxy).

### Actual behavior
No proxy related environment variables was settled in a container.
According to the documentation(https://docs.docker.com/docker-for-windows/), my proxy settings propagate into the containers.

### Information

  - Windows Version: 10.0.17763.379
  - Docker for Windows Version: 2.0.3.0 (31778)

### Steps to reproduce the behavior

  1. Setting "Manual proxy configuration" is on
  2. "Web Server(HTTP)" to http://blahblah:1234. 
  3. Then click apply, 
  4. Restart will begin.
  5. After docker's launch.  "docker run alpine env" on command-line shows below 
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=42d5ee4d97f0
HOME=/root`
No proxy related environment variables are shown!

**Comment by Addisco** [comment]
Same here. 
* Docker for Windows Version: 2.0.0.3 (31259)
* Channel: stable
* Build: 8858db3

**Comment by Addisco** [comment]
Manually adding the proxy configuration to `%USERPROFILE%\.docker\config.json` solved the issue for me. 

``` json
"proxies": {
  "default": {
    "httpProxy": "http://1.2.3.4:8080",
    "httpsProxy": "http://1.2.3.4:8080"
  }
}
```

**Comment by azack** [comment]
Still occurs in `2.1.0.2 (37877)`, Channel stable, Engine 19.03.2

**Comment by aklys** [comment]
I produce the same issue on Docker for Windows 2.1.0.5

**Comment by guidoavvisati** [comment]
Same issue for me on Windows 10 and Docker 2.2.0.5. Manually changing the ~/.docker/config.json file works. If some sites need to bypass the proxy, use the `noProxy` variable
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://127.0.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3001",
     "ftpProxy": "http://127.0.0.1:3001",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```

**Comment by mat007** [comment]
@guidoavvisati I believe this has been fixed in 2.2.1.0, see https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2210
```
Fixed a bug where users were unable to modify the Manual proxy configuration settings through the Docker Desktop UI.
```
See also #5606 #5548.

**Comment by davidtvs** [comment]
Using 2.3.0.2 and it's still not working. After setting the proxies in the GUI here's the output from `alpine env`:
```
> docker run alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a26984ab7a1a
HOME=/root
```

**Comment by mat007** [comment]
> Using 2.3.0.2 and it's still not working.

Oh yes, you’re right. This is actually a different issue.
I’ll re-open this one.

**Comment by mat007** [comment]
After running this by a few people on the team we realized that this is actually on purpose.
We might revisit this whenever there is a Docker Desktop Linux if there is one one day, but the rationale is that for now we want the same user experience on Windows/Mac than on Linux.

Therefore the recommended way to set proxy settings in containers is by setting environment variables, e.g. on the command line:
```
$ docker run -e HTTP_PROXY=http://proxy.example.com:3128 alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=625b39b859b1
HTTP_PROXY=http://proxy.example.com:3128
HOME=/root
```
or if you have the environment variables set on the host:
```
$ docker run -e HTTP_PROXY alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=625b39b859b1
HTTP_PROXY=http://proxy.example.com:3128
HOME=/root
```

Sorry for the inconvenience, we need to fix the documentation.

**Comment by mishak87** [comment]
On linux using client config is much more convenient than passing build variables since you can set it by script along with docker service without messing with your terminal session or .*rc files.

But on Windows everything is harder to script due to lacking support and outdated documentation.

Having list of proxies that would also apply to client config would be quite useful be it on Mac or Windows. You could have there a warning or toggle for applying same options also to client config.
Rarely I need one without the other. I am assuming the main use-case is for users behind "secure" enterprise firewalls forced to use single gateway. Actually disabling parallel pull could be another option in this "Behind enterprise firewall" settings panel 😂 since such gateway usually throttles traffic anyway.
