### ISSUE TITLE
New install crashes when logging in with Docker ID on Welcome screen 

### ISSUE THREAD

**Issue by rpatrick00** [docker/for-win#4044]
- I was having problems with Docker crashing during Windows startup after running successfully for several months.  After reading #3230, I uninstalled Docker, deleted the credential from Windows Credential Manager, restarted my machine, and reinstalled Docker Desktop 2.0.0.3.  After installation, Docker started successfully.  When the Welcome screen appeared, I entered my Docker ID and password and pressed the Log In button.  Immediately, an Error dialog box popped up saying Docker failed to initialize.

  - I have uploaded Diagnostics
  - Diagnostics ID: A53AAE46-B46C-4599-B6DA-4C1BEAF55AF7/20190606085909

### Information

  - Windows Version:  Windows 10 Pro
  - Docker for Windows Version:  Docker Desktop 2.0.0.3

C:\Windows\system32>docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Start Docker Desktop
  3. Login using the Docker Desktop Welcome Screen (NOTE: docker login from the Command Prompt seems to work fine).

**Comment by mikeparker** [comment]
Can you try latest edge and see if its fixed? We fixed a few bugs in this area recently.

**Comment by rpatrick00** [comment]
Thanks, I will give it a try and report back.

**Comment by rpatrick00** [comment]
Tried the 2.0.4.1 edge version and I still see the problem.   Diagnostic ID is A53AAE46-B46C-4599-B6DA-4C1BEAF55AF7/20190612182749

**Comment by mikeparker** [comment]
Ok, thanks for the info I can see the error, it's failing to store your credentials in the credential helper (although there is no indication of why..)

```
[13:27:49.772][GUI            ][Error  ] Docker.Core.DockerException
   at Docker.DockerLoginSync.SetCredentialInStore(DockerLoginCredential cred)
   at Docker.DockerLoginSync.OnCredentialChanges(Auth cred)
   at Docker.Core.Mediator`1.Raise(T ev)
   at Docker.WPF.DockerHub.CredentialManager.Store(Credential cred, Credential oAuthCred)
   at Docker.WPF.DockerHub.CredentialManager.<ValidateBasicCredentialsAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.WPF.WelcomeWindow.<LogIn>d__11.MoveNext()
-
```
