### ISSUE TITLE
Zombie container after updating to windows 1903

### ISSUE THREAD

**Issue by jasonmcboyd** [docker/for-win#4056]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C293FACB-C45E-482B-83F6-F4390B2C1A89/20190608143513

I have a zombie container after upgrading to Windows 1903. The container existed before the upgrade. After the upgrade Docker reports the container exists but any attempt to interact with or stop the container results in a "no such container" message or Docker simply hangs.

```
 docker ps --all
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                PORTS                    NAMES
4c70fe356631        microsoft/mssql-server-windows-developer   "powershell -Command…"   3 days ago          Up 3 days (healthy)   0.0.0.0:1433->1433/tcp   agitated_germain
```
```
docker exec -it agitated_germain powershell
no such container
```
```
docker exec -it 4c7 powershell
no such container
```
`docker stop` and `docker rm -f` hang indefinitely.

### Information
  - Windows Version: 1903
  - Docker Desktop Version:
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:10 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:06:34 2019
  OS/Arch:          windows/amd64
  Experimental:     true

### Steps to reproduce the behavior
Not sure. Maybe get a copy of windows 1809, start a container, upgrade to 1903.

**Comment by jasonmcboyd** [comment]
I uninstalled docker desktop and hyper-v and then reinstalled them and it was fixed. So I guess that is a solution.

**Comment by ktmitton** [comment]
I'm getting the same issue with the new 2.1 update. I've uploaded my diagnostics (12CD9B90-4858-4838-9983-BD5D447BBC56/20190802144117), I'll try the above fix to see if that works for me as well.

**Comment by ktmitton** [comment]
Just tested it out, doing a full uninstall/reinstall of both docker and hyper-v did not solve the problem for me.

I'm running docker desktop 2.1.0.0, here are the steps I use to reproduce it:

1. Run `docker run -d redislabs/redismod`
1. Container should be up an running, no issues yet
1. Restart your machine
1. Run `docker ps -a`, nothing looks wrong here
1. Run `docker container ls`, nothing looks wrong here
1. Run `docker logs <id>`, nothing looks wrong here
1. Run `docker exec -it <id> sh`, you'll get `no such container`
1. Run `docker kill <id>`, it'll just hang (I let it run for over 30 minutes before aborting this)

Here's a screenshot of what I see:
![image](https://user-images.githubusercontent.com/2873724/62386040-a567bc80-b524-11e9-914d-6b664d8a14ae.png)


The only way I've been able to remove these containers is to stop docker, then remove their directories in C:\ProgramData\Docker, then restart docker.

@mikeparker I'm new to this, is that what you need to see?

**Comment by karlholbrook** [comment]
We have the same issue with Windows Containers - Docker Desktop (2.1.0), windows 19:03. Cannot kill or stop or exec to a container that is claiming to be healthy. We have had this issue on 3 separate developer PCs, the only fix seems to be completely removing docker and reinstalling. 
Interestingly we also have a Docker Swarm running 19.03.01 that has a zombie container, claims to be healthy but cannot be killed - just hangs when try to stop/kill.  The Docker Swarm is running on windows 18:09.

**Comment by ktmitton** [comment]
@karlholbrook I had opened up ticket #4463 with more specific instructions and details, but I suspect the two issues are really the same. Per a comment in my ticket, the moby developers were able to resolve this in https://github.com/moby/moby/pull/39703, and if you want to test it you can find the nightly builds at https://master.dockerproject.org/.

I've downloaded the build and am no longer experiencing this issue 😀

**Comment by ktmitton** [comment]
@karlholbrook did my comment help? I'm pretty sure that's the same issue that got resolved by the moby update, and if so, I was going to suggest to @mikeparker this ticket be closed.

**Comment by karlholbrook** [comment]
Yes this helped, I have read through the moby fix and it sounds like it is the same issue. Thanks.
