### ISSUE TITLE
"Unable to create" Docker does not start, v2.1.0.0 after upgrade : NullReferenceException in SettingsLoader.SaveChanges: 

### ISSUE THREAD

**Issue by 3komma14** [docker/for-win#4390]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4514AB46-36A1-46D9-A078-AA9136CDE32C/20190802105340

### Information
Installed the upgrade to 2.1.0.0 and was not able to start.
Uninstall, installed and a reboot did not help.
Installed the old version 2.0.0.3 and all worked fine again

  - Windows Version: Windows 10 Pro 46bit
  - Docker Desktop Version: 2.1.0.0

### Steps to reproduce the behavior
Install docker version 2.0.0.3 and upgrade.

**Comment by mikeparker** [comment]
```
[12:53:25.602][HyperV            ][Error  ] Unable to create: System.Management.Automation.CmdletInvocationException: Objektreferanse er ikke satt til en objektforekomst. ---> System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved Docker.Core.SettingsLoader.SaveChanges(Action`1 changes)
```

**Comment by vinicius-lima** [comment]
Unable to create
at Docker.Core.Pipe.NamedPipeClient.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
at Docker.Actions.<>c__DisplayClass27_0.b__0()
at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

diagnostic ID: 1BCC0740-9152-4818-B59A-E5DD6230CFA6/20190802140216

**Comment by da9l** [comment]
I get a very similar error too after upgrading to 

```
Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

But looking at [log.txt](https://github.com/docker/for-win/files/3466350/log.txt) I get the impression my problem might have something to do with:

`[09:06:43.881][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".`

D89B102F-8759-4D6E-B323-A69B530DA6A8/20190805070644

**Comment by da9l** [comment]
If I switch to windows containers it works but when I try to switch back to linux I get the same error again.

D89B102F-8759-4D6E-B323-A69B530DA6A8/20190805085752

**Comment by ksushaBoo** [comment]
a have the same problem 

`Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()`

[log.txt](https://github.com/docker/for-win/files/3468176/log.txt)

FB785C56-1FAB-479E-AA9D-B3E8457C3786/20190805144718

How can i solve this problem?

**Comment by da9l** [comment]
Ok.. I've got pretty good reasons to believe this is practically a duplicate of [issue 324](https://github.com/docker/for-win/issues/324). 
* The error messages are practically the same `...Hyper-V was unable to find a virtual switch with name "DockerNAT".`
* One of the workarounds in that issue solved this problem for me.

**Comment by jorioux** [comment]
Same problem with 2.1.0.0 even after uninstall Docker, reboot, and reinstalling it:

```
Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by mattdunndc** [comment]
Same.  Fail Whale.

Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by nithinmohantk** [comment]
Same problem for me as well after updating to 2.1.0.0 
`Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()`

More details form log.txt 
`[11:59:34.448][HyperV            ][Info   ] Creating Switch: DockerNAT...
[11:59:38.573][HyperV            ][Info   ] Switch created.
[11:59:39.594][HyperV            ][Info   ] Setting docker switch IP address to 10.10.75.1
[11:59:39.768][HyperV            ][Info   ] Removing any other IP addresses from DockerNAT switch
[11:59:52.650][HyperV            ][Info   ] Creating VM DockerDesktopVM...
[11:59:52.745][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[11:59:52.745][Linux             ][Info   ] Setting container engine status to FailedToStart
[11:59:52.762][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to create    at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, String command, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Create(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[11:59:53.014][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to create
[11:59:53.016][Notifications     ][Error  ] Unable to create`

**Comment by da9l** [comment]
I got an update to 2.1.0.1. Despite that this issue is mentioned in the release notes, it did not fix the problems for me. 

The error log got a little bit more verbose about the actual problem tho.

```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by da9l** [comment]
Ok, the errors I have reported here are actually another problem: See https://github.com/docker/for-win/issues/4462. I will move my comments to that issue report.

**Comment by vinicius-lima** [comment]
I have updated Docker Desktop for Windows to version v2.1.0.1 and it started to work as expected again. I restarted my PC and Docker itself and everything seems to be running well until now.

**Comment by boop5** [comment]
same with stable 2101 (37199)

**Comment by alexbom** [comment]
Just installed Windows Desktop version, downloaded from official site and got same problem.

> Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by adunlea** [comment]
I've been getting the same issue with Docker Desktop 2.1.0.1. Does anyone have a workaround? Is there an earlier version that works?

```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by erikread** [comment]
I too am having the same issue.
With mine I have 2 identical Windows 10 Professional vms in VMWare Fusion.
I am using the latest version of Fusion. On an older Macbook Pro (2108) Docker runs fine. On the newer one (2019, 32GB RAM, Core i9) I get the error that others are seeing.
If I run a VM in Parallels it works.

**Comment by psydrohne** [comment]
same problem here after upgrading!

**Comment by Lambda-android** [comment]
It might be a Hyper-V vs. antivirus issue.
https://support.microsoft.com/en-us/help/3105657/recommended-antivirus-exclusions-for-hyper-v-hosts

**Comment by mikeparker** [comment]
Most comments in this thread are not the same issue. This issue is about the `System.NullReferenceException` in `SaveChanges`, which has been fixed with the release of 2.1.0.1.

For example:
* `Hyper-V was unable to find a virtual switch with name "DockerNAT".` is a different issue.
* Compatibility with VMWare Fusion is a different issue.
* `Logon failure: the user has not been granted the requested logon type at this computer.` is a different issue

Unless your error is exactly the above, please open a new issue or more likely the issue already exists (in many cases the fixes are documented already), please search for it and add your comments and diagnostics there. Thanks!

**Comment by bailey8** [comment]
I am getting this issue as well

   
at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by Guangrun** [comment]
> 
> 
> Unable to create
> at Docker.Core.Pipe.NamedPipeClient.d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
> at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
> at Docker.Actions.<>c__DisplayClass27_0.b__0()
> at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
> 
> diagnostic ID: 1BCC0740-9152-4818-B59A-E5DD6230CFA6/20190802140216

Hi, I confronted the same problem.
It was resolved by:
1, diabling Hype-V 
2, restart windows
3, enabling Hype-V
4, restart windows 
5, stopping and starting destop-docker

**Comment by Guangrun** [comment]
> 
> 
> I am getting this issue as well
> 
> at Docker.Core.Pipe.NamedPipeClient.d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
> at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
> at Docker.Actions.<>c__DisplayClass27_0.b__0()
> at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

Hi, I confronted the same problem.
It was resolved by:
1, diabling Hype-V
2, restart windows
3, enabling Hype-V
4, restart windows
5, stopping and starting destop-docker

**Comment by RonLencioni** [comment]
I have tried many of these solutions and am still unable to get it to work my Diag ID: EB3D589B-FA13-47EF-97AF-581B9B68DB60/20200103230657

One thing to note is that I am not Admin on my box.

**Comment by gogorichie** [comment]
I was experiencing this same error post-installation. I restarted the Docker Desktop Service and the error was resolved.

**Comment by harshitshah436** [comment]
I have installed 2.1.1.0(37260) in the past and it worked well. So after that, I never tried to upgrade :)

**Comment by di-ma-73** [comment]
Similar problem (`Unable to create DockerDesktopVM`).

My Docker works after opening Hyper-V Parameters (in Hyper-V Manager) and **setting correct paths** of Virtual Hard Disks and Virtual Machines.
