### ISSUE TITLE
Cannot stop container

### ISSUE THREAD

**Issue by ameeno** [docker/for-win#4475]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: BCD1E3B2-8DF6-4141-90C6-9B23CB230E78/20190808150637

### Expected behavior
Docker image shuts down (simple php image)
### Actual behavior
Docker image hangs and does not shut down
### Information

  - Windows Version: 1903 
  - Docker Desktop Version: 2.1.0.1 (37199) stable
 - Docker using windows containers and experimental features.

### Steps to reproduce the behavior

  1. Here is my Dockerfile:
    FROM php:7.2-apache
    COPY src/ /var/www/html/
    EXPOSE 80
 src/index.php :
<?php echo "Hello Docker" ?>
  2. docker build -t hello-world .
      docker run -p 12345:80 hello-world
       docker ps (find name of container)
     docker stop <container name>

nothing happens. same with docker kill

**Comment by mat007** [comment]
Sorry, for an unknown reason your diagnostics file never reached us.
Do you think you could try and send a fresh one?

**Comment by ameeno** [comment]
Thanks for getting back to me.

I managed to fix it myself before your response.

I had to shut down docker, disable on startup, & reboot.

then locate the docker container files on the windows machine,
and manually delete them.

This left downloaded images intact, but I deleted the running containers manually to make them stop.

**Comment by ameeno** [comment]
Just so you know, I faced the same problem again today where a container would not die gracefully and required major manual intervention when trying to use docker kill <container name> ect>

it seemed to finally die after when I collected the troubleshooting logs the docker died and crashed on windows.

Here is the diagnostic ID for the latest diagnostic issues:

maybe you can tell me what's wrong with my computer?
BCD1E3B2-8DF6-4141-90C6-9B23CB230E78/20190812102528

**Comment by joostmeijles** [comment]
Same problem here. After stopping Docker Desktop and removing all folders from `C:\ProgramData\Docker\containers` starting / stopping containers works again.

**Comment by mat007** [comment]
@ameeno again I am unable to find your diagnostics, maybe your firewall is blocking the upload or something?
Can you post the content of `%LOCALDATA%\Docker\log.txt`?
Sorry for the inconvenience…

**Comment by ameeno** [comment]
sure.

%Local data didn't resolve for me, but i found two files in AppData\Local\Docker\ that could be related.

they are attached. the 2nd one is bigger so i had to zip it, but should give an idea of my entire docker history.

[log.txt](https://github.com/docker/for-win/files/3492384/log.txt)


[log.0.txt.zip](https://github.com/docker/for-win/files/3492388/log.0.txt.zip)

**Comment by ameeno** [comment]
Hello. Can you tell me what my logs solay and why I can't stop containers?

They also become zombie containers when I reboot and don't respond and don't die.

So I cannot use this for development if the containers are unreliable.

**Comment by mat007** [comment]
From your log file
```
[12:55:58.370][WindowsDaemon     ][Error  ] Failed to delete container ce2199de34b77f91ff3cd475f8b129893093f046acceed517768296f2dcdb78d from containerd [error=no such container]
```
Seems to be similar to https://github.com/moby/moby/issues/39742 ?

**Comment by 8thHalfHour** [comment]
Same issue here today. Cannot stop containers on Docker Edge v2.1.1.0 bld37260 (Docker Engine v19.03.1), with the command `docker stop [container_name]`.  Diagnostics ID: 8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190816173619

Expected Result: container stops.
Actual: Command hangs
To exit the command, I uses `Ctrl-C`.

Using the command `docker kill [container_name]`: Diagnostics ID: 8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190816173854

Same expected results and actual results as stated above.

Additionally, removing the folders inside `C:\ProgramData\Docker\containers` did not fix the problem, it just removed my containers. I can't even blame this issue on running the WSL 2 Tech Preview engine running, because it still occurs when it is not started. Diagnostics ID (WSL engine not running): 8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190816180321

**Comment by clawrenceks** [comment]
Same issue here too. It is happening with great frequency too. 4 times in the last 2 days for me.

**Comment by clawrenceks** [comment]
This issue has a major impact on developer productivity in the latest version of Docker Desktop. Currently happening to me around 4 to 5 times a day at the moment. Constantly having to reboot is a huge issue.

Can I provide any diagnostics to assist in debugging? Is there any progress on a resolution?

**Comment by ta32** [comment]
i am running into this issue it is very frustrating.  Docker for windows - with windows containers feels unstable.
I saw two vmmem processes, one was suspended and one was running with 0 memory. I could not kill these process using task-manager either. I think this might be related

**Comment by ameeno** [comment]
I don't like Docker Hyper-v VM mode. it takes pointless resources, and is constrained, and i can just use my own hyper-V vm such as arch and expose kernels to do what docker desktop does.

All i need is A path variable and docker-cli for windows from chocolatey.


i don't even need docker desktop to do that.

The beauty of docker desktop is the LCOW function (Linux containers on Windows) built on top of the windows containers platform.

but the zombie container bug is preventing this big time.


No one from Docker-For-Win has proposed a solution, so i am perplexed.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/issues/39742 should be fixed in Docker Engine 19.03.2; is anyone still running into this issue with Docker Engine 19.03.2?

**Comment by clawrenceks** [comment]
@thaJeztah I am running Docker Engine 19.03.2 (just installed the latest Docker Desktop updates abount an hour ago) and this issue is definitely still happening.

**Comment by clawrenceks** [comment]
@thaJeztah - Is anything being done about this issue? Just completed my fifth restart of the day after clearing up zombie containers from the containers folder.

**Comment by ta32** [comment]
please post this on twitter to get visibility maybe that will help?

**Comment by Drewster727** [comment]
@thaJeztah I am seeing this as well in 19.03.2 -- in my case I have a swarm, with some windows 1903 worker nodes, when I drain the node it leaves the win containers around running.

**Comment by Felix-Indoing** [comment]
Same problems here with the latest windows version.

**Comment by ameeno** [comment]
Shame there is no fix.

Stopped using docker for windows.

**Comment by jtnord** [comment]
still observed in 2.0.4.1 (34207)

/remove-lifecycle stale

**Comment by jtnord** [comment]
I accidently removed the lifecycle/stale label as I realised I was on an older version than reported so adding back

/lifecycle stale
