### ISSUE TITLE
Traceroute on host machine not working anymore

### ISSUE THREAD

**Issue by MarcoMiltenburg** [docker/for-win#512]
Ever since I installed Docker for Windows yesterday, my tracert command shows strange results. This is a trace route to ww.google.nl on the host machine (not in a container):

![image](https://cloud.githubusercontent.com/assets/6213937/23154790/ea18922a-f80f-11e6-8cfb-f7c4412259d4.png)

This is what it looks like in a container:

![image](https://cloud.githubusercontent.com/assets/6213937/23155009/f4941854-f810-11e6-9c9b-2a438b04bc6b.png)

### Expected behavior
It should display all intermediate hops, at least the ones that acknowledge.

### Actual behavior
No hops are display, except for the last destination host. It looks like Docker does not allow the ICMP TTL exceeded messages to come back to the tracert command on the host.

### Information
Diagnostic ID: 4059120D-4BE5-475F-8A06-F45BA214E9C0/2017-02-21_08-31-25

### Steps to reproduce the behavior
1. Freshly rebooted machine
2. Open CMD prompt or PowerShell
3. Type: tracert www.google.nl

**Comment by friism** [comment]
ping @msabansal do see if he has suggestions.

I'm seeing the same thing on my machine.

**Comment by msabansal** [comment]
net stop winnat 

Is fixing the issue. Will investigate this once I can get cycles.

**Comment by onovotny** [comment]
I've been hitting this for months/year+ now, glad to see the root cause. Would really like to see this fixed.

**Comment by onovotny** [comment]
@msabansal Is there any ETA for this?

**Comment by maartenba** [comment]
Seeing the same issue, and indeed stopping `winnat` fixes it.

**Comment by artisticcheese** [comment]
Why there is still no progress on this issue? I'm pretty sure every single Windows admin out there now scratching their heads why traceroute is not working anymore with containers installed.

**Comment by msabansal** [comment]
@artisticcheese  This has been fixed for the next windows update. Sorry for not updating this thread

**Comment by artisticcheese** [comment]
Which specific Windows update are you refering to? @msabansal

**Comment by onovotny** [comment]
@artisticcheese @msabansal I am running 16251 and still see this issue if Winnat is running.

**Comment by msabansal** [comment]
Windows 10 Fall Creators Update (Redstone 3) 

@onovotny Which branch?  This was fixed recently. The fix might not have flowed to your branch. I can verify quickly

**Comment by onovotny** [comment]
I'm using the rs3_release branch. Very glad to hear it should be fixed soon!

**Comment by msabansal** [comment]
@onovotny I would expect another week for the fix to reach your branch. The payload was sitting in another branch because of some other issues.

**Comment by onovotny** [comment]
@msabansal unrelated to the traceroute issue but related to winnat, do you know if the localhost port sharing issue is fixed? ie, let me go to `localhost:8080` for a windows container? Today that only works for Linux containers and you have to use the container IP:port, which is really tedious.

**Comment by msabansal** [comment]
@onovotny Unfortunately this is not something we were trying to solve for RS3. Ping @Jmesser81

**Comment by artisticcheese** [comment]
@msabansal How about implementing docker swarm routing mesh, is it something being worked on or be implemented this year.

**Comment by JMesser81** [comment]
@onovotny - localhost communication will be fixed in our next coding milestone internally called RS4 which is targeted for release in Q2 of CY18. Routing Mesh is being worked on currently in the RS3 milestone

**Comment by JMesser81** [comment]
cc @artisticcheese @msabansal ^^

**Comment by artisticcheese** [comment]
I'm running Windows  2016 1607 14393.1198
I'm completely lost as far as what is RS2, RS3 etc. When RS3 is targeted to?

**Comment by OliverRC** [comment]
@JMesser81 that is great news. Not having localhost comms has forced us to completely halt any progress on using docker as we are unable to create working local environments to develop against.
