### ISSUE TITLE
No reload on file save

### ISSUE THREAD

**Issue by murphce** [docker/for-win#5212]
Hi,

I have a docker-compose which is resposible for running my application's UI, API and DB. My UI is built on React and I have mounted a volume so that I continue to develop the application. However, the UI does not update when I change any files (not even if I manually reload the page), I have used `docker exec` to verify that the files are being changed in the container.

The following is my docker-compose file:
```
version: '3'

services:
  ui:
    build: ./docker.dses-ui/
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./docker.dses-ui/dses-ui/src:/usr/src/app

  api:
    build: ./docker.dses-api/dses-api/.
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    build: ./docker.dses-db/postgres/.
    ports:
      - '5432:5432'
    expose: 
      - '5432'
```
Any help would be greatly appreciated.

**Comment by stephen-turner** [comment]
Thanks for the report. This is because Samba (which we use for file sharing) doesn't support event notifications. However, we have already developed a new solution based on FUSE, which should solve the problem. It's available on the Edge channel now, so if you switch to Edge, you should find that the reload works properly. Please do try it and let us now how you get on.

cc @djs55

**Comment by murphce** [comment]
I am working off the most recent version of Docker - but still experiencing the same issue.

**Comment by stephen-turner** [comment]
@murphce Are you on the Stable channel or the Edge channel? It's only in Edge right now.

**Comment by mat007** [comment]
@murphce also you need to make sure you have Experimental enabled.

![image](https://user-images.githubusercontent.com/2386884/69810305-de225480-11eb-11ea-82db-ec2e23013cb5.png)

**Comment by murphce** [comment]
I have installed docker from the following URL: https://docs.docker.com/docker-for-windows/edge-release-notes/ and have set experimental to be true - still facing the same issue.

**Comment by murphce** [comment]
The following is my output from `docker version`:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by djs55** [comment]
@murphce to make absolutely sure the new code is activated (sorry this is a bit complicated) could you run the following powershell command:
```
docker run -it -v C:\:/c --privileged --pid=host justincormack/nsenter1 /usr/bin/ctr -n services.linuxkit t exec -exec-id foo -t docker /bin/sh -c 'mount | grep host_mnt'
```
If the new code is enabled you should see something mentioning "grpcfuse" e.g.
```
grpcfuse on /host_mnt/c type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
whereas if the old code is still active it will mention "cifs"

**Comment by murphce** [comment]
That still did not work for me, however for anyone that experiences this issue, changing my start script in my package.json to `"start": "./node_modules/react-scripts/bin/react-scripts.js start"` solved the issue!
