### ISSUE TITLE
'MobyLinuxVM' failed to initialize

### ISSUE THREAD

**Issue by myfriend12** [docker/for-win#62]
I am getting the following error:

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

'MobyLinuxVM' failed to initialize.

'MobyLinuxVM' failed to start. (Virtual machine ID 4A21C237-D6E0-42D9-BB25-C09E0C414627)

'MobyLinuxVM' failed to initialize. (Virtual machine ID 4A21C237-D6E0-42D9-BB25-C09E0C414627)
at Start-MobyLinuxVM, <No file>: line 228
at <ScriptBlock>, <No file>: line 322
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.LinuxContainersEngine.DoStart(Settings settings)
   at Docker.Backend.LinuxContainersEngine.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostic ID: 34E4795C-2FA4-4167-88E5-05BE339614B2/2016-08-28_17-04-45

Running the latest beta running windows 10. Have been trying to get this to work with little to no success, even after researching. Would love to be able to start using it.

**Comment by dgageot** [comment]
@myfriend12 Thank you for reporting the issue! Can you please run this command from an **elevated shell** and tell us what's the output?

```
Start-VM -VMName MobyLinuxVM
```

**Comment by myfriend12** [comment]
I get the following error:

```
Start-VM : 'MobyLinuxVM' failed to start.
'MobyLinuxVM' failed to initialize.
'MobyLinuxVM' failed to start. (Virtual machine ID 4A21C237-D6E0-42D9-BB25-C09E0C414627)
'MobyLinuxVM' failed to initialize. (Virtual machine ID 4A21C237-D6E0-42D9-BB25-C09E0C414627)
At line:1 char:1
+ Start-VM -VMName MobyLinuxVM
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : AccessDenied,Microsoft.HyperV.PowerShell.Commands.StartVM

```

I also have the latest beta version running.

**Comment by myfriend12** [comment]
I ran the command in powershell with administrator permissions.

**Comment by rahilwazir** [comment]
I have the exact same issue

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 923FE888-20E5-4E96-8384-4D3A8BC74339)
at Start-MobyLinuxVM, <No file>: line 228
at <ScriptBlock>, <No file>: line 322
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.LinuxContainersEngine.DoStart(Settings settings)
   at Docker.Backend.LinuxContainersEngine.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Crash Report ID: `C141349B-6EE0-48C7-9FCE-F3B2342CEE1C/2016-09-06_00-15-08`

Also ran the following (in PS as administrator)
```
PS C:\WINDOWS\system32> Start-VM -VMName MobyLinuxVM
Start-VM : 'MobyLinuxVM' failed to start. (Virtual machine ID 923FE888-20E5-4E96-8384-4D3A8BC74339)
At line:1 char:1
+ Start-VM -VMName MobyLinuxVM
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : AccessDenied,Microsoft.HyperV.PowerShell.Commands.StartVM
```

OS: Windows 10 Pro 64bit, Hyper-V enabled
Docker: `1.12.1-beta24 (build: 6563)`

**Comment by friism** [comment]
@myfriend12 @rahilwazir it seems like you're encountering the error described here: https://blogs.technet.microsoft.com/rmilne/2014/01/15/hyper-v-could-not-initialize-could-not-create-or-access-saved-state-file/

Could you try the workaround described?

**Comment by myfriend12** [comment]
I did the following to the directory, .vmcx and .VMRS files in C:\ProgramData\Microsoft\Windows\Hyper-V\Virtual Machines and still get the same error. I have also gone into the permissions of each file and folder and given full permissions to everyone. Any other suggestions?

**Comment by dgageot** [comment]
@myfriend12 @rahilwazir Can you please try these commands from an **elevated Powershell**:

+ `cd 'C:\Program Files\Docker\Docker\resources'`
+ `.\MobyLinux.ps1 -Destroy`
+ `.\MobyLinux.ps1 -Create`
+ `.\MobyLinux.ps1 -Start`

**Comment by myfriend12** [comment]
Ran the commands, this is the result:

> PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Destroy
> .\MobyLinux.ps1 : File C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 cannot be loaded because running scripts
> is disabled on this system. For more information, see about_Execution_Policies at
> http://go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:1
> + .\MobyLinux.ps1 -Destroy
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
> PS C:\Program Files\Docker\Docker\resources> Set-ExecutionPolicy RemoteSigned
> 
> Execution Policy Change
> The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
> you to the security risks described in the about_Execution_Policies help topic at
> http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
> PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Destroy
> VM MobyLinuxVM is stopped
> Destroying Switch DockerNAT...
> Removing VM MobyLinuxVM...
> Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
> PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create
> Creating Switch: DockerNAT...
> Switch created.
> Set IP address on switch
> Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
> Creating VM MobyLinuxVM...
> VM created.
> PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Start
> Starting VM MobyLinuxVM...
> 'MobyLinuxVM' failed to start. (Virtual machine ID 82B795FD-BDD3-4A7F-A3EB-DCEF2396CECD)
> At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:332 char:5
> +     throw $_.Exception
> +     ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], VirtualizationException
>     + FullyQualifiedErrorId : 'MobyLinuxVM' failed to start. (Virtual machine ID 82B795FD-BDD3-4A7F-A3EB-DCEF2396CECD)

**Comment by rahilwazir** [comment]
@friism Still same error as mentioned by @myfriend12, I also had `.vmcx` and `.VMRS` files.

@dgageot Ran the command, here's the output:

```
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Destroy
.\MobyLinux.ps1 : File C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 cannot be loaded because running scripts
is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\MobyLinux.ps1 -Destroy
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create
.\MobyLinux.ps1 : File C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 cannot be loaded because running scripts
is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\MobyLinux.ps1 -Create
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Start
.\MobyLinux.ps1 : File C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 cannot be loaded because running scripts
is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\MobyLinux.ps1 -Start
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by dgageot** [comment]
@rahilwazir You should run ` Set-ExecutionPolicy -Scope Process Unrestricted` before, to allow the execution of Powershell scripts in your session.

**Comment by rahilwazir** [comment]
Ok so here's the output:

```
PS C:\Program Files\Docker\Docker\resources> Set-ExecutionPolicy -Scope Process Unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Destroy
VM MobyLinuxVM is stopped
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx

PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Creating VM MobyLinuxVM...
VM created.

PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Start
Starting VM MobyLinuxVM...
'MobyLinuxVM' failed to start. (Virtual machine ID FF39448C-339C-4CFF-8A05-D937D16790AE)
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:332 char:5
+     throw $_.Exception
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], VirtualizationException
    + FullyQualifiedErrorId : 'MobyLinuxVM' failed to start. (Virtual machine ID FF39448C-339C-4CFF-8A05-D937D16790AE)
```

**Comment by ruloweb** [comment]
I had a similar issue and solved it following this instructions: https://forums.docker.com/t/failed-to-create-vm-mobylinuxvm-cannot-find-an-overload-for-min-and-the-argument-count-2/17918

**Comment by rahilwazir** [comment]
@ruloweb Nope, it still appears to throw the same error, after deleting the existing `.vhdx` file and VM from Hyper-V Manager.

**Comment by myfriend12** [comment]
So just an update, I installed the latest beta 26 which enabled the option "Switch to Windows Containers" and after doing that docker was able to start, however, now I get the following error when I try to pull an image:

```
PS C:> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

c04b14da8d14: Extracting [==================================================>]    974 B/974 B
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: re-exec error: exit status 1: output:
 ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\0542d088387cd99e3ce26a9e5f4544dc7bfd5d05b9ae07619fa247a7a32ea63b:
The system cannot find the path specified..
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

What exactly does that switch to Windows/Linux containers do? I have looked to try to find information but can not find anything.

**Comment by dgageot** [comment]
@myfriend12 @rahilwazir I hope this issue is fixed in recent beta versions of Docker for Windows. Can you tell us if this is the case or not? In case no information is added, I'm going to close this issue in about a week.

**Comment by rahilwazir** [comment]
@dgageot No this issue still exist with same error posted above.

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 8FB98001-617F-45FB-9DCA-4F268AEC314D)
at Start-MobyLinuxVM, <No file>: line 262
at <ScriptBlock>, <No file>: line 363
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostic id: `C141349B-6EE0-48C7-9FCE-F3B2342CEE1C/2016-11-30_07-42-05`

**Comment by rneugeba** [comment]
@rahilwazir thanks for the diagnostics. In there I saw remnants of both VMware and VirtualBox with some of the VMware processes still running. I also see errors in the logs of the form:
```
Virtual Machine Worker Process initialization has timed out, and will terminate.
```
I suspect the error maybe due to either VMware or Virtual Box not being full un-installed. They do not work with Hyper-V. Could you try to uninstall these and try again?
Thanks

**Comment by rahilwazir** [comment]
@rneugeba Thanks for the suggestion.

I uninstalled both of them, the issue persists.

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 3C0FB0D8-6FB2-4DED-9F94-AA99ACBB8D81)
at Start-MobyLinuxVM, <No file>: line 276
at <ScriptBlock>, <No file>: line 368
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostic id: `C141349B-6EE0-48C7-9FCE-F3B2342CEE1C/2016-12-02_00-05-33`

**Comment by rneugeba** [comment]
@rahilwazir thanks for trying. I'm somewhat clutching at straws here as this looks like a Windows/Hyper-V issue with very little information available. The thing in the logs, which sticks out is the already mentioned:
```
Virtual Machine Worker Process initialization has timed out, and will terminate.
```
But, it doesn't really say why it timed out...

Microsoft suggests [here](https://technet.microsoft.com/en-us/library/dd581819(v=ws.10).aspx) to restart the service. Could you try that? I doubt it'll work, but worth a try.

The next thing you could try, is to disable Hyper-V completely (now that you removed VMware and VirtualBox), then reboot, then re-enable it and reboot again. You can disable Hyper-V via "Programs and Features" and then use the Windows features.

Finally, I found on [this thread](http://www.tenforums.com/tutorials/2087-hyper-v-virtualization-setup-use-windows-10-a-15.html), where someone had the same error message as you, that using:
```
net localgroup administrators

net localgroup administrators LOCAL /delete
net localgroup administrators SERVICE /delete
```
followed by a reboot fixed their issue. Could you try that as well?

**Comment by rahilwazir** [comment]
@rneugeba Thanks
I've tried with first two suggestions, and got no luck with them.

This solved the issue followed by reboot:
```
net localgroup administrators SERVICE /delete
```

Can you tell me is there any side effect? Seems like it removes localgroup `administrators` from group `SERVICE`. Sorry but I've no idea why this was required in the first place?

Again, thanks for the solution!

**Comment by rneugeba** [comment]
@rahilwazir To be honest,  have no idea. I just found this through googling and where this solution was discssed, people did not know why this worked but there were no other side effects reported.

glad it worked. Closing

**Comment by kapoorlakshya** [comment]
Just want to share what worked for me - https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class#1152468
