### ISSUE TITLE
Upgraded to 2.3.2.0, broke file binding. Can't start containers now. arrrgh

### ISSUE THREAD

**Issue by YouveGotMeowxy** [docker/for-win#6285]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2ECBE1F4-ADE2-4D97-8082-505598CFAE53/20200409214858

### Expected behavior

I'm able to mount the files.

I was on the last version before updating to 2230 and it would mount the files (config files). After updating, I get the errors in the screenshots below.

### Actual behavior

I'm not able to mount the files.

![image](https://user-images.githubusercontent.com/39491297/78943589-c7d1b280-7a81-11ea-850e-66c7050dfffe.png)

![image](https://user-images.githubusercontent.com/39491297/78943604-d0c28400-7a81-11ea-8175-e4a192ac83be.png)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

![image](https://user-images.githubusercontent.com/39491297/78943516-a375d600-7a81-11ea-8ebd-0508ffae6c51.png)

**Comment by YouveGotMeowxy** [comment]
... literally the worst support on the planet. Especially for such a popular product.

**Comment by mat007** [comment]
Thanks for the report, and very sorry we couldn’t reply sooner to provide you support for this free product.

This may be similar to #6209? It’s hard to tell without a bit of information in the «Steps to reproduce the behavior» field of the issue.
Can you tell us the command line you’re using or how you mount your folders?

**Comment by YouveGotMeowxy** [comment]
@mat007 Hi, sorry for sounding so frustrated, I know it's a free products, but I've come to depend on it and have spend countless hours now getting all these little tweaks and containers and settings going it gets frustrating when an update takes it down, and then no matter where I go for some assistance I just get crickets, and then just hope and pray that a new release that is who knows how far away will fix it.

**Here's the compose I use that contains the DNSCrypt Proxy error:**

```
version: "3"

services:

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: "redacted"
      ServerIP: "192.168.1.188"
      VIRTUAL_HOST: "192.168.1.188"
      IPv6: "false"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
    volumes:
       - 'pihole_data:/etc/pihole/'
       - 'pihole_dnsmasq_data:/etc/dnsmasq.d/'
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    cap_add:
      - NET_ADMIN
    networks:
      - pihole
    restart: unless-stopped

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    hostname: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    environment:
      TZ: 'America/Chicago'
    volumes:
      - '/f/Sites/DNSCrypt/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
    ports:
      - '5252:5053/udp'
    networks:
      - pihole
    restart: unless-stopped

volumes:
  pihole_data:
    external: true
  pihole_dnsmasq_data:
    external: true

networks:
  pihole:
    external:
      name: my-dns
```

**and for the compose that contains the MySQL error:**

```
version: '2'

services:

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - TZ='America/Chicago'
      - MYSQL_ROOT_PASSWORD="redacted"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - '/i/MySQL/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '3306:3306'
    command: "--default_authentication_plugin=mysql_native_password"
    networks:
      - odb

volumes:
  mysql_data:
    external: true

networks:
  odb:
    external:
      name: my-db
```

**Comment by mat007** [comment]
Does it work if you use Windows path style in your `volumes`, e.g.
```
    volumes:
      - f:/Sites/DNSCrypt/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml
```
```
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - i:/MySQL/my.cnf:/etc/mysql/my.cnf
```
?

**Comment by djs55** [comment]
@YouveGotMeowxy thanks for your report. Could you provide some more information to help me reproduce this -- could you provide a `docker-compose.yml` file or similar that I could try?

**Comment by djs55** [comment]
(sorry for posting an out-of-date comment here -- my web browser hadn't refreshed the page properly!)

**Comment by YouveGotMeowxy** [comment]
> Does it work if you use Windows path style in your `volumes`, e.g.
> 
> ```
>     volumes:
>       - f:/Sites/DNSCrypt/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml
> ```

Hi @mat007 

TY for trying to help me. :)

I just tried:

    'f:/Sites/DNSCrypt/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'

and get this error:

![image](https://user-images.githubusercontent.com/39491297/79411731-3a9eca00-7f69-11ea-8ae8-8038ad6a46ee.png)

One question that may or may not be related; I'm using Portainer to create this Compose stack, and it is still stuck using Compose version 2, so I'm setting the compose version to 2. Could that have anything to do with how it's handling the paths? i.e. would compose version 3 handle the Windows path style you're suggesting, but version 2 won't?

**Comment by mat007** [comment]
This seems to be working for me with a very recent build, could you try the version from the link suggested in https://github.com/docker/for-win/issues/6209#issuecomment-613515551 as we’ve fixed a very similar issue recently?

**Comment by YouveGotMeowxy** [comment]
@mat007 Unfortunately upgrading didn't help. I tried both path formats and get the same errors for both, respectively.

![image](https://user-images.githubusercontent.com/39491297/79513857-7d64ae80-800a-11ea-8213-ed8a8220dc16.png)

**Comment by YouveGotMeowxy** [comment]
I just upgraded to the latest version and still have the same issue

![image](https://user-images.githubusercontent.com/39491297/79762584-8e524000-82e8-11ea-9a67-de92cda7d09a.png)

**Comment by YouveGotMeowxy** [comment]
I'm wondering if it might have something to do with the periods (dots) in the paths, since I'm trying to mount files?  Similar to this: https://github.com/docker/for-linux/issues/675

From my understanding, there's been a lot of new work put into sharing, and the Resources/sharing has been overhauled, as well as some recent issues with parsing; I wonder if this is another parsing issue?

**Comment by mat007** [comment]
It might but we believed we had fixed those, maybe @djs55 would have some insight?

**Comment by YouveGotMeowxy** [comment]
Ok, I did a bit of sleuthing and it looks like it's some new compatibility issue with Portainer.

It used to work fine until the last Docker (Edge) update, but now for some reason the same compose code no longer works when trying to start up stacks using Portainer's stack editor.

However, copying and pasting that same exact code into a docker-compose.yml file and `up`ing, starts the containers no problem, using either path format.

I guess this is now just a Portainer issue and not a Docker issue, however, it does seem worth noting that it happened with a recent Docker update. So there's _something_ that happened there. :)

I'll leave it up to you guys on whether or not you want to close this issue.

**Comment by mat007** [comment]
Thanks for digging into it!
It’s still very odd as I would assume Portainer probably does a `docker-compose up` as well…
Have you created a ticket over there that you could like to/from here?

**Comment by mat007** [comment]
Ah I see you just did it, thanks!

**Comment by YouveGotMeowxy** [comment]
> Thanks for digging into it!
> It’s still very odd as I would assume Portainer probably does a `docker-compose up` as well…
> Have you created a ticket over there that you could like to/from here?

No problem (ish! :p).

From what I understand. Portainer uses a very old version of libcompose (or something like that) which is why their stack editor can only go up to version 2 max, while the latest compose is @3.8. So, I guess (again, a very uneducated guess!) maybe something in the latest docker changes broke some sort of compatibility with that old lib?

**Comment by simonferquel** [comment]
If you are deploying the compose file from portainer (instead of using docker-compose), you don't go through the proxy that translates paths from windows style to their equivalent from out VM point of view.

The path translation is an implementation detail and is subject to changes (it is even a bit different between Hyper-V and WSL 2 backends).

So to get the correct "linux path" for a given windows path, you can do something like:
```
$> docker create --name simon-mount -v c:\Users\simon:/simon alpine
$> docker inspect simon-mount
```
And look for how mounts got translated. 
For example, on my machine with WSL 2 backend, I can see:
```
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/run/desktop/mnt/host/c/Users/simon",
                "Destination": "/simon",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
You can see that in this case, the path that exposes c:\users\simon in the Linux VM is `/run/desktop/mnt/host/c/Users/simon`.

**Comment by YouveGotMeowxy** [comment]
Looks like in my Hyper-V backend it made them like this:

```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "mysql_data",
                "Source": "/var/lib/docker/volumes/mysql_data/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/i/MySQL/my.cnf",
                "Destination": "/etc/mysql/my.cnf",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Comment by mat007** [comment]
We now have a private build with a fix, if you would like to try: https://download-stage.docker.com/win/stable/45279/Docker%20Desktop%20Installer.exe
We will also make a new release in very likely a few days.
Thanks!

**Comment by mat007** [comment]
A fix has now been released in Docker Desktop Stable 3.2.0.3, I’ll go ahead and close this issue.
Thanks!
