### ISSUE TITLE
WSL2 error when shutdown.

### ISSUE THREAD

**Issue by Eji4h** [docker/for-win#6933]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: I can't upload diagnostics because it's not found problem.
![image](https://user-images.githubusercontent.com/7007629/83196497-353abf00-a166-11ea-935f-806a510bca40.png)
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Expected behavior
Should not show error when shutting down.

### Actual behavior
![wsl-error-when-shutdown](https://user-images.githubusercontent.com/7007629/83196083-72eb1800-a165-11ea-8c68-072a651d16c3.jpg)
Always error when shutting down Windows. But I can use everything fine.
com.docker.wsl-distro-proxy.exe - Application Error
The application was unable to start correctly (0xc0000142).

### Information
  - Is it reproducible?
  Always popup error when restart. I try to reinstall WSL2, Docker Desktop. But don't format my Windows.
  - Is the problem new?
  Already open issue at [WSL2 Docker error on system shutdown #6446](https://github.com/docker/for-win/issues/6446). But don't have any update.
  - Did the problem appear with an update?
  After migrate from WSL1 to WSL2

  - Windows Version: Windows 10 Pro 20H2 (OS build 19042.746)
  - Docker Desktop Version: 3.0.4 (51218)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
  No

### Steps to reproduce the behavior
  1. Run Docker from some terminal (PowerShell, WSL2).
  2. Shutdown or restart my computer.

**Comment by mmelvin0** [comment]
I have the same issue and was able to upload diagnostics. Diagnostics ID: 56EFB7E9-0159-4356-836D-7E928AA0C341/20200608165403

**Comment by fkiller** [comment]
Same here. C0532449-A6B7-400D-BCF2-A1926FB9C913/20200610031128

**Comment by anton-petrov** [comment]
Same error, Windows 10 Professional 2004

**Comment by yongzhang** [comment]
Same error, Windows 10 Professional 2004

**Comment by PepoBJ** [comment]
Same error, Windows 10 profesional 2004

**Comment by jpcuve** [comment]
Same error, Windows 10 Professional 2004

**Comment by 2259289435** [comment]
Same error, Windows 10 profesional 2004

**Comment by robece** [comment]
Same error, Windows 10 Enterprise 2004

**Comment by thanhquang1988** [comment]
Same errror with me, windows 10 pro 2004

**Comment by vssenko** [comment]
Me too on Windows 10 Home 2004, Docker 19.03.8, Docker desktop 2.3.0.3

**Comment by hapticPaper** [comment]
Same - W10 2004. I could swear I have the same software setup on an old i5 and dont get the error, but I do on my new ryzen 7.

**Comment by alexhackney** [comment]
Getting the same error, only when I shutdown my windows 10 pro 2004. It's on a clean install within the last week or so. Doesn't seem to affect anything but just disconcerting.

**Comment by iwritten** [comment]
ditto. as shutdown or restart is initiated. 

10 Pro. Version 20H2 (OS Build 19042.330)

**Comment by danztensai** [comment]
same here, getting the same rror, only when try to shutdown/ restart windows 10 pro 2004 
![image](https://user-images.githubusercontent.com/2839051/86114269-838c0680-baf4-11ea-9a9a-658b90a18b98.png)
cleaned install last week on I7 8th gen,  everything works normal after restart.

**Comment by lyona** [comment]
same as above, see it on shutdown after installing docker on 2004 win pro

**Comment by AlexZayats** [comment]
Same error, Windows 10 Pro 20H2

**Comment by joelteixeira** [comment]
Same erro on every restart. 
Windows 10 Pro 2004
Version 10.0.19041.329

**Comment by subjacked** [comment]
Same. Windows 10 Home 2004

**Comment by keyz182** [comment]
Windows 10 Pro - 20161.1000
Diagnostics ID: 26E3FC70-39AD-4855-BCA1-8C5D80B47F10/20200708091215

Anecdotally - this appears to be a security issue. On my system it seems to prevent windows update from running at all on reboot. If there are pending updates, I _have_ to manually shut down docker first or they never trigger.

**Comment by ielkhalloufi** [comment]
Same here (at shutdown).

Windows machine:

![image](https://user-images.githubusercontent.com/4039439/87228694-34bb5800-c3a3-11ea-910b-745c498a3993.png)

Error:

![20200711_181554](https://user-images.githubusercontent.com/4039439/87228779-b3b09080-c3a3-11ea-8771-80ee5d22d529.jpg)

**Comment by thomasvochten** [comment]
Same here...

**Comment by awpogodin** [comment]
Same here..
Windows 10 Pro (2004)

**Comment by leehanchung** [comment]
Same issue
Windows 10 Pro, Build 20161

**Comment by SardukarSilver** [comment]
Same here...

**Comment by lorentzyip** [comment]
Same here
Windows 10 Pro, Build 19041

![Capture](https://user-images.githubusercontent.com/1384476/88205433-5956e000-cc7f-11ea-874b-a7bf35d662c6.PNG)

**Comment by Seaniak** [comment]
Same here!

**Comment by mmichaelis** [comment]
And another "Same here". Happens since 2004 Update and letting Docker (it asked for it) activating WSL and switching to it.

This very same issue is tracked here (but to no avail, too): [The application was unable to start correctly on shutdown error message · Issue #5408 · microsoft/WSL](https://github.com/microsoft/WSL/issues/5408)

**Comment by eschrader** [comment]
I was able to fix my WSL.exe error by changing some docker settings, cleaning up a bunch of startup tasks, and uninstalling windows 10 OOTB apps that provided no value. Clean install of Windows 10 and started originally getting the error after switching from Hyper V to WSL.

**Docker settings**
**Uncheck** Send usage statistics

Then I removed the OOTB windows apps, such as Phone, Edge browser, Xbox game bar, etc. etc.

Then I went into Startup and removed Adobe creative cloud auto update stuff except for the Adobe Updater startup utility (basically I removed all High impact startup items except One Drive and Docker)

After that no more error. I even re-enabled send feedback on docker and still no more error. Maybe it was Edge or too much crap on startup running.

**Comment by nicopadu** [comment]
Same issue after fresh install.
Also tracked here https://github.com/microsoft/WSL/issues/5448

**Comment by utsxumiao** [comment]
Same issue here. Window 10 2004

**Comment by dharmeshsharma** [comment]
Same issue here. Window 10 2004. after updated latest

**Comment by yaodwwy** [comment]
The same problem ! 

com.docker.wsl-distro-proxy.exe
0xc0000142

**Comment by otakenz** [comment]
Same issue here. Window 10 Home 2004.

**Comment by roelkoops** [comment]
Same error, Windows 10 profesional 2004

**Comment by orojlo** [comment]
Same error, Windows 10 Enterprise 2004

**Comment by kitsunekyo** [comment]
bump. same issue. win 10 pro 2004 build 19041.450

**Comment by CodeBrotha** [comment]
Same issue here. Windows 10 Pro 19041.450

**Comment by yosri-ch** [comment]
Same issue. Windows 10 Entreprise N. Version 2004 build 19041.450

**Comment by CarlosLanderas** [comment]
Same issue.  Windows 10 Enterprise, Build 19041

**Comment by D3MaxT** [comment]
+1. Happens on both my desktop and laptop PCs.

Windows 10 Pro
2004
19041.450

Please fix.
Thank you.

**Comment by parin-s** [comment]
Same here. Happens when attempt to shutdown
Windows 10 Pro. Version 2004 build 19041.450

Run Docker on WSL

**Comment by mcgstar** [comment]
same here. Win 10 pro 2004

**Comment by Sunappnio** [comment]
same here. Win 10 pro 2004

**Comment by hangrymuppet** [comment]
Same issue here - reported diagnostics 6FBAD6A1-6F13-4C34-9EB8-AD9CF3F546E0/20200910175707

**Comment by steelcracker** [comment]
Same.
Workaround: If I right-click on the Docker icon in the system tray and choose to "Quit Docker Desktop", then no error pops out after that while shutting down the PC. I also stop all running containers before that just for the case, but maybe that's redundant.

**Comment by CodeBrotha** [comment]
> Same.
> Workaround: If I right-click on the Docker icon in the system tray and choose to "Quit Docker Desktop", then no error pops out after that while shutting down the PC. I also stop all running containers before that just for the case, but maybe that's redundant.

That's not really a good workaround as it requires manual intervention every time.

**Comment by im55cc** [comment]
我也遇到了这个问题，大概什么时候能解决呢？好烦人。

**Comment by Ephemeralis** [comment]
Same issue. Unsure if related, but I have to force a restart of WSL2 via ``wsl --shutdown`` before I am able to access any Windows filepaths via WSL again on the Ubuntu terminal, which happens exclusively on the reboot after this error occurs.

Ubuntu also complains of 3 zombie processes when this happens.

**Comment by reyo** [comment]
Same same. Had this problem since W10 2004 initially came out, march or april.

**Comment by onigunn** [comment]
Same here. Since Windows 2004 and enabling to WSL integration (obviously).

**Comment by jjavierdguezas** [comment]
same here 
Diagnostic ID: 94809D05-84C4-4906-A5E2-ABA7230198BC/20201007083452

> Windows specifications:
>- Edition: Windows 10 Pro
>- Version: 2004
>- Installed on: 10/02/2020
>- OS build: 19041.508
>- Experience: Windows Feature Experience Pack 120.2212.31.0


![image](https://user-images.githubusercontent.com/13673443/95308271-fb9f6080-0889-11eb-8291-d0736f48a2a6.png)

**Comment by jslow421** [comment]
Experiencing the issue as well. Has anyone had any luck with a solution that isn't disabling wsl2?

**Comment by steelcracker** [comment]
Seems like the problem had disappeared for me😅.
At least no such message (but now there's a sound when I restart as if a USB-stick is removed, dunno if it's even related or just some mine custom issue).

Can't tell the reason, so here's a guess-list:

- latest Docker-for-win version, `2.4.0.0 (48506) stable` ('autoupdates on' setting, or right-click on the tray icon and check for updates manually)
- since the last error encounter, I've installed everything listed at `Settings | Windows Update` (optional ones too, but not the ones under "View optional updates" button)
- `sudo apt update && sudo apt upgrade` for my default distro (Ubuntu 20.04.1 LTS) where the docker daemon lives I believe
- [_unlikely this one:_] for a while, I've turned off docker's autostart, launched it manually and used to "Quit Docker Desktop" before shutting down the PC (but now I've turned autostart on to test this out - still no errors)

**Comment by mendrik** [comment]
switching to docker beta channel solved it for me now

**Comment by CodeBrotha** [comment]
> Seems like the problem had disappeared for me😅.
> At least no such message (but now there's a sound when I restart as if a USB-stick is removed, dunno if it's even related or just some mine custom issue).
> 
> Can't tell the reason, so here's a guess-list:
> 
> * latest Docker-for-win version, `2.4.0.0 (48506) stable` ('autoupdates on' setting, or right-click on the tray icon and check for updates manually)
> * since the last error encounter, I've installed everything listed at `Settings | Windows Update` (optional ones too, but not the ones under "View optional updates" button)
> * `sudo apt update && sudo apt upgrade` for my default distro (Ubuntu 20.04.1 LTS) where the docker daemon lives I believe
> * [_unlikely this one:_] for a while, I've turned off docker's autostart, launched it manually and used to "Quit Docker Desktop" before shutting down the PC (but now I've turned autostart on to test this out - still no errors)

Problem still exists. You don't see it because you manually quit Docker Desktop before shutting down.

**Comment by boistordu** [comment]
I can confirm on last windows update so 10.0.19041.572 it still exists and it has been for nearly a year now. Can we expect a patch about it anytime soon?

**Comment by steelcracker** [comment]
@CodeBrotha 
> Problem still exists. You don't see it because you manually quit Docker Desktop before shutting down.
Nope, I did write _for a while_ about that. I use autostart for Docker now and I don't use manual quitting before shutting down anymore. Still no error both with running containers or stopped.

**Comment by CodeBrotha** [comment]
> @CodeBrotha
> 
> > Problem still exists. You don't see it because you manually quit Docker Desktop before shutting down.
> 
> Nope, I did write _for a while_ about that. I use autostart for Docker now and I don't use manual quitting before shutting down anymore. Still no error both with running containers or stopped.

Then you are quite fortunate. The issue still persists for the rest of us.

**Comment by Arukaito** [comment]
Same.. 
Always happens when i restart or Shutdown..
it is not disruptive, but i just dont like seeing errors like that,

**Comment by sam-stanford** [comment]
Same for me! Error when I shut down, and when I start up. ID: 28E9A062-BE50-4C3C-911F-39159B9FC3E4/20201108111602

**Comment by fferri** [comment]
Same issue here.

**Comment by eliveikis** [comment]
Same issue, since mid last year. It's a crash popup, quite distracting.

**Comment by tpsapp** [comment]
I am having the same issue on Windows 10 2004 build 19041.630 and docker version 2.5.0.1

**Comment by mmelvin0** [comment]
Since updating to Windows 10 20H2 and Docker Desktop 2.5.0.1, I no longer have this issue.

At the very least, it does not occur every time I reboot or shut down anymore. Previously this error consistent on every reboot or shut down when Docker Desktop was running.

**Comment by jslow421** [comment]
@mmelvin0 

> Since updating to Windows 10 20H2 and Docker Desktop 2.5.0.1, I no longer have this issue.
> 
> At the very least, it does not occur every time I reboot or shut down anymore. Previously this error consistent on every reboot or shut down when Docker Desktop was running.

Same setup here. I'm still getting the error myself, however it does seem like if I don't have a container running at the time of shutdown it doesn't always seem to happen.

**Comment by mmelvin0** [comment]
@jslow421 Weird. On my setup I _always_ have at least one container running that auto-starts with Docker Desktop, which starts with Windows.

**Comment by jslow421** [comment]
@mmelvin0 Thanks that's good to know. Thought I was on to something.

**Comment by tpsapp** [comment]
> I am having the same issue on Windows 10 2004 build 19041.630 and docker version 2.5.0.1

I reinstalled WSL 2 and also upgraded my Ubuntu WSL image to use version 2 and this seems to have resolved my issue.  This is the site that I used to upgrade the WSL version of my Ubuntu: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by christo-olivier** [comment]
Same issue here. Fresh install of Windows 10 2004 Version 10.0.19042 and docker version 2.5.0.1. Nothing mentioned above has solve the issue yet.

**Comment by mmelvin0** [comment]
It occurred on my system again. I did not make any software/configuration changes. Please disregard my previous two comments. See also #6848.

**Comment by SoulSeekkor** [comment]
Same issue here as well on Windows 10 Pro ever since enabled WSL2 integration for Docker.

**Comment by Fessant** [comment]
Had same issue. 
My solution for this issue was:
1) Open distro
2) type **exit**
3) reboot PC

**Comment by nuno-aj-aniceto** [comment]
Looks like an "Embrace Extend Exterminate" issue...

**Comment by twsl** [comment]
I also have this issue

**Comment by Azuki1029** [comment]
The error's from 'com.docker.wsl-distro-proxy.exe', who can be found running in taskmgr with a commandline like "...proxy.exe --distro-name "Ubuntu" --...".
After going through all Docker-related processes, I'm quite sure this proxy guy is the agent between Docker daemon and its target WSL2 instance, and if I shutdown all WSL2 instances by "wsl --shutdown", the proxy process would be gone while Docker frontend warns about this and asks if a restart is needed.
So what happens at OS shutdown/reboot can be:
1. wsl2 instances down
2. wsl2 platform service processes down, which makes it impossible to start wsl2 instances
3. docker daemon detects this "accident" but fails to send notifications because frontend process is down or active Win session is shutting down
4. docker daemon attempts to restart the wsl2 instances it needs to fix the "accident"
5. error occurs during agent (...proxy.exe) initialization, which is expected since the whole wsl2 platform is down
6. here comes the annoying error message from the agent, just before the screen goes dark
Thus a simple workaround can be "wsl --shutdown" (and "No" if Docker asks for restart) before shutdown/reboot.

**Comment by hapticPaper** [comment]
Kudos to working to find this out. it should not be necessary especially
after the issue has persisted this long. It may not block work, but it was
so avoidable, and seems to affect everyone.

**Comment by zifik** [comment]
I also have the same issue of the "com.docker.wsl-distro-proxy.exe - Application Error" dialog during shutdown.

**Comment by eabrega** [comment]
I also have this issue

**Comment by mbround18** [comment]
same issue

**Comment by MaxSbk** [comment]
I also have this issue

**Comment by boukeversteegh** [comment]
@eabrega 
> I also have this issue

@mbround18 
> same issue

@MaxSbk 
> I also have this issue

It will be more useful for the maintainers of this repository if you could react to the issue with a thumbs-up 👍.

Maintainers can sort issues by number of 👍 to get a sense of the size of the impact. The number of comments won't help a lot, but mostly create noise in the technical discussion of the issue.

**Comment by AlbanDurrheimer** [comment]
I also have this issue with Docker Desktop Version 3.0.4 (51218).
Please update the label.

**Comment by Eji4h** [comment]
> I also have this issue with Docker Desktop Version 3.0.4 (51218).
> Please update the label.

**Comment by boukeversteegh** [comment]
@Eji4h why did you close this issue?

The issue has had no resolution, but was the 2nd highest voted open issue on this repository. It's important for everyone that this issue remains open, so that the user-demand is visible to Docker developers/contributors.

If you's just like tonot receive notifications, I assume you get a lot of them, you could also unsubscribe and re-open the issue.

**Comment by Eji4h** [comment]
> @Eji4h why did you close this issue?
> 
> The issue has had no resolution, but was the 2nd highest voted open issue on this repository. It's important for everyone that this issue remains open, so that the user-demand is visible to Docker developers/contributors.
> 
> If you'd just like to not receive any more notifications - I assume you get a lot of them - you could also unsubscribe and re-open the issue.

Sorry for my mistake. It's accident.

**Comment by givihuda** [comment]
Happens often when shutting down, happened this time upon screen lock wake.

![image](https://user-images.githubusercontent.com/74785256/104771092-ed859980-572e-11eb-9074-38abb13d4c9d.png)

**Comment by prasannakumarkn** [comment]
I have the same issue. Pop us comes while shutting down the laptop.
happening after Installing Docker desktop

**Comment by boukeversteegh** [comment]
Please upvote the issue at the top instead of repeating "me too" as mentioned earlier. Please delete your comments as they don't add any new information.

**Comment by AlbanDurrheimer** [comment]
I’ve just looked at the readme and  I'm wondering if we shouldn't add the `kind/bug`, `area/windows` and `area/WSL2` labels to make it more visible.

Because there are more than 900 open issues, we need to increase visibility if we want the problem to be resolved.

**Comment by Eji4h** [comment]
> I’ve just looked at the readme and I'm wondering if we shouldn't add the `kind/bug`, `area/windows` and `area/WSL2` labels to make it more visible.
> 
> Because there are more than 900 open issues, we need to increase visibility if we want the problem to be resolved.

The issue template has been change from my create issue. I already update template.
Thank for tell me to know.

**Comment by avendael** [comment]
I also have this issue. No performance impact but it makes things look broken. Upvoted.

**Comment by iocron** [comment]
I have the same error message when I try to restart / shutdown the pc (I am on the latest Windows Version Build 19042.746 and Docker Engine 20.10.2).

**Comment by givihuda** [comment]
The issue isn't it just looking broken, it's that it could be an indication of a real problem that may have caused or could be causing other issues too that could manifest of increasingly strange behavior, like a car with a weird sound that you don't realize is causing other things to wear too much, and suddenly it dies and you've got a mess to fix.

**Comment by mnorrsken** [comment]
Same issue and it has caused me a lot of headaches because I thought it was my overclock doing it. I know I should have googled it earlier, but something like this should have been fixed long ago (even by just suppressing the popup).

**Comment by AlbanDurrheimer** [comment]
I just updated docker to 3.1.0 (51484) and the problem still exists.  
Please add it to the label :)

**Comment by sterlp** [comment]
+1 
Docker Engine
v20.10.2
Kubernetes
v1.19.3

**Comment by hapticPaper** [comment]
How is this still an open issue? Why isnt anything being done to address this? 
Why would something so prevalent make it through so many releases?

**Comment by dlangerm** [comment]
Piling on that I have had this issue for quite some time (over a year, I just decided to look it up today). Windows 10 Pro, multiple versions. WSL2.

This is just anecdotal, but sometimes if I don't remember to kill docker and WSL2 before shutting down, I can get weird startup behavior (monitor flashes, mouse hitching, etc.). Perhaps Windows sees an error upon shutdown which triggers alternate startup behavior. This doesn't seem to happen if I make sure to shut down docker and wsl before turning off or restarting.

**Comment by PermissionError** [comment]
> Piling on that I have had this issue for quite some time (over a year, I just decided to look it up today). Windows 10 Pro, multiple versions. WSL2.
> 
> This is just anecdotal, but sometimes if I don't remember to kill docker and WSL2 before shutting down, I can get weird startup behavior (monitor flashes, mouse hitching, etc.). Perhaps Windows sees an error upon shutdown which triggers alternate startup behavior. This doesn't seem to happen if I make sure to shut down docker and wsl before turning off or restarting.

I can second this. If I get the docker wsl "application was unable to start correctly" error, I tend to get a BSOD on next boot with "HYPERVISOR_ERROR" which fixes itself when I reboot again.

**Comment by CaringDev** [comment]
For me, disabling and re-enabling WSL integration in the settings fixed the problem:
![image](https://user-images.githubusercontent.com/421982/108496415-4904f300-72aa-11eb-82e1-a37250b743b9.png)

**Comment by CodeBrotha** [comment]
> For me, disabling and re-enabling WSL integration in the settings fixed the problem:
> ![image](https://user-images.githubusercontent.com/421982/108496415-4904f300-72aa-11eb-82e1-a37250b743b9.png)
> No Windows restart needed (but don't forget to `Apply & Restart`)

That doesn't fix anything. Problem returns on next reboot.

**Comment by CaringDev** [comment]
> > For me, disabling and re-enabling WSL integration in the settings fixed the problem:
> 
> > ![image](https://user-images.githubusercontent.com/421982/108496415-4904f300-72aa-11eb-82e1-a37250b743b9.png)
> 
> > No Windows restart needed (but don't forget to `Apply & Restart`)
> 
> 
> 
> That doesn't fix the issue, as you'll soon discover.

Indeed... it seemed to persist restarts but most likely I was too slow to notice the error dialog.

**Comment by stephen-turner** [comment]
This is fixed in versions 3.2.0 and 3.2.1. Closing the ticket now.
