### ISSUE TITLE
Internet access inside docker NAT network is very slow

### ISSUE THREAD

**Issue by gregpakes** [docker/for-win#698]
### Expected behavior

I would expect the internet speed inside a container to be comparable to the speed of the host.

### Actual behavior

I am finding the connection speed is extremely slow.

### Information

I am using this Speedtest script: [https://www.powershellgallery.com/packages/Speedtest/2.0/DisplayScript](https://www.powershellgallery.com/packages/Speedtest/2.0/DisplayScript)

**SpeedTest from Host**

![image](https://cloud.githubusercontent.com/assets/102243/25644971/66a0bd26-2fed-11e7-83b4-a47afa021fbb.png)

**SpeedTest from container** (it even times-out)

![image](https://cloud.githubusercontent.com/assets/102243/25645347/720e09a4-2ff0-11e7-8278-6552b070c91e.png)

**Comment by friism** [comment]
cc @kallie-b

**Comment by medianick** [comment]
Very similar here. On host (Windows 10, 1703, docker 17.03.1-ce):

![image](https://user-images.githubusercontent.com/329902/27436912-af02d668-572e-11e7-8422-2fda894c8a25.png)

On a fresh microsoft/windowsservercore container:

![image](https://user-images.githubusercontent.com/329902/27436937-c357314a-572e-11e7-9d5d-5d7e69e00555.png)

This is interfering with any sort of larger tool installations into containers over the network, e.g., via Chocolatey.

**Comment by friism** [comment]
pinging @kallie-b and @jmesser81 again

**Comment by kallie-b** [comment]
@gregpakes @medianick 

Thanks for this feedback--we know that container performance needs to be improved and it's always valuable to get explicit requests/comments on things like this directly from the community. I'll bring this back to my team, and I'll update you if they have any recommendations for action you can take to improve performance, especially in the short term.

**Comment by gregpakes** [comment]
@kallie-b 

Yes I still have the same issue.  I have to change how I do my dockerfiles to get around this issue.  I have to use the ADD syntax rather than using powershell to download and install components in the container itself.

I am currently on the stable version of docker, but the issue persists on the edge version too.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\greg.pakes> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
PS C:\Users\greg.pakes> docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 99
Server Version: 17.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.82 GiB
Name: iSAMS-LAP-GREG3
ID: H5EZ:EK42:BS6Y:FC3X:TRWA:YDP5:5RCT:ZZ3U:VJ7K:GTOC:C4Y5:ZDXK
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 19
 System Time: 2017-06-23T07:45:01.7394473+10:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
PS C:\Users\greg.pakes>
```

**Comment by kallie-b** [comment]
@gregpakes -- Thanks for the info.

So something that's playing a role here, is that you're running your containers in hyper-v isolation mode by default. If you're using Windows 10 as opposed to Windows Server, this is expected as hyper-v isolation is required when running containers on Windows 10. On Windows Server, however, you also have the option to run Windows containers without hyper-v isolation (e.g. `docker run -itd --isolation=process microsoft/nanoserver cmd`), which will improve your performance. Of course, that option is also less secure--so there's a tradeoff there.

Another way you can improve performance, is by using our transparent networking driver. The default driver is NAT (so, by default your containers are attached to the default `nat` container network on your host), but you can opt to connect your containers to a transparent network instead, for increased performance. [Here's a link to our docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking#windows-container-network-drivers), and a description of our Windows container networking drivers. To create a transparent network and connect a container to that network, you'd use the following syntax:

`docker network create -d transparent mytransparentdriver`
`docker run -itd --network=mytransparentdriver microsoft/nanoserver cmd`

**Comment by gregpakes** [comment]
@kallie-b 

Thanks for this.  I am aware of the isolation, but as you guessed I am using Windows 10, so have no option.  We use these containers in development, so can't always fallback onto Windows 2016.

Thanks for the tip regarding the transparent network.  This is useful, but actually my docker compose builds a private nat'd network (as this mimicks production) so changing this is not desirable.

Also, the biggest issue I have is during "docker build" (installing components from the web at build time).  Would the transparent network be used during build?

**Comment by kallie-b** [comment]
@gregpakes 

Yes, if you were to use the transparent network it would be used during build. 

So right now, since your containers are attached to the `nat` network, even during build all of the communication that they're having with the "outside world" is going through its `nat` endpoint, which unfortunately has high performance overhead. If you were to instead use the transparent network (at least during build time), your containers would communicate with the outside world through your transparent endpoint, which would increase performance and speed up your build time.

**Comment by kallie-b** [comment]
@gregpakes 

Also, I know that if you're running manual build commands you can specify a network with them that might be different to the network you'll use when actually running your containers (just use the `--network` option with the [`docker build` syntax](https://docs.docker.com/engine/reference/commandline/build/)). I haven't done this with Compose, but I'm sure there's an equivalent syntax.

**Comment by gregpakes** [comment]
@kallie-b 

Thanks for the workaround

**Comment by kallie-b** [comment]
No problem, let us know if that doesn't lessen your build time as expected.

**Comment by JMesser81** [comment]
@gregpakes @medianick - We recently found a few issues which may be related to the network performance problems you were experience. If you have an active repro, could you please run the following commands:

PS C:\> Get-netadpaterRSC | Disable-netadapterRSC
Reboot the host

When RSC (receive side coalescing) was on, some packets which violated MTU were indicated to winnat, which winnat dropped instead of processing correctly.

**Comment by gregpakes** [comment]
@JMesser81 Thanks for this.  I'll try it out and let you know when I am working with Docker next.

**Comment by medianick** [comment]
Unfortunately, that Speedtest.ps1 is giving me a 403 error now, so I have to find another repro. Will post an update here when I have one. Thanks @JMesser81!

**Comment by medianick** [comment]
@JMesser81, your fix appears to have done the trick. The following command, whether run in the host OS (WIndows Server 2016) or a `microsoft/windowsservercore` container, is returning equivalent results:

`curl -o nul http://speedtest.dallas.linode.com/100MB-dallas.bin`

This Dallas link, for example, is returning an average of ~30Mbps both in and outside the container.

I installed curl via [Chocolatey](https://chocolatey.org/packages/curl) to facilitate the test.

**Comment by patroza** [comment]
@JMesser81 typo, `Get-NetAdapterRSC`

**Comment by ljani** [comment]
My issues were fixed with @JMesser81's solution. I'd be interested how did you figure out this, Wireshark?

**Comment by LegitStack** [comment]
I'm still having this problem as well. Haven't tried the work arounds but I'm on windows 10 trying to use linux containers and get the same issue.

![image](https://user-images.githubusercontent.com/5642485/43845282-d7d105ac-9ae8-11e8-94a0-4d360fa6c7f4.png)

**Comment by mback2k** [comment]
I also experienced this low network performance issue on Windows Server containers with process-level isolation and WinNAT. Applying the suggestion of @JMesser81 and restarting the server fixed the issue and it is still working after one day of uptime. Therefore I would like to ask to add this requirement / feature disabling into the Docker setup routines.

**Comment by jhoneill** [comment]
Another case here of very slow running fixed by disabling RSC. If the it's not possible to turn off RSC in setup, it should at least be documented in an obvious way.

**Comment by dermeister0** [comment]
Is there any other network settings we should know about? Disabling RSC helped, but container network is still 3 times slower than on the host.

**Comment by shanalikhan** [comment]
same issue, any update on this ?

**Comment by zook-k** [comment]
same issue also, tried disabling RSC but still the same.
Is there any solution?

**Comment by turric4n** [comment]
same issue, but in my case I think is our top XCP (Xen Server) virtualization layer that is incompatible with WinNat.

**Comment by levimatheri** [comment]
@zook-k were you able to resolve this?

**Comment by zook-k** [comment]
nope, I moved to use a mac 😀

**Comment by patroza** [comment]
> 

What about WSL2?

**Comment by arcayi** [comment]
same issue. 
docker desktop on wsl2 in windows.
iperf3 result is OK to be above 970Mbps, between each others of wsl2 Ubuntu, host windows, a linux machine in the same LAN. but only 100Mbps between container and each of above OS. tried bridge and host network.

**Comment by jankap** [comment]
> @gregpakes @medianick - We recently found a few issues which may be related to the network performance problems you were experience. If you have an active repro, could you please run the following commands:
> 
> PS C:> Get-netadpaterRSC | Disable-netadapterRSC Reboot the host
> 
> When RSC (receive side coalescing) was on, some packets which violated MTU were indicated to winnat, which winnat dropped instead of processing correctly.

Another one here where this setting fixed the issue and increased the transfer speed by x200. Thank you!

**Comment by arcayi** [comment]
do you mean
Get-NetAdapterRsc | Disable-NetAdapterRsc ?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月23日(星期一) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [docker/for-win] Internet access inside docker NAT network is very slow (#698)





  
@gregpakes @medianick - We recently found a few issues which may be related to the network performance problems you were experience. If you have an active repro, could you please run the following commands:
 
PS C:&gt; Get-netadpaterRSC | Disable-netadapterRSC Reboot the host
 
When RSC (receive side coalescing) was on, some packets which violated MTU were indicated to winnat, which winnat dropped instead of processing correctly.
  
Another one here where this setting fixed the issue and increased the transfer speed by x200. Thank you!

**Comment by sithtoast** [comment]
i've also been experiencing speeds 1/10th of my typical speed inside of my container network. I have tried the RSC fix and it looks like it only effects my wifi adapter. Is there a way to use that adapter for comms instead of wired ethernet?

**Comment by cristoslc** [comment]
Windows 11 host with Linux (Alpine + Ubuntu) containers. Seeing download speeds about 50% of the host's but upload speeds match the host. The `Get-NetAdapterRsc | Disable-NetAdapterRsc` fix did not help.
