### ISSUE TITLE
error during connect: Get http://127.0.0.1:2375/v1.27/containers/json

### ISSUE THREAD

**Issue by lbottoni** [docker/for-win#741]
### Information

  - 2C8676B0-4EAB-436E-B99F-6DB9196258D7/2017-05-12_08-35-57
  - open cmd, send command "docker ps"
  - window 10

### Steps to reproduce the behavior

  1. open cli
  2. docker ps

hi after uptdate docker (before worked fine!) i have this error (all action same issue)

> C:\wamp\www\nc>docker ps
error during connect: Get http://127.0.0.1:2375/v1.27/containers/json: dial tcp 127.0.0.1:2375: connectex: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.

**Comment by dgageot** [comment]
Hi @lbottoni can you share the output of `docker version`?

**Comment by icechair** [comment]
i have the same Problem. here is my output of `docker version`

```
PS H:\> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
error during connect: Get http://127.0.0.1:2375/v1.27/version: dial tcp 127.0.0.1:2375: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
```

When I enable `Expose daemon on tcp://localhost:2375 without TLS` under `Settings -> General` the commands are working:
```
PS H:\> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

PS H:\> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS
NAMES
```

**Comment by rn** [comment]
closing old issues

**Comment by lbottoni** [comment]
ok old problem, but the solution link???!?!?

**Comment by lbottoni** [comment]
resolved
----------------------------
- click on docker icon
- settings
- flag on expose deamon on tcp://localhost:2375 without TLS
- apply

**Comment by theasteve** [comment]
I'm also getting the same error:
`docker version`
```Client:
 Version:	18.04.0-ce
 API version:	1.37
 Go version:	go1.10.1
 Git commit:	3d479c0
 Built:	unknown-buildtime
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm
error during connect: Get http://127.0.0.1:2375/v1.37/version: read tcp 127.0.0.1:50709->127.0.0.1:2375: read: connection reset by peer```

I unset TLS

>  $ unset DOCKER_TLS_VERIFY
>  $ unset DOCKER_CERT_PATH
>  $ export DOCKER_HOST=tcp://127.0.0.1:2375


However if I still run `docker info` I still get ```error during connect: Get http://127.0.0.1:2375/v1.37/info```

**Comment by rn** [comment]
@theasteve 
Under `Settings->General` do you have `Expose daemon on tcp://localhost:2375 without TLS` enabled? You need to if you want to access the daemon as described. But please do keep in mind that this setting is *insecure* as explained in the warning.

**Comment by kumarharsh** [comment]
@rn It's not working for me too. I have checked the `Expose daemon on tcp://localhost:2375 without TLS` option in Docker settings.

Notably, if I set an incorrect `DOCKER_HOST` environment variable, I get this error:
```
$> export DOCKER_HOST="tcp://localhost:2376"
$> docker info
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
```

Which is kind-of equivalent to docker-for-windows not exposing the daemon on a port, correct?

But then I set the correct env variable:
```
$> export DOCKER_HOST="tcp://localhost:2375"
$> docker info
error during connect: Get http://localhost:2375/v1.39/info: EOF
```

So it's at least connecting initially, but after the first connection, it's somehow dropping the conn. Please reopen the issue.

**Comment by pratikzingade** [comment]
I had the same issue, although my `Expose daemon on tcp://localhost:2375 without TLS` was enabled. I just tried restarting docker and it started running fine.
