### ISSUE TITLE
Docker on Startup gives error.

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [docker/for-win#7691]
I have installed Docker Desktop on my Windows machine. I use WSL. Whenever I start my machine, The Docker desktop gives an error and fails to startup. My log files are as Follows:
```
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The Windows Subsystem for Linux instance has terminated.


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

```

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD33EFC3-508E-4213-967A-A7B60AC77E61/20200716084048

### Expected behavior

I expected Docker to start normally in both WSL and Native Windows.

### Actual behavior

Docker Crashes

### Information

  - Windows Version: Win10 Version 2004 OS Build 19041.329
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...Whenever I start my Windows.

**Comment by SrinivasaDK** [comment]
I have also have the same issue, Please advice. 
Diagnostics were uploaded with id:
47C2312F-D2F3-47D9-9B8C-3AA43088B155/20200716130446

**Comment by SrinivasaDK** [comment]
My issue has been fixed once I manually update the Linux kernel inside of WSL 2. As per the instruction in the link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by agarwalvaibhav0211** [comment]
@SrinivasaDK I have already updated my WSL Kernel. The Problem was not resolved

**Comment by narwy** [comment]
@agarwalvaibhav0211 You need to enable WSL2 + set a distro. That's the issue.

**Comment by agarwalvaibhav0211** [comment]
@narwy I already have Installed ubuntu. AND my WSL is version. I run docker from WSL itself, so I don't think it's that issue. Apart from that once this error comes, then i close the error log, and start docker desktop manually, it starts. This is a workaround. But what is the issue itself? Is this a known issue and currently being worked upon??

**Comment by agarwalvaibhav0211** [comment]
Well it is working after I disabled fast startup in windows. Does anybody know why this was happening?
