### ISSUE TITLE
WSL2 integration seems to be broken

### ISSUE THREAD

**Issue by cwoolum** [docker/for-win#7995]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 057544A3-14DE-4A20-9CAF-0E90D44EADFA/20200807162315

### Expected behavior

When opening the Ubuntu WSL prompt, I should be able to run `docker ps` to view available containers.

### Actual behavior

An error is thrown

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Information

  - Windows Version: 19042.423
  - Docker Desktop Version: 2.3.4.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Ubuntu in WSL 2 mode.
  2. Enable WSL2 integration.
  3. Restart the machine

I have tried fully resetting Docker for Windows. `docker ps` does work in Windows.

![image](https://user-images.githubusercontent.com/942415/89667209-98488080-d890-11ea-8d62-40b6a11e8d56.png)

![image](https://user-images.githubusercontent.com/942415/89667259-ab5b5080-d890-11ea-92e6-20e206111ab7.png)

**Comment by GustavR** [comment]
Just ran into this issue today after updating to latest Docker Desktop 2.3.5.0 (Edge Channel).
Are there any news on this? Were you able to resolve your problem?

**Comment by cwoolum** [comment]
Reverting to 2.3.4.0 does not fix the issue.

**Comment by cwoolum** [comment]
Fixed with 2.3.5.1

**Comment by Mistic92** [comment]
It's still crashing for me
90397157-8ED2-4369-A30E-BE5F9C77A7B2/20200827080640
```
WSL distro stopped while waiting for Lifecycle server.
  >Stdout:

  >Stderr:
2020/08/27 08:11:41 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
2020/08/27 08:11:41 copying...
Error: mounting wslCLIDest: open /mnt/host/wsl/docker-desktop-data/isocache/a08c12d3e273772f412bc0f786af6caf7193ccab28a7efb763be192376e82ed0.iso: input/output error
2020/08/27 08:11:41 open /mnt/host/wsl/docker-desktop-data/isocache/a08c12d3e273772f412bc0f786af6caf7193ccab28a7efb763be192376e82ed0.iso: input/output error
mounting wslCLIDest
main.doRun
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:224
main.run.func1
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:83
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:838
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:943
github.com/docker/pinata/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/github.com/docker/pinata/vendor/github.com/spf13/cobra/command.go:883
main.main
	/go/src/github.com/docker/pinata/linuxkit/pkg/wsl-bootstrap/main.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```
