### ISSUE TITLE
Unable to share drives

### ISSUE THREAD

**Issue by dimitriadams** [docker/for-win#803]
### Expected behavior
C drive is shared
### Actual behavior
C drive isn't shared
### Information

  - Diagnostic ID 9159A2D9-E77A-4FC2-93B7-532785D767A3/2017-06-08_10-40-44
  - Docker Version: 17.03.1-cd
  - OS: Windows 10 Enterprise
  
### Steps to reproduce the behavior

  1. In Docker For Windows select Shared Drives
  2. Click 'Reset credentials'
  3. Select C Drive
  4. Click Apply
  5. Enter credentials
  6. The C Drive is unselected again....

**Comment by lgrepo** [comment]
Related to #690 
QuickFix: reinstall docker4win, if that doesn't help uninstall again and switch to edge-channel version

**Comment by dimitriadams** [comment]
I uninstalled docker4win, rebooted, installed the edge-channel, rebooted, tried to share again but still no success. The logfiles shows that mounting seems to be successfull with SambaShare, but with NamedPipes it gives an error: Key already exists in dictionary...
[dockerlog.txt](https://github.com/docker/for-win/files/1063186/dockerlog.txt)

**Comment by jasonbivins** [comment]
I tested this again, and was able to share my C: drive in the latest edge build, where I wasn't able to on the stable build.  

Have you tried the reset function?  Try resetting to the factory default

![image](https://user-images.githubusercontent.com/28021664/26989319-9868b05c-4d20-11e7-9ccb-153ceb61b111.png)

**Comment by dimitriadams** [comment]
Just tried the 'Reset to factory defaults', but still no sharing

**Comment by gesch** [comment]
Having the same issue with stable and edge. Tried different combinations of installs, resets and reboots. No Luck yet. Currently It is not possible to share any drive on windows.

**Comment by patelmaulik** [comment]
Same issue on Win10 Pro. Tried everything in the book

1. re-installing file & print sharing, re-installing drivers
2. manually opening ports although docker has already added firewall rule
3. reset, reboot etc..etc
4. edge & stable channel

Still no joy with shared drives.

**Comment by mohahn** [comment]
The same here. Using

- Docker 17.03.1-ce-win12 (12058)
- Windows 10 Pro, latest Version 1703 (Creators Update)

It seems a bit reproducable for me. Perhaps anyone can confirm this. After every re-install of Docker or "Resetting to Factory Defaults" I can add a shared drive, by providing credentials. But when adding another drive or disable and re-enable existing share, the same behaviour as above happens: after providing credentials when clicking "Apply" the shared drives are unselected again.
I want to mention, that Docker from Edge channel does *not* work for me, as it fails on building image with error `oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"` (could be related to [this](https://github.com/linuxkit/linuxkit/issues/1991))

What seems to work for me is: first, share complete drive in Windows explorer (via extended share, in german: "Erweiterte Freigabe") with all permissions to admin only. After that I can add this drive in Docker settings without error. Can anyone confirm this?

**Comment by jasonbivins** [comment]
Hi @dimitriadams @mohahn   This is an issue in the Stable build - have you tried the latest Edge build?  We just released one earlier today, 17.06 rc4 that should resolve this for you. Please try it and let me know how it goes.

**Comment by dimitriadams** [comment]
I just installed the 17.06 rc4 version but still the same results. I did a 'Reset to factory defaults' to be sure but no shared drives.... :-(

**Comment by mohahn** [comment]
@jasonbivins have u read, that after installing Edge a build of images fail? Nevertheless, even with Edge, after fresh install I can add a share (like in Stable) but when editing a share or adding a new one, all shares are disabled again. For me the same behaviour like in Stable.

**Comment by pavelmaca** [comment]
Docker Version: 17.06 rc5

Mine Windows account is linked to the Microsft. In the  lusrmgr.msc i can see that user password is marked as "User must change password at next logon" and this option can't be changed.

This worked for me as workaround:
Create a new local windows user with password and add it to Administrators group.
Use this account to create shared drives.

**Comment by lgrepo** [comment]
I got this issue again, after changing my password on windows. And i remember this was also the case when i got this issue last time. I'm requested to change my password every 2-3 months for security reasons. Looks like i have to reinstall Docker again.

While the suggested solution from @pavelmaca might work there will still be users (like me) who can not simply create a new user on their system. Docker should not corrupt shared drives when the user password has changed. Imo docker should somehow notice that the password has changed and ask for the new password to allow the shared drives. Or atleast uncheck the shared drives so a user can spot the problem and then check the drive again + authentication.

**Comment by Dargmuesli** [comment]
Try the newest Edge build. Version 17.06.1-ce-rc1-win20 (12818). The issue is fixed for me there.

**Comment by dimitriadams** [comment]
I just tried the new Edge build, still no luck in sharing drives.

**Comment by liri2006** [comment]
Faced the same issue, even with Edge build. Providing credentials of other admin user indeed works, but in this case this "other" user should have access to current users's folder in C:/Users/{currentUser}

**Comment by kirisky** [comment]
I ran into the same problem today. 
My environment is Windows 10 Pro and docker for windows.
My port 445 is blocked by the firewall. I tried many methods, but they didn't work. 
Then I found my firewall has two "block the connection" rules. They banned port 137, 139, 445 and 3389.
The rules' names are "20170415漏洞" and "20170415漏洞UDP".  
So, I opened the window of the rules‘ property and turned on the "local principals" tab. 
Then, I added my windows account to the "Exception." 
Finally, I solved this problem. 
The problem spends some time of mine.
I hope my experience could help someone.

**Comment by kumarharsh** [comment]
Still happens to me. I have a PIN set, but docker keeps asking for password on mounting drives. If I shut down docker and restart it, docker lets me mount the drive without asking for password again.

**Comment by dashesy** [comment]
Same as @kumarharsh  After restarting the docker the drive is shared without askign for password!

**Comment by namnh06** [comment]
I knew what happen guys.

In my case, after remove xampp in my computer, I can not share drives any more. It's block the 445 port, guess that.

Just find this one and disable it !

![disable-445](https://user-images.githubusercontent.com/28762252/39950824-74c9379c-55ae-11e8-9818-f6144a140d88.PNG)

**Comment by rafabaldoni** [comment]
This tutorial worked for me!

http://peterjohnlightfoot.com/docker-for-windows-on-hyper-v-fix-the-host-volume-sharing-issue/

**Comment by arashsofts** [comment]
SOLUTION for Windows Users: 

Guys go to docker's settings click on sharing and click on the checkbox next to the c drive and it'll ask u for a password u must have the admin's privileges and try to add a new rule on windows defender to accept requests on port 445 and if that doesn't work than you might have an antivirus program that's blocking it.

**Comment by besil** [comment]
reset to factory settings worked for me

**Comment by Yavdhesh** [comment]
I had to reset it to factory defaults. 
restarted, then checked those drive, it worked.
मुझे फेक्टरी डीफोल्ट करना पडा।
पुन: शुरु किया, तब ड्राईव साझा हो गया ।

**Comment by Twosmiles** [comment]
I've tried each and every recommendation here and in other issue trackers. My problem was that the windows service called "Server" (Thank you microsoft for that) was not running and actually deactivated.
After starting it, the sharing worked just fine

**Comment by Fieel** [comment]
I got a popup after running  `docker-compose up - nginx mysql`, inserted my microsoft account credentials and it worked. I had to try multiple times, though.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
