### ISSUE TITLE
Frequest DRIVER_CORRUPTED_EXPOOL blue screens

### ISSUE THREAD

**Issue by roelkok** [docker/for-win#913]
Lately I've been getting frequent (4 in a week) BSODs with DRIVER_CORRUPTED_EXPOOL at seemingly random times. Memory dump analysis says it's probably caused by `vpnkit.exe`.

It's hard to reproduce as it seems to occur at random times, not a specific user initiated event.

- Diagnostic id : `9DB2E177-CB3C-4D31-BED5-E1C44F50459A/2017-07-11_21-12-28`
- I'm using this Dockerfile: [https://github.com/nimmis/docker-apache-php7](https://github.com/nimmis/docker-apache-php7)
- OS: Windows 10.0.15063

Analysis from the memory dump
```
BugCheck C5, {8, 2, 0, fffff8011c49ca64}
Probably caused by : vmbusr.sys ( vmbusr!PipeCreate+2b )

THREAD ffffc60515699700  Cid 378c.5fc8  Teb: 00000000002fd000 Win32Thread: 0000000000000000 RUNNING on processor 1
IRP List:
    ffffc6052d77cb80: (0006,0478) Flags: 00060000  Mdl: 00000000
Not impersonating
GetUlongFromAddress: unable to read from fffff8011c55a2d4
Owning Process            ffffc60520fd6540       Image:         vpnkit.exe
```

I'm now trying to a container from a different image to see if the issue persists.

**Comment by jasonbivins** [comment]
Hi @roelkok 
Let's try to remove Docker, Hyper-V and the containers feature completely, then reinstall.  You might also want to double check your event viewer and device manager. I did see a couple of I/O timeouts in the logs.  Run the below script - then remove Hyper-V and the Containers features in windows - reboot then reinstall Hyper-V, then Containers then reinstall Docker.

$ErrorActionPreference = "SilentlyContinue"

kill -force -processname 'Docker for Windows', com.docker.db, vpnkit, com.docker.proxy, com.docker.9pdb, moby-diag-dl, dockerd

try {
    ./MobyLinux.ps1 -Destroy
} Catch {}

$service = Get-WmiObject -Class Win32_Service -Filter "Name='com.docker.service'"
if ($service) { $service.StopService() }
if ($service) { $service.Delete() }
Start-Sleep -s 5
Remove-Item -Recurse -Force "~/AppData/Local/Docker"
Remove-Item -Recurse -Force "~/AppData/Roaming/Docker"
if (Test-Path "C:\ProgramData\Docker") { takeown.exe /F "C:\ProgramData\Docker" /R /A /D Y }
if (Test-Path "C:\ProgramData\Docker") { icacls "C:\ProgramData\Docker\" /T /C /grant Administrators:F }
Remove-Item -Recurse -Force "C:\ProgramData\Docker"
Remove-Item -Recurse -Force "C:\Program Files\Docker"
Remove-Item -Recurse -Force "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Docker"
Remove-Item -Force "C:\Users\Public\Desktop\Docker for Windows.lnk"
Get-ChildItem HKLM:\software\microsoft\windows\currentversion\uninstall | % {Get-ItemProperty $_.PSPath}  | ? { $_.DisplayName -eq "Docker" } | Remove-Item -Recurse -Force
Get-ChildItem HKLM:\software\classes\installer\products | % {Get-ItemProperty $_.pspath} | ? { $_.ProductName -eq "Docker" } | Remove-Item -Recurse -Force
Get-Item 'HKLM:\software\Docker Inc.' | Remove-Item -Recurse -Force
Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\Run -name "Docker for Windows" | Remove-Item -Recurse -Force
#Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\UFH\SHC | ForEach-Object {Get-ItemProperty $_.PSPath} | Where-Object { $_.ToString().Contains("Docker for Windows.exe") } | Remove-Item -Recurse -Force $_.PSPath
#Get-ItemProperty HKCU:\software\microsoft\windows\currentversion\UFH\SHC | Where-Object { $(Get-ItemPropertyValue $_) -Contains "Docker" }

**Comment by MrGekko** [comment]
I am having the same issues. But I get the BSOD 4 times a day.
I don't really know how to run the above script though, it seems like its being formatted by Github.

My Diagnostics: EF02D507-FC51-4599-8ACA-0DC588D8F12C/2017-07-19_09-28-10
OS: Windows 10 1703 Build 15063.483

**Comment by bachratyg** [comment]
Same here. Started exactly the same time when I started using Docker4Win. I used Hyper-V before with no problems. The BSOD is most likely to happen when I start debugging an app in a linux container.

**Comment by jasonbivins** [comment]
@MrGekko   Can you please send another diagnostic? I'm having a hard time finding that one
@bachratyg  Can you please send a diagnostic ID as well?  Right-click the Whale icon - then choose diagnose and feedback

**Comment by PabloMessina** [comment]
I'm facing the same problem. I have an ASUS ZenBook Pro UX501 with Windows 10, a few days ago I upgraded from Home to Pro in order to use Hyper-V, then downloaded and installed Docker for Windows and yesterday I've been running a cpu intensive process within an Ubuntu 16 container (I have a python script in Windows which sends a lot of requests through localhost to a flask server in the container,  the server runs a cpu intensive process to handle the request and then sends the results back to Windows, this is repeated thousands of times). I've had 2 DRIVER_CORRUPTED_EXPOOL blue screens during the execution of the script.

**Comment by MrGekko** [comment]
EF02D507-FC51-4599-8ACA-0DC588D8F12C/2017-07-21_15-13-16
@jasonbivins Thanks for looking into this!

**Comment by PabloMessina** [comment]
In my case, based on the 2 minidumps above the suspicious processes are vpnkit.exe and WmiPrvSE.exe. In both cases there is a WIN8_DRIVER_FAULT, which I don't understand (why WIN8 if my laptop came shipped with Windows 10 from the start?)

**Comment by PabloMessina** [comment]
I just uninstalled Docker for Windows, disabled Hyper-V, rebooted my laptop, reenabled Hyper-V, rebooted again, then reinstalled Docker for Windows again and then proceeded to set up and run the Windows-to-Container intercommunication scenario I explained in my previous comment, which looked like this:

![image](https://user-images.githubusercontent.com/6187545/28487202-fc629f32-6e59-11e7-980e-a3d79c4385f8.png)

As you can see, I was running a python script in a Jupyter Notebook in Windows 10, which was sending requests and receiving back responses from a flask server within an Ubuntu 16 container (see logs in the command prompt). This setting was doing fine ... for a while, until a new third DRIVER_CORRUPTED_EXPOOL BSOD suddenly arose again.

## MINIDUMP
![image](https://user-images.githubusercontent.com/6187545/28487231-a30ae4b6-6e5a-11e7-814d-cd889d29edc7.png)
full minidump: https://drive.google.com/file/d/0B42QoVvPwhLkeUR3TUM4cnd5NG8/view?usp=sharing

## Docker's Diagnostic:
A22602E2-3D7E-4A44-88C9-A6B83FC54F9D/2017-07-21_21-08-35


An interesting point made in the minidump troubleshooting suggestion is to run the "driver verifier" against any new (or suspect) drivers. Does anybody know which drivers should I run driver verifier against, how do I exactly do that?

**Comment by bachratyg** [comment]
@jasonbivins
23253D8E-43E5-453F-9B98-ADD19A2A0037/2017-07-22_18-04-58

Last dump analysis shows culprit as vmbusr.sys ( vmbusr!PipeCreate+2b ), process vpnkit.exe, consistent with the initial post.

Just noticed that installation of KB4025342 was consequently failing so I downloaded it from the catalog and installed manually. No BSOD in the last 1,5 hours, though I'm still holding my breath.

**Comment by elmarlg** [comment]
I can confirm the exact same issue. This can range from hours to days. On one occasion it happened 3 times in 1 day. It seems that the issue occurs after a container is started (in my case it is Dotnet core container which is in fact a Debian 8 container). This has happened on 3 different Windows machines. The same issue did not occur when I was running Linux (I used Debian and Ubuntu hosts).

**Comment by creyke** [comment]
Same for me. Three times today so far. I'm also using .NET Core containers although I doubt that's the trigger.

**Comment by justincormack** [comment]
Looks like it might be related to hyper-v sock drivers? cc @rn

**Comment by rn** [comment]
@roelkok The line:
```
Probably caused by : vmbusr.sys ( vmbusr!PipeCreate+2b )
```
seems the relevant here. `vmbusr.sys` is the Virtual Machine Bus Root Driver which, i think, is responsible for host to VM communication and the crash is in a function called `PipeCreate()`. The process running at the time was `vpnkit.exe`. I may or may not have been involved in the crash.

In any case a userspace program like `vpnkit.exe` should not be able crash the kernel. So, this looks like a Windows kernel bug. Can you make sure you have all updates installed. Could you maybe also make the minidump available. We could ask someone at MSFT to take a look.

**Comment by rn** [comment]
@PabloMessina 

I loaded the crash dumps into `windbg` and hit `!analyze -v`. I attached the output, but:
- First minidump (`072117-6500-01.dmp`):  The crash is in `nsiproxy.sys`
- Second minidump (`072017-9328-01.dmp`): This is a crash in `vmbusr!PipeCreate+2b` while `vpnkit.exe` was running. See stack trace below.
- Third minidump (`072117-6281-01.dmp`): Same as second. Crash in `vmbusr!PipeCreate+2b` while `vpnkit.exe` was running.

I don't know if this coincidence or accidental memory corruption which happens to hit the same pool...but I'm certain that this should not be cause by Docker for Windows. I see if I can get some from MSFT to take a look.


Stack trace from second minidump:
```
STACK_TEXT:  
ffffc880`88371e98 fffff803`2c57f8a9 : 00000000`0000000a 00000000`00000008 00000000`00000002 00000000`00000000 : nt!KeBugCheckEx
ffffc880`88371ea0 fffff803`2c57de7d : ffffb109`5dbf14f0 00000000`00000000 00000000`00000002 ffffb109`5dbf1060 : nt!KiBugCheckDispatch+0x69
ffffc880`88371fe0 fffff803`2c687a64 : ffffc880`88372448 ffffc880`883722b0 00000000`ffffffff fffff803`2c46d5ba : nt!KiPageFault+0x23d
ffffc880`88372170 fffff80d`6198a23b : 00000000`00000000 ffff9580`b78ebe60 ffff9580`a4842500 fffff803`00000000 : nt!ExAllocatePoolWithTag+0x6c4
ffffc880`88372260 fffff80d`619ba321 : ffff9580`b78ebb30 ffff9580`b78ebe60 00000002`00000000 00000000`00000000 : vmbusr!PipeCreate+0x2b
ffffc880`88372290 fffff80d`619b9de1 : ffff9580`b78ebb30 00000000`00000000 ffffc880`7cc40ba0 fffff803`2c68765c : hvsocket!VmbusTlXPartCreatePipe+0x35
ffffc880`883722c0 fffff80d`619b61fe : ffff9580`b78ebb30 ffff9580`b78ebb30 00000000`00000000 ffff9580`a9d6ca40 : hvsocket!VmbusTlXPartRootSetupConnection+0x121
ffffc880`883724b0 fffff80d`619b30b0 : ffff9580`b78ebb30 ffffc880`88372580 ffffc880`88372690 ffff9580`b78ebb30 : hvsocket!VmbusTlSetupConnection+0x19a
ffffc880`88372510 fffff80d`6291a011 : ffff9580`00000200 ffff9580`00000000 ffff9580`b78ebb30 ffff9580`b5944830 : hvsocket!VmbusTlProviderConnect+0x630
ffffc880`883725c0 fffff80d`6291d1e7 : ffff9580`b5c577b0 ffff9580`b5c57958 00000000`00000000 00000000`00000001 : afd!AfdConnect+0x6e1
ffffc880`88372770 fffff803`2c89e6ef : ffff9580`b103fba0 00000000`00000000 00000000`00000000 00000000`00000000 : afd!AfdDispatchDeviceControl+0x77
ffffc880`883727a0 fffff803`2c89e4f4 : ffff9580`00000000 ffff9580`b103fb04 fffff780`000002dc ffffc880`88372b00 : nt!IopSynchronousServiceTail+0x1af
ffffc880`88372860 fffff803`2c89d716 : 9580ad57`afb0ffff 00000000`00000268 00000000`00000000 00000000`00000000 : nt!IopXxxControlFile+0xdc4
ffffc880`883729a0 fffff803`2c57f413 : 00000000`00000000 00000000`00000001 00000000`00000001 00000000`00000000 : nt!NtDeviceIoControlFile+0x56
ffffc880`88372a10 00007fff`e9cd5484 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13
00000000`1953f868 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007fff`e9cd5484
```
So this is likely `vpnkit.exe` trying to open a Hyper-V socket connection which tries to do a memory allocation and then something is corrupted. Could be similar with @roelkok.

[072117-6500-01.txt](https://github.com/docker/for-win/files/1180900/072117-6500-01.txt)
[072117-6500-01.txt](https://github.com/docker/for-win/files/1180924/072117-6500-01.txt)
[072117-6281-01.txt](https://github.com/docker/for-win/files/1180949/072117-6281-01.txt)

**Comment by roelkok** [comment]
@rn Hi, would it be helpful if I would post my minidumps as well? I'm not at my machine that has the minidumps at the moment but I can post them tomorrow.

**Comment by rn** [comment]
@roelkok I think two of @PabloMessina dumps are essentially the same as yours. It's a fault at the same offset in the same function as I found out after I replied to your post. It might be useful to have the dump but not urgent. I basically can't do anymore and have pinged some folks as this seems to be an issue in Windows.

**Comment by zerefel** [comment]
Same issue here, running `docker-compose` with 4 containers. Crashing every 30-40 minutes.
Minidump: 
![Minidump](http://i.imgur.com/Gda30Co.png)

**Comment by Morosko** [comment]
Same problem here. Diagnostic ID: B4F782B4-FC80-416E-A18A-EA10AE58F4EF/2017-08-02_12-35-55
Is there a temporary fix yet?

**Comment by JonasProgrammer** [comment]
+1, happens once every 3 days up to every 3 hours, depending on the system's mood. To me it seems to occur much more often (though not exclusively) when I have a browser open and connected to a container running fenglc's pgadmin4 image.
The component crashing is, according to windbg, nsiproxy.sys most of the time though, rather than the VM bus driver itself.

**Comment by dmikheev** [comment]
+1, according to windbg:
Probably caused by : vmswitch.sys ( vmswitch!VmsNblHelperAllocateMdlAndData+56 )

**Comment by jhowardmsft** [comment]
@PabloMessina Thanks for all the great information and memory dumps so far. I was chatting to one of the HVSocket devs here, and we would appreciate it if you could use driver verifier to enable us to get some more information in another `memory.dmp` as we haven't been able to repro this in-house so far.

From an elevated command prompt on the host, run

```verifier /volatile /flags 0x1 /adddriver hvsocket.sys hvsocketcontrol.sys vmbusr.sys```

The above takes effect immediately without a reboot being needed. Note it won't persist across reboots (including a bugcheck).

Thanks so much!

**Comment by Renkas** [comment]
I'm having same problem - occasional BSODs. And after yesterdays W10 update the CPU load has skyrocketed. Process using it is: WmiPrvSE.exe. Which seems to be somehow also tied to Hyper-V as I understand?

I tried the verifier command and this lowered the CPU usage significantly - from ~30% to ~5% - but it's still odd constant load.

**Comment by PabloMessina** [comment]
@jhowardmsft, I just run the command as per your instructions. This is what I got:

![image](https://user-images.githubusercontent.com/6187545/29149934-4f1b2dd0-7d45-11e7-90e7-f90456fe6d2c.png)

By the way, a few days after I started getting the BSODs I just gave up and uninstalled Docker and disabled Hyper-V, I don't know if that has any impact on the command's output but I'm letting you know just in case.

**Comment by jhowardmsft** [comment]
> By the way, a few days after I started getting the BSODs I just gave up and uninstalled Docker and disabled Hyper-V, I don't know if that has any impact on the command's output but I'm letting you know just in case.

Oh :( Then you won't hit the repo. Perhaps someone else could try with verifier enabled on this thread and provide the memory.dmp file?

That output looks correct :)

**Comment by PabloMessina** [comment]
@jhowardmsft, I can reinstall Docker, Hyper-V and reproduce the scenario again, but right now I'm kind of busy. Maybe this weekend I will have time do it though.

**Comment by jhowardmsft** [comment]
💚 Thank you!

**Comment by p4ul** [comment]
I am getting a similar issue. Attached is 4 minidump files (running windows 10, trying to run unit tests on a python instance of docker)

The latest one was different, it happened awhile after running 
`verifier /volatile /flags 0x1 /adddriver hvsocket.sys hvsocketcontrol.sys vmbusr.sys`

[crashes.zip](https://github.com/docker/for-win/files/1213471/crashes.zip)

**Comment by jhowardmsft** [comment]
@p4ul Thanks, I'll pass that on for investigation. Not sure if it's related or not currently.

**Comment by Renkas** [comment]
@jhowardmsft I now got a DRIVER_VERIFIER_DETECTED_VIOLATION  BSOD

Here's the dump: [081017-12343-01.zip](https://github.com/docker/for-win/files/1215131/081017-12343-01.zip)

PS! Right now I have disabled Hyper-V and Docker is not running. But I see that this BSOD is linked to the verifier command you gave earlier

**Comment by jhowardmsft** [comment]
@Renkas Awesome! I've forward this on for investigation.

**Comment by dmikheev** [comment]
For me error changed to PAGE_FAULT_IN_FREED_SPECIAL_POOL when I turned on driver verifier. I would send a memory dump but its size for me is 2,5 Gb (maybe the reason is that I enabled driver verifier for all drivers).

**Comment by PabloMessina** [comment]
@jhowardmsft, I haven't had the time to reinstall docker and reproduce the setting again. That being said, a few minutes ago I got a totally unexpected CRITICAL_STRUCTURE_CORRUPTION BSOD (minidump: https://drive.google.com/file/d/0B42QoVvPwhLkal91TWFRSmQ2SFU/view?usp=sharing), this is my fourth BSOD since I bought my laptop on January, but this the first time it happens without using Docker, so it totally took me by surprise. I wasn't doing nothing special, just chatting through Telegram, had Chrome opened with some tabs, listening to music, and that would be it. I would really appreciate any feedback regarding this last BSOD, maybe there is an underlying problem that links this BSOD with the previous ones. What steps should I take? Thank you in advance!

**Comment by kheldorin** [comment]
@jhowardmsft  Has anyone found a workaround? I'm crashing quite often. Here is my dump. The error changed with the verifier enabled for me. Dump:  https://drive.google.com/open?id=0B8b4FdfLYI8MUXNLa2xyYlZ3ZW8

**Comment by jngutteridge** [comment]
Hi @kheldorin 

I've worked around the issue by uninstalling Docker for Windows, disabling Hyper-V in the Windows "Turn Windows features on or off" settings, and installing Docker Toolbox, which is the VirtualBox based version.

This means I can still use Docker in a similar manner but without any crashes.

I think it's the only workaround until this issue is resolved.

**Comment by mayankgureja** [comment]
I'm having the same issues. BSODs every few hours. I've uninstalled/reinstalled everything and continue to have the issue.

The errant modules are nsiproxy.sys and ntoskrnl.exe. I don't 100% know if it's related but I updated Docker to the latest version last week and that's when the issues started. Before that I hadn't updated in quite a few months and I was working without issues.

Windows 10, Hyper-V, Docker CE.

**Comment by Sieabah** [comment]
I'm getting these bluescreens every 30 minutes if docker is running, effectively halting all development.

**Comment by Angelinsky7** [comment]
+1
same here... if someone want my minidmp file i have 3 of them per day :-)

**Comment by elmarlg** [comment]
Try installing the most recent Docker update for windows which was released a few days ago (think last week). I'm not getting any more blue screens since. I'm running Windows 10 Enterprise N Version 1703.

**Comment by Angelinsky7** [comment]
I'm up to date with the stable channel.

**Comment by elmarlg** [comment]
Yes. That is indeed the version that I am using. This is why I prefer Linux. I think this is more of a Windows / HyperV issue than a Docker issue.

**Comment by mayankgureja** [comment]
The issue has become worse. Now I get BSOD every 30mins. I have confirmed the issue only occurs when Docker is running. Otherwise no crashes occur.

**Comment by rn** [comment]
To be clear, docker for windows should not be able to casue a BSOD it's just a Hyper-V VM and a service running on Windows. However from the original minidump it looks like it is triggering a bug in  the Hyper-V socket subsystem which in turn cause the BSOD. As far as I know Microsoft is still investigating this.

In the meantime if you have the issue, instead of just saying "me too" it would be useful to provide at least the Windows build number (e.g., output of `[System.Environment]::OSVersion.Version`) and ideally a link to a minidump (or even better a stackbacktrace from the minidump) so that folks can look at it and determine if this is the same issue.

**Comment by elmarlg** [comment]
I agree. Also, just make sure that your Windows 10 is running update 1703 along with all the latest updates as well as the latest version of docker for Windows. Ever since the latest August update, I am NOT getting ANY crashes or issues and I am running multiple containers all at one time requiring quite a bit of resources.

**Comment by nelsonlaquet** [comment]
I had a BSOD last week and one just now. Since my machine never bluescreens, this is concerning. Both times I had a docker-compose up with four services, all running some variant of alpine. Also, one of the services was a node application running in development mode, with two webpack watchers - one of which had hot module replacement enabled. There are multiple volumes mounted from the host to the containers.

I had multiple browser windows connected to the node application. So there were at least four websocket connections from the host to the container, which receive notifications on file changes. I do not recall if I had just made a file modification when the BSOD happened.

[Here are both of my minidumps](https://github.com/docker/for-win/files/1282878/Dumps.zip), but from what I can see they closely mirror what people have already posted.

Windows: 10.0.15063.0
Docker: 17.06.2-ce-win27 (13194)

There are no pending system updates.

Interestingly, I did make one change today to the node application. Usually I start the node process without debugging. However, today I had to debug something, so I added the "--inspect=0.0.0.0:9229" flag to the node process, and attached a debugger from the host (vscode).

**Comment by nelsonlaquet** [comment]
I switched to using Docker Toolbox last night and had no more BSODs. I'm going to continue to use docker toolbox until this issue is resolved, and I'll post another update if it fails... but so far this seems to be the only way around this issue for now.

So here's a quick guide of how I got things running. I'm sure most of you guys already know all this stuff, but I'm posting it anyway for people who may have only used docker for windows in the past.

1. Disable hyper-v

   Docker Toolbox uses VirtualBox and for... reasons... you can't have hyper-v enabled when using any other virtualization tech.

   Simply execute this from an elevated command line:
   
   `bcdedit /set hypervisorlaunchtype off`

2. Uninstall docker for windows
3. Restart
4. [Install docker toolbox](https://www.docker.com/products/docker-toolbox)
5. Launch "Docker Quickstart Terminal" (this will configure Virtual Box the first time you run it)

Now you're good to go! There are a few issues, however:

1. Docker commands do not automatically connect to the VirtualBox machine
   
   If you want to run docker or docker-compose from a command line _other_ than the Docker Quickstart Terminal, you're going to have to setup some environment variables. Simply use docker-machine - it will be configured with this box under "default".
   
   For example, if you want to use Powershell, you must run
   
   `docker-machine env --shell powershell default | Invoke-Expression`
   
   In every powershell instance that you wish to use docker and docker-compose in.

2. Shared folders do not work by default unless they are under C:\Users

   The only folder that is shared by default is C:\Users. This isn't quite acceptable, since I host all of my code on a drive other than my system drive (good idea to avoid npm/yarn from murdering my SSD with 10.5 billion writes every second). The solution is simple, however. Docker commands will automatically map windows paths from volume mounts to unix-style paths, so all you have to do is share out any root folder that hosts your code in a way that can be mapped back.
   
   As an example, all of my code is hosted under E:\Users\Nelson\Projects. So I can get volume mounts to work if I made any of these shared folder mappings:
   
   - e -> E:\
   - e/Users -> E:\Users
   - e/Users/Nelson/Projects -> E:\Users\Nelson\Projects

   etc. To do this, open up Oracle VM VirtualBox Manager, find a VM named "default", go to "settings -> shared folders" and create a new entry.

   Now restart the machine (via the VM manager or docker-machine).

3. Docker toolbox doesn't automatically start when you log in

   This is pretty simple, you just have to launch the Docker Quickstart Terminal every time you restart. This will spool up the VM. You could also use docker-machine for this, but it's easier to use the Quickstart Terminal IMO.
   
4. Logs from docker-compose in docker toolbox cut off the last line

   This is the most infuriating issue. The last line of output from docker-compose is cut off in both powershell and the Docker Quickstart Terminal. The solution is to run
   
   `docker-compose logs -f`
   
   In a separate terminal/powershell window, and use that to monitor your services. At this point you may as well run docker-compose in daemon mode.

So other than those issues, everything went smoothly. Like I said, I'll post back if I get another BSOD from Docker Toolbox.

**Comment by Sieabah** [comment]
@nelsonlaquet How unfortunate, I'm just going to stick to using a different OS for the time being until this issue gets fixed. Whether it is a Docker or Hyper-V issue I don't think the relevant parties have given a hint that they're working on it.

**Comment by victorbush** [comment]
I seem to be having the same issue. Windows 10 Pro build 1703. Docker CE version 17.06.2-ce-win27 (13194).

> On Thu 9/7/2017 11:56:11 PM GMT your computer crashed
crash dump file: C:\Windows\Minidump\090717-8921-01.dmp
This was probably caused by the following module: ntoskrnl.exe (nt+0x16C560) 
Bugcheck code: 0xC5 (0x8, 0x2, 0x0, 0xFFFFF8009969AA64)
Error: DRIVER_CORRUPTED_EXPOOL
file path: C:\Windows\system32\ntoskrnl.exe
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: NT Kernel & System

I'm running docker-compose with four containers. Hyper-V enabled.

**Comment by Sieabah** [comment]
Anyone still having this issue on 17.09?

**Comment by Angelinsky7** [comment]
Yes, same issue as before, nothing new (already sent info and bug report)

**Comment by MrGekko** [comment]
Yes same issue persists

**Comment by Sieabah** [comment]
It's insulting that this is still stage-0. Just tried it myself and within 15 minutes it bluescreened. It's a consistent bluescreen issue...

@rn Is there an open thread at Microsoft for further development on this issue since it's a Hyper-V issue?

**Comment by Sieabah** [comment]
This issue also seems to affect 17.03 that I just installed. Guess Docker for-win is gimped by Hyper-V at this point.

**Comment by jrandalldemllo** [comment]
Also getting issue.
Windows 10.0.15063
Docker 17.09.0-ce-win33 (13620)

**Comment by nelsonlaquet** [comment]
This issue is getting a little more attention now, so I'll update you guys with what I've been doing...

Basically, I've gone ahead and entirely stopped using Docker Toolbox or Docker 4 Windows. Instead, I run a lubuntu VM inside of Virtual Box. I run docker inside of that, and run my editor (vscode) inside of it as well (using Unity mode, which makes the vscode window appear as if it's in Windows). I use multiple putty instances connected to the VM over SSH for running docker (and other) commands.

The reason why is that the Virtual Box host mounts are _unbearably_ slow in the context of a Node application. The read performance for a VM accessing a file on the host was causing my builds, tests, and application runs to take over 10+ seconds on every save. This is after a bunch of build-performance optimizations. A simple "require" call on the server could take upwards of 2 seconds, if that "require" call imported multiple nested dependencies. Since node applications typically load in hundreds to thousands of files, the terrible read performance of the mount added up.

Note: webpack builds were very fast, but that's just because webpack keeps all the files in memory and only re-loads what has changed. It was the build performance of my server-side code and the application startup that was insufferable.

With this setup, it takes about half a second to re-build and re-launch my node application on every file save. The editor runs just fine (vscode is cross platform) and looks pretty much identical to my windows instance after I copied over the default consolas font.

With some network configuration kung-fu I'm able to have all of my ports mapped to my host - so I can access my services via "localhost" on my host machine. The only downside is that A) vscode is locked to one monitor (for perf reasons I don't want to enable multi-monitor since I have four) and B) I often forget that vscode is in a VM and try dragging/dropping text files onto it to edit (which doesn't work).

I applaud the effort that the docker team (and others) have done to make docker run "seamlessly" on Windows and MacOS. I wouldn't have been able to get started with docker as quickly if not for their work. But you cannot escape the fact that docker is running in a VM, and the effort on my part to get it running satisfactorily using Toolbox or 4win ended up being greater than me simply biting the bullet and going full-on Linux dev environment.

**Comment by Sieabah** [comment]
@nelsonlaquet I went from that to using 4win because of how unbearably slow and cumbersome it is to work in a VM.

**Comment by wjrogers** [comment]
I was experiencing this issue, but since installing Windows 10 version 1709, I have now gone four days without a crash. Has anyone experienced this crash on Windows 1709? Does anyone have the ability to check whether Microsoft believes this problem is fixed in the latest version of Windows (docker team?)

**Comment by Sieabah** [comment]
@wjrogers I've been holding back making a post but I've been able to run it without bluescreening.

**Comment by jrandalldemllo** [comment]
@wjrogers Also updated to 1709 ~4 days ago, BSOD's seem to have stopped. Have been running Docker non-stop without issues.

**Comment by chimico** [comment]
I have regular crashes. They started after installing 1709.

**Comment by Sieabah** [comment]
@chimico Something I also did was reinstall docker completely and disable and enable hyper-v.

**Comment by chimico** [comment]
@Sieabah No success, but have not had a crash since installing 1710.

**Comment by mayankgureja** [comment]
No BSODs since installing Windows 10 build 1709. Thanks!

**Comment by jhowardmsft** [comment]
(Posting on behalf of the dev team here....)

Is anyone hitting this still on Windows build 1709 (not to be confused with Docker build 17.09 or later). Ie Windows "RS3" or the "Fall Creators Update". That would be Windows build 16299. Telemetry indicates it isn't being hit in latest Windows builds.

**Comment by Sieabah** [comment]
I haven't been hitting it since the update

**Comment by superzadeh** [comment]
Same here, I haven't seen BSODs since that update it seems. Good job to the Dev team! 🎉

**Comment by exinknighthigh** [comment]
Sorry guys. I just updated to the latest Docker on Windows 10 and got the bluescreen error. My minidump points to the same problem.  This is the 3rd time since the beginning of December. Here is my config:

Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/01/12 11:49:12.128
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

**Comment by jhowardmsft** [comment]
@exinknighthigh Yes, but that isn't RS3, it's RS2. We believe it's fixed in the platform in RS3.

> BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

**Comment by penleychan** [comment]
I am also experiencing BSOD after installing Docker. Seems to be something to do wit hyper-v and linux container. I can trigger the BSOD after reboot from running verifier.exe /standard /all then wait awhile until docker initialize during startup.

Switching to Windows Container seems to stop BSOD, but that's not what I want.

**Comment by KoduIsGreat** [comment]
I'm still receiving this issue intermittently windows 10 . Is this being worked on? its pretty infuriating to deal with.

**Comment by jhowardmsft** [comment]
@KoduIsGreat Are you on RS3 or an insider build?

**Comment by KoduIsGreat** [comment]
I'm still on RS2, this machine is managed by my companies IT department, not sure when they're rolling to RS3 (not important enough for that kind of information 🤷‍♂️ )
