### ISSUE TITLE
Docker stuck in "is starting": Failed to connect to database

### ISSUE THREAD

**Issue by pinoniq** [docker/for-win#922]
### Expected behavior
Docker starts on windows boot

### Actual behavior
Docker is stuck in the "is starting" mode and fails after X minutes

### Information

Actual error after a couple of minutes:
```
The process cannot access the file 'C:\WINDOWS\TEMP\b2322z43.kb5' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile)
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs)
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings)
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings)
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Log:
```
Version: 17.06.0-ce-win18 (12627)
Channel: stable
Sha1: d9b66511e0920fdb4a7ff88b8343f65b46fc07e0
Started on: 2017/07/14 19:15:32.300
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616
File: C:\Users\jme\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[19:15:32.454][GUI            ][Info   ] Starting...
[19:15:33.187][Tracking       ][Info   ] Crash report and usage statistics are enabled
[19:15:33.187][SegmentApi     ][Info   ] Usage statistic: appLaunched
[19:15:33.256][NamedPipeClient][Info   ] Sending Version()...
[19:15:33.272][NamedPipeClient][Info   ] Received response for Version
[19:15:33.272][SegmentApi     ][Info   ] Usage statistic: heartbeat
[19:14:17.870][PowerShell     ][Info   ] Run script...
[19:15:33.272][NamedPipeServer][Info   ] Version()
[19:15:33.272][NamedPipeServer][Info   ] Version done in 00:00:00.
[19:15:33.688][Updater        ][Info   ] Checking for updates on channel stable...
[19:15:33.688][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[19:15:33.703][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[19:15:33.703][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[19:15:33.788][Updater        ][Info   ] We got a new version 12801 which is newer than 12627, asking user.
[19:15:33.788][SegmentApi     ][Info   ] Usage statistic: eventShowUpdateWindow
[19:15:33.880][ApiProxy       ][Info   ] docker proxy: ready
[19:15:33.903][ApiProxy       ][Info   ] proxy >> GET /_ping
[19:15:33.903][ApiProxy       ][Info   ] Dial Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:33.906][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:33.908][ApiProxy       ][Info   ] proxy << GET /_ping
[19:15:33.909][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[19:15:33.909][ApiProxy       ][Info   ] Dial Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:33.909][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:33.917][ApiProxy       ][Info   ] proxy << GET /v1.30/containers/json
[19:15:33.930][NamedPipeClient][Info   ] Received response for Start
[19:15:33.930][DockerDaemonChecker][Info   ] Docker daemon is running
[19:15:33.930][NamedPipeServer][Info   ] Start done in 00:00:00.2263464.
[19:15:33.954][NamedPipeClient][Info   ] Sending Mount(C, COMPANY\jme:**********, Docker.Core.Settings)...
[19:15:33.955][NamedPipeServer][Info   ] Mount(C, COMPANY\jme:**********, Docker.Core.Settings)
[19:15:34.062][SambaShare     ][Info   ] Mount C
[19:15:34.135][Updater        ][Info   ] Check for updates done.
[19:15:34.145][Cmd            ][Info   ] Share name        C
[19:15:34.146][Cmd            ][Info   ] Path              C:\
[19:15:34.146][Cmd            ][Info   ] Remark            
[19:15:34.146][Cmd            ][Info   ] Maximum users     No limit
[19:15:34.146][Cmd            ][Info   ] Users             
[19:15:34.146][Cmd            ][Info   ] Caching           Caching disabled
[19:15:34.147][Cmd            ][Info   ] Permission        COMPANY\jme, FULL
[19:15:34.147][Cmd            ][Info   ] 
[19:15:34.147][Cmd            ][Info   ] The command completed successfully.
[19:15:34.147][Cmd            ][Info   ] 
[19:15:34.168][SambaShare     ][Info   ] "C" is shared
[19:15:34.299][SambaShare     ][Info   ] Username: jme
[19:15:34.299][SambaShare     ][Info   ] Host IP: 10.0.75.1
[19:15:34.299][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,domain=COMPANY
[19:15:34.388][ApiProxy       ][Info   ] proxy >> GET /_ping
[19:15:34.388][ApiProxy       ][Info   ] Dial Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.389][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.390][ApiProxy       ][Info   ] proxy << GET /_ping
[19:15:34.393][ApiProxy       ][Info   ] proxy >> POST /v1.30/images/load?quiet=1
[19:15:34.393][ApiProxy       ][Info   ] Dial Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.394][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.518][ApiProxy       ][Info   ] proxy << POST /v1.30/images/load?quiet=1
[19:15:34.607][ApiProxy       ][Info   ] proxy >> GET /_ping
[19:15:34.607][ApiProxy       ][Info   ] Dial Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.608][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 972f9a6a-70c5-4c7b-ac70-ea89af339700:23a432c2-537a-4291-bcb5-d62504644739
[19:15:34.609][ApiProxy       ][Info   ] proxy << GET /_ping
[19:15:34.620][ApiProxy       ][Info   ] proxy >> POST /v1.30/containers/create [rewriteBinds]
[19:15:34.622][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:34.722][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:34.822][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:34.922][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:35.023][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:35.123][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:35.223][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:35.324][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[19:15:35.424][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
...
```

### Additional info:
Not sure it is usefull, but who knows:
* Company computer with (local) domain account.
* HP Client Security (encryption of disk)
* bitdefender endpoint security tools
* Running linux containers

### How I resolve the issue:
open Task manager and quit docker for windows and docker.service. Relaunch docker for windows.

Most of the time this resolves my issue (not always).

### Steps to reproduce the behavior

  1. reboot windows

**Comment by Dargmuesli** [comment]
This is related to #818, which should have been fixed with the latest update. Make sure to use the newest downloadable version of docker for-win.

**Comment by pinoniq** [comment]
I'm running the newest version of docker. The only thing that changed was the actual error being shown:

```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

The logs are still the same

**Comment by johanwestling** [comment]
Got the same thing as @pinoniq. Thought it was related to the F-Secure SENSE, but it does the same thing even after it's removed.

**Comment by jasonbivins** [comment]
@pinoniq 
Can you share the output of the docker version command?  
Here's the latest stable version:

![image](https://user-images.githubusercontent.com/28021664/28550510-50635002-70af-11e7-9093-66d5153a4df2.png)

**Comment by pinoniq** [comment]
@jasonbivins  I'm running 17.06.0 on channel: stable. When checking for updates, docker tells me I'm up to date.
Is there a way to force the update?

**Comment by Dargmuesli** [comment]
@jasonbivins You need to download the edge build manually from the Docker store.
On https://store.docker.com/editions/community/docker-ce-desktop-windows (not at the top!). Or click here: https://download.docker.com/win/edge/InstallDocker.msi

**Comment by parkshinhye** [comment]
@Dargmuesli my docker is Latest beta，but Still have this bug

**Comment by stphngrtz** [comment]
#911

**Comment by stphngrtz** [comment]
This is related to #911 and as far as I can tell even #953 #927 #941

**Comment by netspark** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/706621/31273198-d8875c9a-aa8d-11e7-95fe-42c5b7e604cd.png)

**Comment by hoegge** [comment]
Same issue with latest version:
Diagnostic ID: E9CBF190-66D5-420A-A5A8-9FA5D6D52443/2017-10-09_07-56-50

**Comment by TheWalletInspector** [comment]
Yep same issue.
[10:42:33.155][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.

![image](https://user-images.githubusercontent.com/11511859/31416104-bcd3efac-ae72-11e7-806a-1c2f9caa03c5.png)

**Comment by pbarker-nic** [comment]
Using Latest stable for Windows - Docker not starting. Restarting can help as work around. 
Crash Report:
D8D4BBFD-A028-4A1C-B942-4AA6B046B38B/2017-11-03_09-09-45

**Comment by megamorf** [comment]
I have the same issue, it started with not being able to mount Drives into docker and now docker for windows doesn't start at all due to `Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified`

Report: 4381CF8A-FEFC-4D2F-8D37-327BF2FA6EAA/2017-11-08_20-42-30

**Comment by megamorf** [comment]
same issue as in #911?

**Comment by Zarkopafilis** [comment]
Happened today to me as well. I wasn't using docker before. Yesterday I made some images and messed around with some containers. Only thing I changed regarding docker settings was to change dns from automatic to 8.8.8.8

**Comment by megamorf** [comment]
I found a different github issue that mentioned this error could occur if the hostname of the docker host exceeds 12 characters (check in PowerShell with `(hostname).length`). I renamed my host but it didn't help, I had to fully reinstall docker, losing all my downloaded and custom built images.

**Comment by YAmikep** [comment]
Same issue.
Restarting Docker seems to work, though. 

Version: 17.09.0-ce-win33 (13620)
Channel: stable
Report: 31DA7061-EB83-4773-B93B-9E512FE73528/2017-11-15_08-42-12

**Comment by Zarkopafilis** [comment]
Can confirm that it works after a restart here as well. Hostname is 15 characters.

**Comment by ohad-G** [comment]
Same issue.
Workaround by restarting Docker
Version 17.09.0-ce-win33

**Comment by dutch3883** [comment]
same for me here

**Comment by HaroldMills** [comment]
I see this issue also, using Docker 17.09.1-ce on Windows 10 Pro. If I configure Docker to start when I log in, the start fails but a subsequent manual restart succeeds. If I configure Docker not to start when I log in, an initial manual start fails but a subsequent manual restart succeeds. I have submitted crash reports for several of the failures, and will attach a sample log.

[log.txt](https://github.com/docker/for-win/files/1601818/log.txt)

**Comment by PrasannaMondkar** [comment]
Same Issue ... came today. Version : 17.06.1-ce-win24 (13025) (Stable Channel)
Restart of Docker fixes it. 
Thanks YAmikep

**Comment by rn** [comment]
Could you please try the latest stable or edge version. We have removed the database in those releases. You may still have issues, but we'd need a diagnostics upload to diagnose it.
