### ISSUE TITLE
Docker fails to restart with custom Network Plugin using WSL2

### ISSUE THREAD

**Issue by Skazzino** [docker/for-win#9282]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E03BA140-75E0-49BC-ACD7-E4D4D8171C8E/20201028102604

### Expected behavior
Using WSL2, restarting Docker with custom Network Plugin enabled should not produce any error.

### Actual behavior
Using WSL2, restarting Docker with custom Network Plugin enabled produces a **Failed to restart error** and forces the user to Reset to Factory Defaults each time.

### Information
  - Windows Version: 2004 Build 19041.508
  - Docker Desktop Version: tried with Stable 2.4.0.0 and Edge 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

We use a custom network plugin. The source is available [here](https://github.com/KatharaFramework/NetworkPlugin/tree/iptables). The plugin conditionally mounts `/run/xtables.lock` file if WSL2 is used (since nftables is not fully supported, so we fallback to iptables with xtables). If the file is mounted inside the container, the Engine crashes every time you try to restart Docker Desktop. While, if the file is not mounted, everything works correctly. 
Funny thing is that we also mount other stuff from host `/run` into container `/run` and everything works without any problem. 
Same source code and Docker plugin is used on other OSes (and also on Docker Desktop with Hyper-V) without any bugs.

### Steps to reproduce the behavior
  1. Enable WSL2 support
  2. Install custom network plugin with this command `docker plugin install kathara/katharanp xtables_lock.source="/run/xtables.lock"`
  3. Enable the plugin (if disabled)
  4. Restart Docker Desktop

**Comment by simonferquel** [comment]
Can you send a diagnostic ? I have the feeling that /run/xtables.lock is not there in the docker service namespace.

**Comment by Skazzino** [comment]
Hi @simonferquel,
actually the thing is quite strange. If you install the plugin (mounting xtables.lock as I wrote in step n2) everything works correctly (so xtables.lock is there). The error only occurs when Docker Desktop is restarted.

However, here's a Diagnostic: E03BA140-75E0-49BC-ACD7-E4D4D8171C8E/20201028102604

**Comment by simonferquel** [comment]
Hmm, I see dockerd failing to start with the following logs:
```
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.965330300Z" level=info msg="Starting up"
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.965374000Z" level=warning msg="Running experimental build"
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.966199500Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.966737000Z" level=warning msg="could not change group /run/guest-services/docker.sock to docker: group docker not found"
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.968282100Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.968323500Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.968348100Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/desktop-containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.968359600Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.971262600Z" level=info msg="parsed scheme: \"unix\"" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.971306300Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.971325800Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/desktop-containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
2020-10-28T10:25:36Z dockerd time="2020-10-28T10:25:36.971335800Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.074821100Z" level=error msg="failed to enable plugin" error="OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting \"/run/xtables.lock\" to rootfs at \"/var/run/xtables.lock\" caused: stat /run/xtables.lock: no such file or directory: unknown" id=c649e96b08f94b0ab36b4d8515580c706288a4230dc4823bec55faf7eeb3ac30
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.080579500Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103146400Z" level=warning msg="Your kernel does not support cgroup blkio weight"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103185800Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103195100Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103201200Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103207800Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103213900Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.103395900Z" level=info msg="Loading containers: start."
2020-10-28T10:25:37Z dockerd time="2020-10-28T10:25:37.105053500Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '4.19.128-microsoft-standard': No such file or directory\n, error: exit status 1"
2020-10-28T10:25:37Z dockerd panic: runtime error: invalid memory address or nil pointer dereference
2020-10-28T10:25:37Z dockerd [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x89bf01]
2020-10-28T10:25:37Z dockerd 
2020-10-28T10:25:37Z dockerd goroutine 1 [running]:
2020-10-28T10:25:37Z dockerd github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0x0, 0xc000ae0f20, 0x1d, 0x3040260, 0xc0009537d0, 0x1, 0x0, 0x0, 0x0, 0xc000a8e940, ...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/pkg/plugins/client.go:160 +0x1e1
2020-10-28T10:25:37Z dockerd github.com/docker/docker/pkg/plugins.(*Client).CallWithOptions(0x0, 0xc000ae0f20, 0x1d, 0x0, 0x0, 0x2bed0a0, 0xc0009537a0, 0x0, 0x0, 0x0, ...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/pkg/plugins/client.go:113 +0x10e
2020-10-28T10:25:37Z dockerd github.com/docker/docker/pkg/plugins.(*Client).Call(...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/pkg/plugins/client.go:102
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote.(*driver).call(0xc0009ca1c0, 0x1f9dedf, 0xf, 0x0, 0x0, 0x3041ec0, 0xc0009537a0, 0x40ed1a, 0x20)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote/driver.go:127 +0xd9
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote.(*driver).getCapabilities(0xc0009ca1c0, 0xc0009ca1c0, 0xc0004058c0, 0xc000a8ebe0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote/driver.go:90 +0x79
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote.Init.func1(0xc0007a2120, 0x18, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote/driver.go:37 +0x9a
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote.Init(0x30775e0, 0xc000191500, 0x0, 0x0, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/remote/driver.go:57 +0x1cb
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry.(*DrvRegistry).AddDriver(...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go:72
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/docker/libnetwork.New(0xc00004eb80, 0x9, 0x10, 0xc0004cc150, 0xc000938750, 0xc00004eb80, 0x9)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:221 +0x4f0
2020-10-28T10:25:37Z dockerd github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc00000c1e0, 0xc0000d6100, 0xc000938750, 0x0, 0x0, 0x0, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/daemon/daemon_unix.go:851 +0xa9
2020-10-28T10:25:37Z dockerd github.com/docker/docker/daemon.(*Daemon).restore(0xc00000c1e0, 0xc000b351c0, 0xc000b3c0e0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/daemon/daemon.go:461 +0x50b
2020-10-28T10:25:37Z dockerd github.com/docker/docker/daemon.NewDaemon(0x30a4ca0, 0xc000b351c0, 0xc0000d6100, 0xc0004cc150, 0x0, 0x0, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/daemon/daemon.go:1093 +0x2b6d
2020-10-28T10:25:37Z dockerd main.(*DaemonCli).start(0xc000aaa750, 0xc000aa4420, 0x0, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/cmd/dockerd/daemon.go:195 +0x743
2020-10-28T10:25:37Z dockerd main.runDaemon(...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:13
2020-10-28T10:25:37Z dockerd main.newDaemonCommand.func1(0xc000405080, 0xc000a41960, 0x0, 0x7, 0x0, 0x0)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:34 +0x7c
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc000405080, 0xc00004e090, 0x7, 0x7, 0xc000405080, 0xc00004e090)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:842 +0x462
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000405080, 0x0, 0x0, 0x16)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:950 +0x34b
2020-10-28T10:25:37Z dockerd github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:887
2020-10-28T10:25:37Z dockerd main.main()
2020-10-28T10:25:37Z dockerd 	/go/src/github.com/docker/docker/cmd/dockerd/docker.go:97 +0x191
```
@chris-crone who would be able to help debug this issue ?

@Skazzino by any chance, do you know if it happened before latest Edge release ? (which contains dockerd in v20.10.0 beta 1)

**Comment by simonferquel** [comment]
Oh, sorry I just saw you said it also happen on stalbe 2.4.0. (so not a 20.10.0 specific issue)

**Comment by simonferquel** [comment]
Can you enable debug mode in the daemon configuration so that the logs get more complete and capture a new diagnostic ?
You can access the daemon configuration in Docker Desktop settings, in Docker Engine section (just put `"debug" : true` in the json config file)

**Comment by Skazzino** [comment]
> 
> 
> Can you enable debug mode in the daemon configuration so that the logs get more complete and capture a new diagnostic ?
> You can access the daemon configuration in Docker Desktop settings, in Docker Engine section (just put `"debug" : true` in the json config file)

Hi @simonferquel,
new diagnostic uploaded with debug enabled: E03BA140-75E0-49BC-ACD7-E4D4D8171C8E/20201029090926

**Comment by simonferquel** [comment]
Hmm diagnostic file got corrupted somehow :( can you upload a new one ?

**Comment by Skazzino** [comment]
> 
> 
> Hmm diagnostic file got corrupted somehow :( can you upload a new one ?

There you go: E03BA140-75E0-49BC-ACD7-E4D4D8171C8E/20201029094821

**Comment by thaJeztah** [comment]
Looks like the panic / nill-pointer-exception originates from https://github.com/moby/moby/blob/v19.03.13/pkg/plugins/client.go#L160

But I see the mod probe error, which looks a bit fishy;

```
Running modprobe bridge br_netfilter failed with message:
modprobe: can't change directory to '4.19.128-microsoft-standard': No such file or directory,
error: exit status 1
```

**Comment by simonferquel** [comment]
@thaJeztah this is one particularity of wsl2: as you can run multiple distros in their own mount namespace, in the same wsl utility vm, they decided to avoid using kernel modules, and bake all the modules inside the kernel itself. So all modprobe fail, but it is not usually an issue.

**Comment by Skazzino** [comment]
Maybe this line is also helpful:
```2020-10-28T10:25:37Z` dockerd time="2020-10-28T10:25:37.074821100Z" level=error msg="failed to enable plugin" error="OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting \"/run/xtables.lock\" to rootfs at \"/var/run/xtables.lock\" caused: stat /run/xtables.lock: no such file or directory: unknown" id=c649e96b08f94b0ab36b4d8515580c706288a4230dc4823bec55faf7eeb3ac30```

Seems like when the WSL2 backend is started, that file is not in place. But after the startup it is regularly mounted.

**Comment by simonferquel** [comment]
Yes, I would be interested in knowing what creates it.
As a workaround, you can probably mount `/run` instead.
Also please note that Docker runs in its own mount namespace. So the content of its /run directory is not the same as what you see in your distro's `/run`

**Comment by Skazzino** [comment]
We already tried to mount the whole `/run` into the plugin, but it crashes because it is not possible to overwrite the container `/run`.

**Comment by simonferquel** [comment]
Oh yes. Something dirty (but which probably work):
- mount /run into `/host-run`
- at the startup of the container, create a link such as `ln -s /host-run/xtables.lock /run/xtables.lock` ? (dont to this in the dockerfile, at runtime, a tmpfs is likely to be mounted over the images `/run` dir)

**Comment by Skazzino** [comment]
> 
> 
> Oh yes. Something dirty (but which probably work):
> 
>     * mount /run into `/host-run`
> 
>     * at the startup of the container, create a link such as `ln -s /host-run/xtables.lock /run/xtables.lock` ? (dont to this in the dockerfile, at runtime, a tmpfs is likely to be mounted over the images `/run` dir)

We also tried this nasty workaround, but iptables locks the link (and it is not propagated on the real file in `/host-run`), so iptables randomly reports `iptables: Resource temporarily unavailable`.

Before opening this issue we tried every trick we could imagine! :smile:

**Comment by simonferquel** [comment]
Hmm indeed, that is a problem.
The root of the issue is that iptables does create the lockfile on first call, and only in the mount namespace it runs within.
Docker daemon and the network plugin run in the same network namespaces, but not in the same mount namespace and they both manipulate iptables (this is why the plugin reports this error - they lock a different file). So we need to create the file before running docker, so that it can be mounted on startup by the plugin.

I'll file an issue in Docker Desktop (it is an easy fix).

Thanks for the report!

**Comment by Skazzino** [comment]
Great! Thanks a lot!
Let us know when the fix is applied into Docker Desktop and when an Edge Release with this patch is available so we can test it.

**Comment by simonferquel** [comment]
Actually I have a custom build (based on our current development branch, so might not be totally stable) that you could try to validate the issue is fixed: https://desktop-stage.docker.com/win/edge/49332/Docker%20Desktop%20Installer.exe
Let me know!

**Comment by Skazzino** [comment]
Hi @simonferquel,
still crashing: E03BA140-75E0-49BC-ACD7-E4D4D8171C8E/20201029155737

**Comment by simonferquel** [comment]
(still can't open the diagnostic file for some reason...) 
Can you look at `%AppData%\Docker\log\vm\dockerd.log` (it is the docker daemon log file streamed from WSL) ? It may contain log entries from previous versions, so just look at the latest startup attempt.

**Comment by Skazzino** [comment]
[dockerd.log](https://github.com/docker/for-win/files/5459745/dockerd.log)

I truncated everything except the last "boostrap"

**Comment by simonferquel** [comment]
Ok, I'll try to debug it locally a bit further. Sorry about the false hope :/

**Comment by Skazzino** [comment]
> Ok, I'll try to debug it locally a bit further. Sorry about the false hope :/

No worries, take your time! 😄

**Comment by simonferquel** [comment]
Was a typo :/. Got it to work locally, signed build is cooking now. I'll share you the link to unblock you when it is ready.

**Comment by simonferquel** [comment]
https://desktop-stage.docker.com/win/edge/49337/Docker%20Desktop%20Installer.exe

**Comment by Skazzino** [comment]
This one works like a charm!

Thank you really much for you efforts!

Just one last thing, could you please notify me when this patch is released? So we can update the wiki of our tool and suggest users to update to this version.

**Comment by simonferquel** [comment]
As the fix is actually very simple, it will ship in both next Edge and Stable versions (most of the time, we first ship fixes in Edge before merging them in a stable release).
I'll let you know when this is avaialable.

**Comment by stephen-turner** [comment]
Stable 2.5.0.0 is now released and contains the fix.
