### ISSUE TITLE
Docker command did not complete within the allowed timeout

### ISSUE THREAD

**Issue by LostKatana** [docker/for-win#941]
### Expected behavior
Docker should start with windows
### Actual behavior
Docker does not start and reports an error
```
    Docker command did not complete within the allowed timeout. Output: 
       at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
       at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
       at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
       at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
       at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
       at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
       at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information

  - Diagnostic ID: CA370BA2-3323-4876-AC18-E426A0FBFEBB/2017-07-20_09-15-32
  - Windows 10 Pro Version 1703 Systembuild 15063.413
  - Docker 17.06.0-ce-win19 (12801)

### Steps to reproduce the behavior

  1. Happens on startup

### Temporary Fix

  1. Go to Settings --> Reset --> Restart Docker...

**Comment by k25nick** [comment]
Just got this as well, I don't have docker set to start on login. This was on starting docker some time after starting windows. Same version: 17.06.0-ce-win19 (12801). Restarting docker worked.

I do have a large Oracle image running which takes some time to start, so it would have been starting that one up. Don't know whether that would have contributed to the timeout? Didn't see any issues with previous versions of Docker.

**Comment by b-mille** [comment]
I had the same issue after the last released (i had the issue #893 too). 

It was a firewall issue with Avast, in my case. I've turned DocketNAT adapter to Private in Avast and now it's OK. 

The log line was "Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.".

So check your firewall maybe !

**Comment by laurin1** [comment]
Mine would not work no matter how many times I restarted. Based on Docker.Backend.SambaShare, I surmised it was due to Shared Drives being enabled. I disabled that feature, which locked up the UI, I had to quit it, then when I started Docker, this time it worked. I was then able to go back in and enable Shared Drives (C) again. 

To test. Quit Docker. Started. This time it started fine as well.

FYI, I'm on Edge:

Version 17.06.1-ce-rc1-win20 (12818)
Channel: edge
28a0bb2

**Comment by into1head** [comment]
Thanks dude, restart the docker from settings works!

**Comment by shipleyr** [comment]
I get this every time I start windows and have to go into settings to restart docker.

**Comment by runemoennike** [comment]
Getting this every time I start docker, without it being set to autostart. Have to go into settings and select restart.

**Comment by jmanuelsoberano** [comment]
I have the same detail, **although it is solved restarting the docker**, if it is annoying to be restarting every time I log in to my operating system

> Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by laurin1** [comment]
I downgraded from Edge to Stable (17.06.0-ce-win19 (12801)) and now I can at least Quit Docker and restart it to get it working again, but still crashing.

**Comment by laurin1** [comment]
Sometimes, I can't even Quit Docker - it gets stuck on "Docker will shut down" and I have to End Task to kill it and then restart.

**Comment by shortspider** [comment]
I am also having this issue. The error is the exact same and it can be 'solved' by restarting docker once the error has popped up.

I am running Windows 10. Docker version outputs:

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

Looking in the log file there are tons of these:

[23:26:58.918][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.

**Comment by morrisalp** [comment]
Same issue as @laurin1 including the System Tray menu freezing. Also, when I open Docker settings I get a loading cursor icon, the window says "Docker is starting...", and I am unable to select anything.

**Comment by immunochomik** [comment]
I have the same problem 

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by LostKatana** [comment]
I didn't had this isse now for several weeks.
What I did was, as we have CD and need to change password every onca a while, heading into settings and reset docker. Befor that I removed my shared devices and after the restart I reconnected them.

**Comment by immunochomik** [comment]
It looks like the docker service is in some broken state, looks like it helps to restart it.

**Comment by hanalice** [comment]
I have the same issue, thanks for @laurin1 answer.  My local  file protection software caused docker can not start and close correctly and quickly. Once I closed my local file protection software, my docker can run immediately.

**Comment by jorispz** [comment]
Same here, every single day Docker doesn't start but restarting invariably works.

Diagnostic ID: CC7AEFCD-008F-4600-A672-E1E9046087A9/2017-08-18_08-51-37

Since somebody mentioned file protection software, I'll just mention we're running the Trend Micro Security Agent (can't turn it off to test if that solves anything though)

**Comment by Amdingo** [comment]
Also crashing when attempting to have a drive mounted via the settings interface.

085A929F-6C54-4094-938A-C5D5EC8D3739/2017-08-20_18-18-08

**Comment by hussonkevin** [comment]
Got the same issue for a long time on Windows 10 with Hyper-V and I just resolve it this morning by manually allowed to Windows Firewall the followings apps :
- C:\Program Files\Docker\Docker\Docker for Windows.exe
- C:\Program Files\Docker\Docker\DockerCli.exe

Hopes this can help

**Comment by transifex3** [comment]
@hussonkevin oh yeah, it worked for me :-)

**Comment by laurin1** [comment]
@hussonkevin Incoming Rules?

**Comment by atthakorn** [comment]
In my experience, the issue only/always happens in cold boot (shutdown + power on) but it never occur if just restart windows or resume back from hypernate



The neither of these solution are solving error in my machine
- reset to factory default
- add firewall rule for DockerCli.exe / Docker for Windows.exe
- set startup delay for docker service
- set start up delay for docker for windows (using 3rd party app e.g.  Startup Delayer)



Finally, I managed to get rid the issue by **turn off the Fast Startup** feature of Win10, pls follow this steps to disable it.


- Go to windows setting -> System (display, notifications, power) -> Power & Sleep
- Click **Additional power setting** 
- then open **Choose what the power button do**
- then check off the Turn of fast startup

Please see the screenshot below.

![fast startup](https://user-images.githubusercontent.com/463654/29650558-f65eabcc-88c5-11e7-8437-47c9b2ba8319.jpg)



The big bonus is, as soon as windows started, the docker for windows (in tarkbar) is very quickly up and running.

**Comment by tbonz** [comment]
@atthakorn Thank you! I am cautiously optimistic, but so far this fix has worked for me too.

**Comment by tianyou6842** [comment]
@atthakorn Thank you! Disable "Turn on fast startup" has also solved this Docker problem for me.

**Comment by Maelstromeous** [comment]
It's also crashing on mine. Looked at the logs and it said it was unable to mount one of my drives, which I have set up to expose to docker.

I don't have the log entry to hand, will acquire as it's happening reliably after a cold boot.

**Comment by zcanann** [comment]
+1

No luck with firewall exceptions. I'd prefer to not have to disable fast startup on my desktop as a work-around.

**Comment by transifex3** [comment]
@atthakorn It seems be right solution.
I noticed yesterday that this problem has been occurred again even i have added docker on firewall exception.
And remembered i did restart docker after changing firewall setting.
So i just simply restarted docker application, and it worked. guessing it's related with cold boot problem somehow?

**Comment by jeffbarnes769** [comment]
'bcdedit /set hypervisorlaunchtype auto' fixes the docker on startup problem as well.  Info on bcedit can be found on stackoverflow and elsewhere.  Thanks to user: https://stackoverflow.com/users/2364438/tvs for pointing this out in another thread

**Comment by laurin1** [comment]
@jeffbarnes769 that post (https://stackoverflow.com/questions/39541163/docker-for-windows-cant-reach-the-database-in-windows-10-enterprise-evaluation) does not appear to be the same issue as this one - have you (or someone) verified that the bcdedit also fixes this issue? I don't want to be messing with my boot configuration unnecessarily.

**Comment by jeffbarnes769** [comment]
Thanks laurin1
The bcedit fix was not consistent.  It seemed to work for a couple of days (a number of reboots), but the problem still occurs on occasion.  Also tried adding 'docker.exe' as an allowed app in the firewall rules.    

Wondering if the issues is related to a memory leak many are reporting in windows 10.  There are a number of fixes or workarounds for the memory leak, with varying results.

**Comment by jchv** [comment]
@atthakorn Another cautiously optimistic reply, this may have fixed my problems too. I cold boot nearly every day, so this seems highly likely to have been my problem. Furthermore, I don't even need fast startup because I'm booting on SSD and it makes maybe a 1-2 second difference... so this seems like a win win to me.

**Comment by jchv** [comment]
OK, Docker has started up successfully every day of the week. I think disabling Fast Startup legitimately fixed it for me.

**Comment by Bango1999** [comment]
Docker has started up consistently for me after disabling fast startup.   Many thanks @atthakorn that was really bugging me.

@LostKatana I think this will solve your problem.

**Comment by deyvisonrocha** [comment]
@atthakorn Works for me! Thank you.

**Comment by laurin1** [comment]
On one of my machines (that just failed this more on a logoff and logon, did not even restart), I don't even have this setting.

**Comment by jeffbarnes769** [comment]
Thanks @atthakorn.  Not only has Docker started consistently after disabling fast startup, it also had a positive impact on the Windows 10 memory leak.  It is much less of a problem than before.
Thanks again

**Comment by laurin1** [comment]
On the machine where I can not disable Fast Startup, Docker has timed out 3 times this morning! I can't get it to start at all now.

**Comment by laurin1** [comment]
Ok, so I disabled this via the Registry (using Group Policy), but considering this is failing on a manual start, I don't have a lot of faith that this setting is my problem.

**Comment by jeffbarnes769** [comment]
Hi Keith, disabling fast startup has worked consistently on a number of
windows 10 enterprise and home edition PC's.  Did it work at all (for a
while anyway).  For me very recent windows and other updates has had an
effect on some related services (specifically minikube), but it's no longer
the 'timed out' issue.

**Comment by laurin1** [comment]
Well, this machine that I am referring to has this features disabled using GPO (Registry):

HiberbootEnabled = 0

But I just logged off and back on and the timeout just occurred.

**Comment by laurin1** [comment]
In  fact, I've tried to start it 3 times now, and all 3 times have failed (killed the process and started it).

**Comment by jeffbarnes769** [comment]
Did you disable fast startup via the following steps?

Type Control Panel in the search box.
Click Control Panel.
Click Power Options.
Click Choose what the power buttons do.
Click Change settings that are currently unavailable.
Scroll down to Shutdown settings and uncheck Turn on fast startup.
Click Save changes/reboot

**Comment by laurin1** [comment]
No, I can't:

> On one of my machines (that just failed this more on a logoff and logon, did not even restart), I don't even have this setting. I just realized, Hibernate has to be enabled for this setting to be available. We disabled Hibernate via GPO. So if I don't have this setting, but still have this problem, how can that setting be the issue?

I disabled it via GPO using the registry key. 

http://mywindowshub.com/how-to-turn-on-or-off-fast-startup-in-windows-10/

**Comment by atthakorn** [comment]
since docker **17.09.0-ce-win32 (13529)** as stated in release note

> Windows Docker daemon is now started as service for better lifecycle management

My gut told me to re-enable 'fast startup'  then I had multiple experiments of cold boot.  It just works and docker starts really fast.

docker for windows is no longer crash even the fast start up turn on.  It seems docker daemon as windows service is very responsive.  Super cool!

**Comment by Dargmuesli** [comment]
v13529 did not fix this for me, but v13620 seems like it did. Let's see if Docker keeps starting correctly or if this bug reappears.

Update notes:

> 17.09.0-ce-win33 (13620)
> Upgrades
> 
> Docker 17.09.0-ce 
> Docker compose 1.16.1 
> Docker Machine 0.12.2 
> Docker Credential Helpers 0.6.0 
> Linux Kernel 4.9.49 
> AUFS 20170911 
> 
> New
> 
> Windows Docker daemon is now started as service for better lifecycle management 
> Store Linux daemon configuration in ~.docker\daemon.json instead of settings file 
> Store Windows daemon configuration in C:\ProgramData\Docker\config\daemon.json instead of settings file 
> VPNKit: add support for ping! 
> VPNKit: add slirp/port-max-idle-timeout to allow the timeout to be adjusted or even disabled 
> VPNKit: bridge mode is default everywhere now 
> Add Skip This version button in update window 
> Security fixes
> 
> VPNKit: security fix to reduce the risk of DNS cache poisoning attack (reported by Hannes Mehnert https://hannes.nqsb.io/) 
> Bug fixes and minor changes
> 
> Fix Docker For Windows unable to start in some cases : removed use of libgmp sometimes causing the vpnkit process to die. 
> Kernel: Enable TASK_XACCT and TASK_IO_ACCOUNTING 
> Rotate logs in the VM more often (docker/for-win#244) 
> Reset to default stops all engines and removes settings including all daemon.json files 
> Better backend service checks (related to https://github.com/docker/for-win/issues/953) 
> Fix auto updates checkbox, no need to restart the application 
> Fix check for updates menu when auto updates was disable 
> VPNKit: do not block startup when ICMP permission is denied. (Fixes docker/for-win#1036, docker/for-win#1035, docker/for-win#1040) 
> VPNKit: change protocol to support error messages reported back from the server 
> VPNKit: fix a bug which causes a socket to leak if the corresponding TCP connection is idle for more than 5 minutes (related to docker/for-mac#1374) 
> VPNKit: improve the logging around the Unix domain socket connections 
> VPNKit: automatically trim whitespace from int or bool database keys 
> Do not anymore move credentials in credential store at startup

**Comment by jeffbarnes769** [comment]
Disabling fast start also fixed some performance issues I was having.
Leaving it disabled for now.  Thanks for the update

**Comment by atthakorn** [comment]
Just to leave note for win docker team

it relapse again after upgrading to  **Version 17.09.0-ce-win33 (13620)** with Fast Startup  

Turn off fast startup still solving issue.

**Comment by michael-x** [comment]
I've had the same timeout issue as the OP. Therfore I've tried setting the Docker windows service to 'delayed start', but it looks like the Docker UI thinks it has full control over the service and refuses to accept that it does in fact start, just a little bit later. No matter which UI option you use when asked whether the Docker UI should start the (already started) Docker service results in an error message. When you then go to 'Settings...' -> 'Reset' -> 'Restart Docker...', Docker 'restarts' rather quickly, so it looks at if it just reconnects to the already running service at that point in time.

**Comment by jchv** [comment]
If you've upgraded to RS3 just recently, Fast Startup may have been re-enabled for you. So don't forget to go back and disable it.

**Comment by genei09** [comment]
what is the method to make use of:
VPNKit: add slirp/port-max-idle-timeout to allow the timeout to be adjusted or even disabled

I would like to disable it

**Comment by Jayflux** [comment]
For me it doesn't just happen on startup, it happens the first time i start up Docker, i always have to restart it

**Comment by Bango1999** [comment]
The latest update claims to fix the docker startup issues, **but for me it still doesn't**.

I rechecked hibernate and fast startup options from my power management settings, and performed a shutdown and startup.  It worked... the first time.

Then I tried a shutdown and startup a second time, and like the other times before, docker startup procedure hung up and failed due to timeout.

(Win 10 pro, hyper-v enabled)

**Comment by jasonwilliams** [comment]
Its been much better for me lately

**Comment by LostKatana** [comment]
I haven't experienced it any more and as the last comment came in on december i will now close this.
Thanks!

**Comment by zcanann** [comment]
If you did the "turn off the Fast Startup" workaround, now is probably a good time to re-enable it.
